/**
 * Generates src/glass-icons/: one module per icon in the Sakani icon set.
 *
 *   node scripts/glass-icons/generate.mjs
 *
 * The set is the Figma "Icons" component set (figma-icons.json, 1,626 names).
 * Each name is taken from lucide-react's own shape data (__iconNode); the few
 * Lucide no longer ships (brand logos) come from figma-extra.json.
 *
 * Every <path> is split into its subpaths and each element is tagged closed or
 * open (see closed.mjs), so the renderer fills only shapes that are really
 * closed. Re-run after upgrading lucide-react or changing the Figma set.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isClosed, splitPath } from './closed.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../..');
const lucideDir = path.join(root, 'node_modules/lucide-react/dist/esm/icons');
const outDir = path.join(root, 'src/glass-icons');
const iconsDir = path.join(outDir, 'icons');

const { names } = JSON.parse(fs.readFileSync(path.join(here, 'figma-icons.json'), 'utf8'));
const extra = JSON.parse(fs.readFileSync(path.join(here, 'figma-extra.json'), 'utf8')).icons;
const lucideVersion = JSON.parse(fs.readFileSync(path.join(root, 'node_modules/lucide-react/package.json'), 'utf8')).version;

const pascal = (n) => n.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
const round = (v) => (typeof v === 'number' ? +v.toFixed(4) : v);

function expand(node) {
  const out = [];
  for (const [tag, attrs] of node) {
    // Paint is the renderer's job; an element Lucide fills on purpose (the dots
    // in chart-scatter) is simply treated as closed.
    const { key: _key, fill, stroke: _stroke, ...rest } = attrs;
    const forcedFill = fill && fill !== 'none';
    for (const k of Object.keys(rest)) rest[k] = round(rest[k]);
    if (tag === 'path') {
      for (const piece of splitPath(rest.d)) out.push(['path', { ...rest, d: piece.d }, piece.closed || forcedFill ? 1 : 0]);
    } else {
      out.push([tag, rest, isClosed([tag, rest]) || forcedFill ? 1 : 0]);
    }
  }
  return out;
}

fs.rmSync(iconsDir, { recursive: true, force: true });
fs.mkdirSync(iconsDir, { recursive: true });

const header = (source) =>
  `// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.\n// Shape data: ${source}\n`;

const exports = [];
const stats = { lucide: 0, figma: 0, missing: [], aliases: [], closedElements: 0, elements: 0 };

for (const name of names) {
  let node, source;
  const file = path.join(lucideDir, `${name}.mjs`);
  if (extra[name]) {
    node = extra[name].map((d) => ['path', { d }]);
    source = `Sakani Figma icon set, icon "${name}"`;
    stats.figma++;
  } else if (fs.existsSync(file)) {
    // Renamed icons survive as alias modules that only re-export the new one
    // ("export { default } from './trash.mjs'"); follow the chain to the data.
    let target = file, via = null;
    for (let hop = 0; hop < 4; hop++) {
      const alias = /export \{ default \} from '\.\/([\w-]+)\.mjs'/.exec(fs.readFileSync(target, 'utf8'));
      if (!alias) break;
      via = alias[1];
      target = path.join(lucideDir, `${alias[1]}.mjs`);
    }
    const mod = await import(target);
    if (mod.__iconNode) {
      node = mod.__iconNode;
      source = `lucide-react ${lucideVersion} (ISC), icon "${via ?? name}"${via ? ` (alias of "${name}")` : ''}`;
      stats.lucide++;
      if (via) stats.aliases.push(`${name}->${via}`);
    }
  }
  if (!node) { stats.missing.push(name); continue; }

  const data = expand(node);
  stats.elements += data.length;
  stats.closedElements += data.filter((e) => e[2]).length;
  const comp = `Glass${pascal(name)}`;
  fs.writeFileSync(
    path.join(iconsDir, `${name}.ts`),
    `${header(source)}import { createGlassIcon } from '../createGlassIcon';\n\n` +
      `export const ${comp} = /*#__PURE__*/ createGlassIcon(${JSON.stringify(name)}, ${JSON.stringify(data)});\n` +
      `export default ${comp};\n`,
  );
  exports.push({ name, comp });
}

const index =
  `${header(`${stats.lucide} icons from lucide-react ${lucideVersion}, ${stats.figma} from the Sakani Figma icon set`)}` +
  `export { GlassIcon, GlassIconSvg, createGlassIcon, GLASS_ICON_TONES } from './createGlassIcon';\n` +
  `export type { GlassIconProps, GlassIconTone, GlassIconVariant, GlassIconNode, GlassIconComponent } from './createGlassIcon';\n` +
  `export { glassIconNames } from './names';\n` +
  `export type { GlassIconName } from './names';\n\n` +
  exports.map(({ name, comp }) => `export { ${comp} } from './icons/${name}';`).join('\n') + '\n';
fs.writeFileSync(path.join(outDir, 'index.ts'), index);

fs.writeFileSync(
  path.join(outDir, 'names.ts'),
  `${header('Figma "Icons" component set')}export const glassIconNames = ${JSON.stringify(exports.map((e) => e.name))} as const;\n\nexport type GlassIconName = (typeof glassIconNames)[number];\n`,
);

console.log(`glass icons: ${exports.length} generated (${stats.lucide} lucide, ${stats.figma} figma)`);
console.log(`elements: ${stats.elements}, closed (filled): ${stats.closedElements}`);
console.log(`aliases followed: ${stats.aliases.length}`);
const dupes = stats.aliases.filter((a) => names.includes(a.split('->')[1]));
if (dupes.length) console.log(`aliases that now draw the same shape as another icon in the set (${dupes.length}): ${dupes.join(', ')}`);
if (stats.missing.length) { console.error('MISSING:', stats.missing.join(', ')); process.exit(1); }
