// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "a-arrow-up"
import { createGlassIcon } from '../createGlassIcon';

export const GlassAArrowUp = /*#__PURE__*/ createGlassIcon("a-arrow-up", [["path",{"d":"M14 11l4 -4l4 4"},0],["path",{"d":"M18 16V7"},0],["path",{"d":"M2 16l4.039 -9.69a0.5 0.5 0 0 1 0.923 0L11 16"},0],["path",{"d":"M3.304 13h6.392"},0]]);
export default GlassAArrowUp;
