// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "a-large-small"
import { createGlassIcon } from '../createGlassIcon';

export const GlassALargeSmall = /*#__PURE__*/ createGlassIcon("a-large-small", [["path",{"d":"M15 16l2.536 -7.328a1.02 1.02 1 0 1 1.928 0L22 16"},0],["path",{"d":"M15.697 14h5.606"},0],["path",{"d":"M2 16l4.039 -9.69a0.5 0.5 0 0 1 0.923 0L11 16"},0],["path",{"d":"M3.304 13h6.392"},0]]);
export default GlassALargeSmall;
