// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "text-align-end" (alias of "align-right")
import { createGlassIcon } from '../createGlassIcon';

export const GlassAlignRight = /*#__PURE__*/ createGlassIcon("align-right", [["path",{"d":"M21 5H3"},0],["path",{"d":"M21 12H9"},0],["path",{"d":"M21 19H7"},0]]);
export default GlassAlignRight;
