// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "align-center-vertical"
import { createGlassIcon } from '../createGlassIcon';

export const GlassAlignCenterVertical = /*#__PURE__*/ createGlassIcon("align-center-vertical", [["path",{"d":"M12 2v20"},0],["path",{"d":"M8 10H4a2 2 0 0 1 -2 -2V6c0 -1.1 0.9 -2 2 -2h4"},0],["path",{"d":"M16 10h4a2 2 0 0 0 2 -2V6a2 2 0 0 0 -2 -2h-4"},0],["path",{"d":"M8 20H7a2 2 0 0 1 -2 -2v-2c0 -1.1 0.9 -2 2 -2h1"},0],["path",{"d":"M16 14h1a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h-1"},0]]);
export default GlassAlignCenterVertical;
