// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "align-center-horizontal"
import { createGlassIcon } from '../createGlassIcon';

export const GlassAlignCenterHorizontal = /*#__PURE__*/ createGlassIcon("align-center-horizontal", [["path",{"d":"M2 12h20"},0],["path",{"d":"M10 16v4a2 2 0 0 1 -2 2H6a2 2 0 0 1 -2 -2v-4"},0],["path",{"d":"M10 8V4a2 2 0 0 0 -2 -2H6a2 2 0 0 0 -2 2v4"},0],["path",{"d":"M20 16v1a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2v-1"},0],["path",{"d":"M14 8V7c0 -1.1 0.9 -2 2 -2h2a2 2 0 0 1 2 2v1"},0]]);
export default GlassAlignCenterHorizontal;
