// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ampersands"
import { createGlassIcon } from '../createGlassIcon';

export const GlassAmpersands = /*#__PURE__*/ createGlassIcon("ampersands", [[["M10 17C5 14 3 10 3 8A2 2 0 0 1 7 8C7 10.5 2 10.5 2 14C2 15.7 3.3 17 5 17C7.8 17 10 14.8 10 12",0],["M22 17C17 14 15 10 15 8A2 2 0 0 1 19 8C19 10.5 14 10.5 14 14C14 15.7 15.3 17 17 17C19.8 17 22 14.8 22 12",0]],[],[20.4,7.6,4.75],1]);
export default GlassAmpersands;
