// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "anchor"
import { createGlassIcon } from '../createGlassIcon';

export const GlassAnchor = /*#__PURE__*/ createGlassIcon("anchor", [["path",{"d":"M12 6v16"},0],["path",{"d":"M19 13l2 -1a9 9 0 0 1 -18 0l2 1"},0],["path",{"d":"M9 11h6"},0],["circle",{"cx":"12","cy":"4","r":"2"},1]]);
export default GlassAnchor;
