// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-big-right"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowBigRight = /*#__PURE__*/ createGlassIcon("arrow-big-right", [["path",{"d":"M13.207 19.793a0.707 0.707 0 0 1 -1.207 -0.5V16a1 1 0 0 0 -1 -1H5a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h6a1 1 0 0 0 1 -1V4.707a0.707 0.707 0 0 1 1.207 -0.5l6.94 6.94a1.207 1.207 0 0 1 0 1.707z"},1]]);
export default GlassArrowBigRight;
