// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-up-from-dot"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowUpFromDot = /*#__PURE__*/ createGlassIcon("arrow-up-from-dot", [["path",{"d":"M5 9l7 -7l7 7"},0],["path",{"d":"M12 16V2"},0],["circle",{"cx":"12","cy":"21","r":"1"},1]]);
export default GlassArrowUpFromDot;
