// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-down-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowDownLeft = /*#__PURE__*/ createGlassIcon("arrow-down-left", [["path",{"d":"M17 7L7 17"},0],["path",{"d":"M17 17H7V7"},0]]);
export default GlassArrowDownLeft;
