// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-up-from-dot"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowUpFromDot = /*#__PURE__*/ createGlassIcon("arrow-up-from-dot", [[["M5 9L12 2L19 9",0],["M12 16L12 2",0],["M11 21A1 1 0 1 0 13 21A1 1 0 1 0 11 21Z",0]],[],[17.4,3.6,4.75],1]);
export default GlassArrowUpFromDot;
