// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-down-right"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowDownRight = /*#__PURE__*/ createGlassIcon("arrow-down-right", [["path",{"d":"M7 7l10 10"},0],["path",{"d":"M17 7v10H7"},0]]);
export default GlassArrowDownRight;
