// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-down-z-a"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowDownZA = /*#__PURE__*/ createGlassIcon("arrow-down-z-a", [["path",{"d":"M3 16l4 4l4 -4"},0],["path",{"d":"M7 4v16"},0],["path",{"d":"M15 4h5l-5 6h5"},0],["path",{"d":"M15 20v-3.5a2.5 2.5 0 0 1 5 0V20"},0],["path",{"d":"M20 18h-5"},0]]);
export default GlassArrowDownZA;
