// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-down-a-z"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowDownAZ = /*#__PURE__*/ createGlassIcon("arrow-down-a-z", [["path",{"d":"M3 16l4 4l4 -4"},0],["path",{"d":"M7 20V4"},0],["path",{"d":"M20 8h-5"},0],["path",{"d":"M15 10V6.5a2.5 2.5 0 0 1 5 0V10"},0],["path",{"d":"M15 14h5l-5 6h5"},0]]);
export default GlassArrowDownAZ;
