// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-down-from-line"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowDownFromLine = /*#__PURE__*/ createGlassIcon("arrow-down-from-line", [["path",{"d":"M19 3H5"},0],["path",{"d":"M12 21V7"},0],["path",{"d":"M6 15l6 6l6 -6"},0]]);
export default GlassArrowDownFromLine;
