// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-big-down"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowBigDown = /*#__PURE__*/ createGlassIcon("arrow-big-down", [["path",{"d":"M9 5a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v6a1 1 0 0 0 1 1h3.293a0.707 0.707 0 0 1 0.5 1.207l-7.086 7.086a1 1 0 0 1 -1.414 0l-7.086 -7.086a0.707 0.707 0 0 1 0.5 -1.207H8a1 1 0 0 0 1 -1z"},1]]);
export default GlassArrowBigDown;
