// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-up-wide-narrow"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowUpWideNarrow = /*#__PURE__*/ createGlassIcon("arrow-up-wide-narrow", [["path",{"d":"M3 8l4 -4l4 4"},0],["path",{"d":"M7 4v16"},0],["path",{"d":"M11 12h10"},0],["path",{"d":"M11 16h7"},0],["path",{"d":"M11 20h4"},0]]);
export default GlassArrowUpWideNarrow;
