// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-down"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowDown = /*#__PURE__*/ createGlassIcon("arrow-down", [["path",{"d":"M12 5v14"},0],["path",{"d":"M19 12l-7 7l-7 -7"},0]]);
export default GlassArrowDown;
