// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-big-down-dash"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowBigDownDash = /*#__PURE__*/ createGlassIcon("arrow-big-down-dash", [[["M14 8A1 1 0 0 1 15 9L15 11A1 1 0 0 0 16 12L19.293 12A0.707 0.707 0 0 1 19.793 13.207L12.854 20.146A1.207 1.207 0 0 1 11.146 20.146L4.206 13.206A0.707 0.707 0 0 1 4.706 12L8 12A1 1 0 0 0 9 11L9 9A1 1 0 0 1 10 8Z",1]],[["M9 4L15 4",0]],[18.399,9.6,4.75],0]);
export default GlassArrowBigDownDash;
