// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-down-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowDownLeft = /*#__PURE__*/ createGlassIcon("arrow-down-left", [[["M17 7L7 17",0],["M17 17L7 17L7 7",0]],[],[16.3,7.7,3.25],1]);
export default GlassArrowDownLeft;
