// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-big-right"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowBigRight = /*#__PURE__*/ createGlassIcon("arrow-big-right", [[["M13.207 19.793A0.707 0.707 0 0 1 12 19.293L12 16A1 1 0 0 0 11 15L5 15A1 1 0 0 1 4 14L4 10A1 1 0 0 1 5 9L11 9A1 1 0 0 0 12 8L12 4.707A0.707 0.707 0 0 1 13.207 4.207L20.147 11.147A1.207 1.207 0 0 1 20.147 12.854Z",1]],[],[18.896,5.601,4.75],0]);
export default GlassArrowBigRight;
