// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-up-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowUpLeft = /*#__PURE__*/ createGlassIcon("arrow-up-left", [["path",{"d":"M7 17V7h10"},0],["path",{"d":"M17 17L7 7"},0]]);
export default GlassArrowUpLeft;
