// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-up-right"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowUpRight = /*#__PURE__*/ createGlassIcon("arrow-up-right", [[["M7 7L17 7L17 17",0],["M7 17L17 7",0]],[],[16.3,7.7,3.25],1]);
export default GlassArrowUpRight;
