// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-down-to-dot"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowDownToDot = /*#__PURE__*/ createGlassIcon("arrow-down-to-dot", [[["M12 2L12 16",0],["M19 9L12 16L5 9",0],["M11 21A1 1 0 1 0 13 21A1 1 0 1 0 11 21Z",0]],[],[17.4,3.6,4.75],1]);
export default GlassArrowDownToDot;
