// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-up"
import { createGlassIcon } from '../createGlassIcon';

export const GlassArrowUp = /*#__PURE__*/ createGlassIcon("arrow-up", [["path",{"d":"M5 12l7 -7l7 7"},0],["path",{"d":"M12 19V5"},0]]);
export default GlassArrowUp;
