// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "backpack"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBackpack = /*#__PURE__*/ createGlassIcon("backpack", [[["M4 10A4 4 0 0 1 8 6L16 6A4 4 0 0 1 20 10L20 20A2 2 0 0 1 18 22L6 22A2 2 0 0 1 4 20Z",1]],[["M8 10L16 10",1],["M8 18L16 18",1],["M8 22L8 16A2 2 0 0 1 10 14L14 14A2 2 0 0 1 16 16L16 22",1],["M9 6L9 4A2 2 0 0 1 11 2L13 2A2 2 0 0 1 15 4L15 6",0]],[18.4,7.6,4.75],0]);
export default GlassBackpack;
