// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "backpack"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBackpack = /*#__PURE__*/ createGlassIcon("backpack", [["path",{"d":"M4 10a4 4 0 0 1 4 -4h8a4 4 0 0 1 4 4v10a2 2 0 0 1 -2 2H6a2 2 0 0 1 -2 -2z"},1],["path",{"d":"M8 10h8"},0],["path",{"d":"M8 18h8"},0],["path",{"d":"M8 22v-6a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v6"},0],["path",{"d":"M9 6V4a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v2"},0]]);
export default GlassBackpack;
