// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "badge-cent"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBadgeCent = /*#__PURE__*/ createGlassIcon("badge-cent", [["path",{"d":"M3.85 8.62a4 4 0 0 1 4.78 -4.77a4 4 0 0 1 6.74 0a4 4 0 0 1 4.78 4.78a4 4 0 0 1 0 6.74a4 4 0 0 1 -4.77 4.78a4 4 0 0 1 -6.75 0a4 4 0 0 1 -4.78 -4.77a4 4 0 0 1 0 -6.76Z"},1],["path",{"d":"M12 7v10"},0],["path",{"d":"M15.4 10a4 4 0 1 0 0 4"},0]]);
export default GlassBadgeCent;
