// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "baggage-claim"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBaggageClaim = /*#__PURE__*/ createGlassIcon("baggage-claim", [["path",{"d":"M22 18H6a2 2 0 0 1 -2 -2V7a2 2 0 0 0 -2 -2"},0],["path",{"d":"M17 14V4a2 2 0 0 0 -2 -2h-1a2 2 0 0 0 -2 2v10"},0],["rect",{"width":"13","height":"8","x":"8","y":"6","rx":"1"},1],["circle",{"cx":"18","cy":"20","r":"2"},1],["circle",{"cx":"9","cy":"20","r":"2"},1]]);
export default GlassBaggageClaim;
