// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bandage"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBandage = /*#__PURE__*/ createGlassIcon("bandage", [["path",{"d":"M10 10.01h0.01"},0],["path",{"d":"M10 14.01h0.01"},0],["path",{"d":"M14 10.01h0.01"},0],["path",{"d":"M14 14.01h0.01"},0],["path",{"d":"M18 6v12"},0],["path",{"d":"M6 6v12"},0],["rect",{"x":"2","y":"6","width":"20","height":"12","rx":"2"},1]]);
export default GlassBandage;
