// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "banknote-arrow-up"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBanknoteArrowUp = /*#__PURE__*/ createGlassIcon("banknote-arrow-up", [["path",{"d":"M12 18H4a2 2 0 0 1 -2 -2V8a2 2 0 0 1 2 -2h16a2 2 0 0 1 2 2v5"},0],["path",{"d":"M18 12h0.01"},0],["path",{"d":"M19 22v-6"},0],["path",{"d":"M22 19l-3 -3l-3 3"},0],["path",{"d":"M6 12h0.01"},0],["circle",{"cx":"12","cy":"12","r":"2"},1]]);
export default GlassBanknoteArrowUp;
