// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "barrel"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBarrel = /*#__PURE__*/ createGlassIcon("barrel", [["path",{"d":"M10 3a41 41 0 0 0 0 18"},0],["path",{"d":"M14 3a41 41 0 0 1 0 18"},0],["path",{"d":"M16.997 21a2 2 0 0 0 1.68 -0.92a15.25 15.25 0 0 0 0 -16.16a2 2 0 0 0 -1.68 -0.92h-10a2 2 0 0 0 -1.681 0.92a15.25 15.25 0 0 0 0 16.16a2 2 0 0 0 1.681 0.92z"},1],["path",{"d":"M3.54 16h16.914"},0],["path",{"d":"M3.54 8h16.914"},0]]);
export default GlassBarrel;
