// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bath"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBath = /*#__PURE__*/ createGlassIcon("bath", [["path",{"d":"M10 4L8 6"},0],["path",{"d":"M17 19v2"},0],["path",{"d":"M2 12h20"},0],["path",{"d":"M7 19v2"},0],["path",{"d":"M9 5L7.621 3.621A2.121 2.121 0 0 0 4 5v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-5"},0]]);
export default GlassBath;
