// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "battery-low"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBatteryLow = /*#__PURE__*/ createGlassIcon("battery-low", [[["M4 6L16 6A2 2 0 0 1 18 8L18 16A2 2 0 0 1 16 18L4 18A2 2 0 0 1 2 16L2 8A2 2 0 0 1 4 6Z",1]],[["M22 14L22 10",0],["M6 14L6 10",1]],[16.4,7.6,4.75],0]);
export default GlassBatteryLow;
