// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "battery-full"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBatteryFull = /*#__PURE__*/ createGlassIcon("battery-full", [["path",{"d":"M10 10v4"},0],["path",{"d":"M14 10v4"},0],["path",{"d":"M22 14v-4"},0],["path",{"d":"M6 10v4"},0],["rect",{"x":"2","y":"6","width":"16","height":"12","rx":"2"},1]]);
export default GlassBatteryFull;
