// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "battery-warning"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBatteryWarning = /*#__PURE__*/ createGlassIcon("battery-warning", [["path",{"d":"M10 17h0.01"},0],["path",{"d":"M10 7v6"},0],["path",{"d":"M14 6h2a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-2"},0],["path",{"d":"M22 14v-4"},0],["path",{"d":"M6 18H4a2 2 0 0 1 -2 -2V8a2 2 0 0 1 2 -2h2"},0]]);
export default GlassBatteryWarning;
