// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bed"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBed = /*#__PURE__*/ createGlassIcon("bed", [["path",{"d":"M2 4v16"},0],["path",{"d":"M2 8h18a2 2 0 0 1 2 2v10"},0],["path",{"d":"M2 17h20"},0],["path",{"d":"M6 8v9"},0]]);
export default GlassBed;
