// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "beer"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBeer = /*#__PURE__*/ createGlassIcon("beer", [[["M5 8L5 20A2 2 0 0 0 7 22L15 22A2 2 0 0 0 17 20L17 8Z",1],["M14 7.5C13 7.5 12.56 8 11 8C9.44 8 9 7.5 8 7.5C7 7.5 6.28 8 5.5 8A2.5 2.5 0 0 1 5.5 3C6.28 3 7.07 3.5 8 3.5C8.93 3.5 9.44 2 11 2C12.56 2 13 3.5 14 3.5C15 3.5 15.72 3 16.5 3A2.5 2.5 0 0 1 16.5 8C15.72 8 15 7.5 14 7.5Z",1]],[["M17 11L18 11A3 3 0 0 1 18 17L17 17",0],["M9 12L9 18",1],["M13 12L13 18",1]],[17.4,3.6,4.75],0]);
export default GlassBeer;
