// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "beer"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBeer = /*#__PURE__*/ createGlassIcon("beer", [["path",{"d":"M17 11h1a3 3 0 0 1 0 6h-1"},0],["path",{"d":"M9 12v6"},0],["path",{"d":"M13 12v6"},0],["path",{"d":"M14 7.5c-1 0 -1.44 0.5 -3 0.5s-2 -0.5 -3 -0.5s-1.72 0.5 -2.5 0.5a2.5 2.5 0 0 1 0 -5c0.78 0 1.57 0.5 2.5 0.5S9.44 2 11 2s2 1.5 3 1.5s1.72 -0.5 2.5 -0.5a2.5 2.5 0 0 1 0 5c-0.78 0 -1.5 -0.5 -2.5 -0.5Z"},1],["path",{"d":"M5 8v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2V8"},0]]);
export default GlassBeer;
