// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bell-electric"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBellElectric = /*#__PURE__*/ createGlassIcon("bell-electric", [["path",{"d":"M18.518 17.347A7 7 0 0 1 14 19"},0],["path",{"d":"M18.8 4A11 11 0 0 1 20 9"},0],["path",{"d":"M9 9h0.01"},0],["circle",{"cx":"20","cy":"16","r":"2"},1],["circle",{"cx":"9","cy":"9","r":"7"},1],["rect",{"x":"4","y":"16","width":"10","height":"6","rx":"2"},1]]);
export default GlassBellElectric;
