// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "between-horizontal-start"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBetweenHorizontalStart = /*#__PURE__*/ createGlassIcon("between-horizontal-start", [["rect",{"width":"13","height":"7","x":"8","y":"3","rx":"1"},1],["path",{"d":"M2 9l3 3l-3 3"},0],["rect",{"width":"13","height":"7","x":"8","y":"14","rx":"1"},1]]);
export default GlassBetweenHorizontalStart;
