// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "biceps-flexed"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBicepsFlexed = /*#__PURE__*/ createGlassIcon("biceps-flexed", [["path",{"d":"M12.409 13.017A5 5 0 0 1 22 15c0 3.866 -4 7 -9 7c-4.077 0 -8.153 -0.82 -10.371 -2.462c-0.426 -0.316 -0.631 -0.832 -0.62 -1.362C2.118 12.723 2.627 2 10 2a3 3 0 0 1 3 3a2 2 0 0 1 -2 2c-1.105 0 -1.64 -0.444 -2 -1"},0],["path",{"d":"M15 14a5 5 0 0 0 -7.584 2"},0],["path",{"d":"M9.964 6.825C8.019 7.977 9.5 13 8 15"},0]]);
export default GlassBicepsFlexed;
