// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "binary"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBinary = /*#__PURE__*/ createGlassIcon("binary", [["rect",{"x":"14","y":"14","width":"4","height":"6","rx":"2"},1],["rect",{"x":"6","y":"4","width":"4","height":"6","rx":"2"},1],["path",{"d":"M6 20h4"},0],["path",{"d":"M14 10h4"},0],["path",{"d":"M6 14h2v6"},0],["path",{"d":"M14 4h2v6"},0]]);
export default GlassBinary;
