// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "biohazard"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBiohazard = /*#__PURE__*/ createGlassIcon("biohazard", [["circle",{"cx":"12","cy":"11.9","r":"2"},1],["path",{"d":"M6.7 3.4c-0.9 2.5 0 5.2 2.2 6.7C6.5 9 3.7 9.6 2 11.6"},0],["path",{"d":"M8.9 10.1l1.4 0.8"},0],["path",{"d":"M17.3 3.4c0.9 2.5 0 5.2 -2.2 6.7c2.4 -1.2 5.2 -0.6 6.9 1.5"},0],["path",{"d":"M15.1 10.1l-1.4 0.8"},0],["path",{"d":"M16.7 20.8c-2.6 -0.4 -4.6 -2.6 -4.7 -5.3c-0.2 2.6 -2.1 4.8 -4.7 5.2"},0],["path",{"d":"M12 13.9v1.6"},0],["path",{"d":"M13.5 5.4c-1 -0.2 -2 -0.2 -3 0"},0],["path",{"d":"M17 16.4c0.7 -0.7 1.2 -1.6 1.5 -2.5"},0],["path",{"d":"M5.5 13.9c0.3 0.9 0.8 1.8 1.5 2.5"},0]]);
export default GlassBiohazard;
