// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bitcoin"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBitcoin = /*#__PURE__*/ createGlassIcon("bitcoin", [["path",{"d":"M11.767 19.089c4.924 0.868 6.14 -6.025 1.216 -6.894"},0],["path",{"d":"M11.767 19.089L5.86 18.047"},0],["path",{"d":"M11.768 19.089l-0.347 1.97"},0],["path",{"d":"M12.984 12.195c4.924 0.869 6.14 -6.025 1.215 -6.893"},0],["path",{"d":"M12.984 12.195l-3.94 -0.694"},0],["path",{"d":"M14.199 5.301L8.29 4.26"},0],["path",{"d":"M14.198 5.302l0.348 -1.97"},0],["path",{"d":"M7.48 20.364l3.126 -17.727"},0]]);
export default GlassBitcoin;
