// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bluetooth-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBluetoothOff = /*#__PURE__*/ createGlassIcon("bluetooth-off", [["path",{"d":"M17 17l-5 5V12l-5 5"},0],["path",{"d":"M2 2l20 20"},0],["path",{"d":"M14.5 9.5L17 7l-5 -5v4.5"},0]]);
export default GlassBluetoothOff;
