// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bookmark-minus"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBookmarkMinus = /*#__PURE__*/ createGlassIcon("bookmark-minus", [["path",{"d":"M15 10H9"},0],["path",{"d":"M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1 -1.496 0.868l-4.512 -2.578a2 2 0 0 0 -1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2 -2z"},1]]);
export default GlassBookmarkMinus;
