// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "book-check"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBookCheck = /*#__PURE__*/ createGlassIcon("book-check", [["path",{"d":"M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1 -1 1H6.5a1 1 0 0 1 0 -5H20"},0],["path",{"d":"M9 9.5l2 2l4 -4"},0]]);
export default GlassBookCheck;
