// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bookmark-check"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBookmarkCheck = /*#__PURE__*/ createGlassIcon("bookmark-check", [[["M17 3A2 2 0 0 1 19 5L19 20A1 1 0 0 1 17.504 20.868L12.992 18.29A2 2 0 0 0 11.008 18.29L6.496 20.868A1 1 0 0 1 5 20L5 5A2 2 0 0 1 7 3Z",1]],[["M9 10L11 12L15 8",1]],[17.4,4.6,4.75],0]);
export default GlassBookmarkCheck;
