// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bow-arrow"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBowArrow = /*#__PURE__*/ createGlassIcon("bow-arrow", [["path",{"d":"M17 3h4v4"},0],["path",{"d":"M18.575 11.082a13 13 0 0 1 1.048 9.027a1.17 1.17 0 0 1 -1.914 0.597L14 17"},0],["path",{"d":"M7 10L3.29 6.29a1.17 1.17 0 0 1 0.6 -1.91a13 13 0 0 1 9.03 1.05"},0],["path",{"d":"M7 14a1.7 1.7 0 0 0 -1.207 0.5l-2.646 2.646A0.5 0.5 0 0 0 3.5 18H5a1 1 0 0 1 1 1v1.5a0.5 0.5 0 0 0 0.854 0.354L9.5 18.207A1.7 1.7 0 0 0 10 17v-2a1 1 0 0 0 -1 -1z"},1],["path",{"d":"M9.707 14.293L21 3"},0]]);
export default GlassBowArrow;
