// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "box"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBox = /*#__PURE__*/ createGlassIcon("box", [["path",{"d":"M21 8a2 2 0 0 0 -1 -1.73l-7 -4a2 2 0 0 0 -2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7 -4A2 2 0 0 0 21 16Z"},1],["path",{"d":"M3.3 7l8.7 5l8.7 -5"},0],["path",{"d":"M12 22V12"},0]]);
export default GlassBox;
