// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "boxes"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBoxes = /*#__PURE__*/ createGlassIcon("boxes", [["path",{"d":"M2.97 12.92A2 2 0 0 0 2 14.63v3.24a2 2 0 0 0 0.97 1.71l3 1.8a2 2 0 0 0 2.06 0L12 19v-5.5l-5 -3l-4.03 2.42Z"},1],["path",{"d":"M7 16.5l-4.74 -2.85"},0],["path",{"d":"M7 16.5l5 -3"},0],["path",{"d":"M7 16.5v5.17"},0],["path",{"d":"M12 13.5V19l3.97 2.38a2 2 0 0 0 2.06 0l3 -1.8a2 2 0 0 0 0.97 -1.71v-3.24a2 2 0 0 0 -0.97 -1.71L17 10.5l-5 3Z"},1],["path",{"d":"M17 16.5l-5 -3"},0],["path",{"d":"M17 16.5l4.74 -2.85"},0],["path",{"d":"M17 16.5v5.17"},0],["path",{"d":"M7.97 4.42A2 2 0 0 0 7 6.13v4.37l5 3l5 -3V6.13a2 2 0 0 0 -0.97 -1.71l-3 -1.8a2 2 0 0 0 -2.06 0l-3 1.8Z"},1],["path",{"d":"M12 8L7.26 5.15"},0],["path",{"d":"M12 8l4.74 -2.85"},0],["path",{"d":"M12 13.5V8"},0]]);
export default GlassBoxes;
