// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "brain-circuit"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBrainCircuit = /*#__PURE__*/ createGlassIcon("brain-circuit", [[["M12 5A3 3 0 1 0 6.003 5.125A4 4 0 0 0 3.477 10.895A4 4 0 0 0 4.033 17.483A4 4 0 1 0 12 18Z",1],["M6.003 5.125A3 3 0 0 0 6.401 6.5",0],["M3.477 10.896A4 4 0 0 1 4.062 10.5",0],["M6 18A4 4 0 0 1 4.033 17.484",0]],[["M9 13A4.5 4.5 0 0 0 12 9",1],["M12 13L16 13",0],["M12 18L18 18A2 2 0 0 1 20 20L20 21",0],["M12 8L20 8",0],["M16 8L16 5A2 2 0 0 1 18 3",0],["M15.5 13A0.5 0.5 0 1 0 16.5 13A0.5 0.5 0 1 0 15.5 13Z",0],["M17.5 3A0.5 0.5 0 1 0 18.5 3A0.5 0.5 0 1 0 17.5 3Z",0],["M19.5 21A0.5 0.5 0 1 0 20.5 21A0.5 0.5 0 1 0 19.5 21Z",0],["M19.5 8A0.5 0.5 0 1 0 20.5 8A0.5 0.5 0 1 0 19.5 8Z",0]],[10.4,3.599,4.75],0]);
export default GlassBrainCircuit;
