// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "brain"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBrain = /*#__PURE__*/ createGlassIcon("brain", [[["M19.967 17.483A4 4 0 1 1 12 18A4 4 0 1 1 4.033 17.483Z",1],["M17.598 6.5A3 3 0 1 0 12 5A3 3 0 1 0 6.402 6.5Z",1]],[["M12 18L12 5",0],["M15 13A4.17 4.17 0 0 1 12 9A4.17 4.17 0 0 1 9 13",0],["M17.997 5.125A4 4 0 0 1 20.523 10.895",0],["M18 18A4 4 0 0 0 20 10.536",0],["M6 18A4 4 0 0 1 4 10.536",0],["M6.003 5.125A4 4 0 0 0 3.477 10.895",0]],[18.392,3.601,4.75],0]);
export default GlassBrain;
