// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "briefcase-medical"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBriefcaseMedical = /*#__PURE__*/ createGlassIcon("briefcase-medical", [["path",{"d":"M12 11v4"},0],["path",{"d":"M14 13h-4"},0],["path",{"d":"M16 6V4a2 2 0 0 0 -2 -2h-4a2 2 0 0 0 -2 2v2"},0],["path",{"d":"M18 6v14"},0],["path",{"d":"M6 6v14"},0],["rect",{"width":"20","height":"14","x":"2","y":"6","rx":"2"},1]]);
export default GlassBriefcaseMedical;
