// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "briefcase-medical"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBriefcaseMedical = /*#__PURE__*/ createGlassIcon("briefcase-medical", [[["M4 6L20 6A2 2 0 0 1 22 8L22 18A2 2 0 0 1 20 20L4 20A2 2 0 0 1 2 18L2 8A2 2 0 0 1 4 6Z",1]],[["M12 11L12 15",1],["M14 13L10 13",1],["M16 6L16 4A2 2 0 0 0 14 2L10 2A2 2 0 0 0 8 4L8 6",0],["M18 6L18 20",1],["M6 6L6 20",1]],[20.4,7.6,4.75],0]);
export default GlassBriefcaseMedical;
