// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "briefcase-business"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBriefcaseBusiness = /*#__PURE__*/ createGlassIcon("briefcase-business", [["path",{"d":"M12 12h0.01"},0],["path",{"d":"M16 6V4a2 2 0 0 0 -2 -2h-4a2 2 0 0 0 -2 2v2"},0],["path",{"d":"M22 13a18.15 18.15 0 0 1 -20 0"},0],["rect",{"width":"20","height":"14","x":"2","y":"6","rx":"2"},1]]);
export default GlassBriefcaseBusiness;
