// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bring-to-front"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBringToFront = /*#__PURE__*/ createGlassIcon("bring-to-front", [["rect",{"x":"8","y":"8","width":"8","height":"8","rx":"2"},1],["path",{"d":"M4 10a2 2 0 0 1 -2 -2V4a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2"},0],["path",{"d":"M14 20a2 2 0 0 0 2 2h4a2 2 0 0 0 2 -2v-4a2 2 0 0 0 -2 -2"},0]]);
export default GlassBringToFront;
