// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bug-play"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBugPlay = /*#__PURE__*/ createGlassIcon("bug-play", [["path",{"d":"M10 19.655A6 6 0 0 1 6 14v-3a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 3.97"},0],["path",{"d":"M14 15.003a1 1 0 0 1 1.517 -0.859l4.997 2.997a1 1 0 0 1 0 1.718l-4.997 2.997a1 1 0 0 1 -1.517 -0.86z"},1],["path",{"d":"M14.12 3.88L16 2"},0],["path",{"d":"M21 5a4 4 0 0 1 -3.55 3.97"},0],["path",{"d":"M3 21a4 4 0 0 1 3.81 -4"},0],["path",{"d":"M3 5a4 4 0 0 0 3.55 3.97"},0],["path",{"d":"M6 13H2"},0],["path",{"d":"M8 2l1.88 1.88"},0],["path",{"d":"M9 7.13V6a3 3 0 1 1 6 0v1.13"},0]]);
export default GlassBugPlay;
