// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bus"
import { createGlassIcon } from '../createGlassIcon';

export const GlassBus = /*#__PURE__*/ createGlassIcon("bus", [["path",{"d":"M8 6v6"},0],["path",{"d":"M15 6v6"},0],["path",{"d":"M2 12h19.6"},0],["path",{"d":"M18 18h3s0.5 -1.7 0.8 -2.8c0.1 -0.4 0.2 -0.8 0.2 -1.2c0 -0.4 -0.1 -0.8 -0.2 -1.2l-1.4 -5C20.1 6.8 19.1 6 18 6H4a2 2 0 0 0 -2 2v10h3"},0],["circle",{"cx":"7","cy":"18","r":"2"},1],["path",{"d":"M9 18h5"},0],["circle",{"cx":"16","cy":"18","r":"2"},1]]);
export default GlassBus;
