// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "calculator"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCalculator = /*#__PURE__*/ createGlassIcon("calculator", [["rect",{"width":"16","height":"20","x":"4","y":"2","rx":"2"},1],["line",{"x1":"8","x2":"16","y1":"6","y2":"6"},0],["line",{"x1":"16","x2":"16","y1":"14","y2":"18"},0],["path",{"d":"M16 10h0.01"},0],["path",{"d":"M12 10h0.01"},0],["path",{"d":"M8 10h0.01"},0],["path",{"d":"M12 14h0.01"},0],["path",{"d":"M8 14h0.01"},0],["path",{"d":"M12 18h0.01"},0],["path",{"d":"M8 18h0.01"},0]]);
export default GlassCalculator;
