// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "calendar-check"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCalendarCheck = /*#__PURE__*/ createGlassIcon("calendar-check", [["path",{"d":"M8 2v3"},0],["path",{"d":"M16 2v3"},0],["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2"},1],["path",{"d":"M3 9h18"},0],["path",{"d":"M9 15l2 2l4 -4"},0]]);
export default GlassCalendarCheck;
