// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "calendar-range"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCalendarRange = /*#__PURE__*/ createGlassIcon("calendar-range", [["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2"},1],["path",{"d":"M16 2v3"},0],["path",{"d":"M3 9h18"},0],["path",{"d":"M8 2v3"},0],["path",{"d":"M17 13h-6"},0],["path",{"d":"M13 17H7"},0],["path",{"d":"M7 13h0.01"},0],["path",{"d":"M17 17h0.01"},0]]);
export default GlassCalendarRange;
