// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "calendar-minus-2"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCalendarMinus2 = /*#__PURE__*/ createGlassIcon("calendar-minus-2", [["path",{"d":"M8 2v3"},0],["path",{"d":"M16 2v3"},0],["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2"},1],["path",{"d":"M3 9h18"},0],["path",{"d":"M10 15h4"},0]]);
export default GlassCalendarMinus2;
