// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "camera-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCameraOff = /*#__PURE__*/ createGlassIcon("camera-off", [["path",{"d":"M14.564 14.558a3 3 0 1 1 -4.122 -4.121"},0],["path",{"d":"M2 2l20 20"},0],["path",{"d":"M20 20H4a2 2 0 0 1 -2 -2V9a2 2 0 0 1 2 -2h1.997a2 2 0 0 0 0.819 -0.175"},0],["path",{"d":"M9.695 4.024A2 2 0 0 1 10.004 4h3.993a2 2 0 0 1 1.76 1.05l0.486 0.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v7.344"},0]]);
export default GlassCameraOff;
