// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "candy-cane"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCandyCane = /*#__PURE__*/ createGlassIcon("candy-cane", [["path",{"d":"M10.8 5l2.111 4.223"},0],["path",{"d":"M17.75 7L15 2.1"},0],["path",{"d":"M4.874 14.647l2.12 4.24"},0],["path",{"d":"M5.7 21a2 2 0 0 1 -3.5 -2l8.6 -14a6 6 0 0 1 10.4 6a2 2 0 1 1 -3.464 -2a2 2 0 1 0 -3.464 -2z"},1],["path",{"d":"M7.906 9.712l2.005 4.411"},0]]);
export default GlassCandyCane;
