// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "case-lower"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCaseLower = /*#__PURE__*/ createGlassIcon("case-lower", [[["M14 12.5A3.5 3.5 0 1 0 21 12.5A3.5 3.5 0 1 0 14 12.5Z",1],["M3 12.5A3.5 3.5 0 1 0 10 12.5A3.5 3.5 0 1 0 3 12.5Z",1],["M10 9L10 16",0]],[["M14 6L14 16",1]],[19.4,10.6,4.75],0]);
export default GlassCaseLower;
