// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "case-lower"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCaseLower = /*#__PURE__*/ createGlassIcon("case-lower", [["path",{"d":"M10 9v7"},0],["path",{"d":"M14 6v10"},0],["circle",{"cx":"17.5","cy":"12.5","r":"3.5"},1],["circle",{"cx":"6.5","cy":"12.5","r":"3.5"},1]]);
export default GlassCaseLower;
