// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cast"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCast = /*#__PURE__*/ createGlassIcon("cast", [["path",{"d":"M2 8V6a2 2 0 0 1 2 -2h16a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-6"},0],["path",{"d":"M2 12a9 9 0 0 1 8 8"},0],["path",{"d":"M2 16a5 5 0 0 1 4 4"},0],["line",{"x1":"2","x2":"2.01","y1":"20","y2":"20"},0]]);
export default GlassCast;
