// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cast"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCast = /*#__PURE__*/ createGlassIcon("cast", [[["M2 8L2 6A2 2 0 0 1 4 4L20 4A2 2 0 0 1 22 6L22 18A2 2 0 0 1 20 20L14 20Z",1]],[["M2 12A9 9 0 0 1 10 20",0],["M2 16A5 5 0 0 1 6 20",0],["M2 20L2.01 20",0]],[20.4,5.6,4.75],0]);
export default GlassCast;
