// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chart-bar"
import { createGlassIcon } from '../createGlassIcon';

export const GlassChartBar = /*#__PURE__*/ createGlassIcon("chart-bar", [[["M3 3L3 19A2 2 0 0 0 5 21L21 21",0],["M7 16L15 16",0],["M7 11L19 11",0],["M7 6L10 6",0]],[],[19.4,4.6,4.75],1]);
export default GlassChartBar;
