// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chart-column-decreasing"
import { createGlassIcon } from '../createGlassIcon';

export const GlassChartColumnDecreasing = /*#__PURE__*/ createGlassIcon("chart-column-decreasing", [["path",{"d":"M13 17V9"},0],["path",{"d":"M18 17v-3"},0],["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"},0],["path",{"d":"M8 17V5"},0]]);
export default GlassChartColumnDecreasing;
