// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chart-bar-decreasing"
import { createGlassIcon } from '../createGlassIcon';

export const GlassChartBarDecreasing = /*#__PURE__*/ createGlassIcon("chart-bar-decreasing", [["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"},0],["path",{"d":"M7 11h8"},0],["path",{"d":"M7 16h3"},0],["path",{"d":"M7 6h12"},0]]);
export default GlassChartBarDecreasing;
