// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chart-pie"
import { createGlassIcon } from '../createGlassIcon';

export const GlassChartPie = /*#__PURE__*/ createGlassIcon("chart-pie", [["path",{"d":"M21 12c0.552 0 1.005 -0.449 0.95 -0.998a10 10 0 0 0 -8.953 -8.951c-0.55 -0.055 -0.998 0.398 -0.998 0.95v8a1 1 0 0 0 1 1z"},1],["path",{"d":"M21.21 15.89A10 10 0 1 1 8 2.83"},0]]);
export default GlassChartPie;
