// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chart-candlestick"
import { createGlassIcon } from '../createGlassIcon';

export const GlassChartCandlestick = /*#__PURE__*/ createGlassIcon("chart-candlestick", [["path",{"d":"M9 5v4"},0],["rect",{"width":"4","height":"6","x":"7","y":"9","rx":"1"},1],["path",{"d":"M9 15v2"},0],["path",{"d":"M17 3v2"},0],["rect",{"width":"4","height":"8","x":"15","y":"5","rx":"1"},1],["path",{"d":"M17 13v3"},0],["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"},0]]);
export default GlassChartCandlestick;
