// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "check-check"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCheckCheck = /*#__PURE__*/ createGlassIcon("check-check", [["path",{"d":"M18 6L7 17l-5 -5"},0],["path",{"d":"M22 10l-7.5 7.5L13 16"},0]]);
export default GlassCheckCheck;
