// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "check-line"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCheckLine = /*#__PURE__*/ createGlassIcon("check-line", [["path",{"d":"M20 4L9 15"},0],["path",{"d":"M21 19L3 19"},0],["path",{"d":"M9 15L4 10"},0]]);
export default GlassCheckLine;
