// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cherry"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCherry = /*#__PURE__*/ createGlassIcon("cherry", [["path",{"d":"M2 17a5 5 0 0 0 10 0c0 -2.76 -2.5 -5 -5 -3c-2.5 -2 -5 0.24 -5 3Z"},1],["path",{"d":"M12 17a5 5 0 0 0 10 0c0 -2.76 -2.5 -5 -5 -3c-2.5 -2 -5 0.24 -5 3Z"},1],["path",{"d":"M7 14c3.22 -2.91 4.29 -8.75 5 -12c1.66 2.38 4.94 9 5 12"},0],["path",{"d":"M22 9c-4.29 0 -7.14 -2.33 -10 -7c5.71 0 10 4.67 10 7Z"},1]]);
export default GlassCherry;
