// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chevrons-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassChevronsLeft = /*#__PURE__*/ createGlassIcon("chevrons-left", [[["M11 17L6 12L11 7",0],["M18 17L13 12L18 7",0]],[],[16.988,8.012,3.77],1]);
export default GlassChevronsLeft;
