// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chevrons-down"
import { createGlassIcon } from '../createGlassIcon';

export const GlassChevronsDown = /*#__PURE__*/ createGlassIcon("chevrons-down", [["path",{"d":"M7 6l5 5l5 -5"},0],["path",{"d":"M7 13l5 5l5 -5"},0]]);
export default GlassChevronsDown;
