// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chevron-right"
import { createGlassIcon } from '../createGlassIcon';

export const GlassChevronRight = /*#__PURE__*/ createGlassIcon("chevron-right", [["path",{"d":"M9 18l6 -6l-6 -6"},0]]);
export default GlassChevronRight;
