// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chevrons-down"
import { createGlassIcon } from '../createGlassIcon';

export const GlassChevronsDown = /*#__PURE__*/ createGlassIcon("chevrons-down", [[["M7 6L12 11L17 6",0],["M7 13L12 18L17 13",0]],[],[15.988,7.012,3.77],1]);
export default GlassChevronsDown;
