// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chevron-first"
import { createGlassIcon } from '../createGlassIcon';

export const GlassChevronFirst = /*#__PURE__*/ createGlassIcon("chevron-first", [[["M17 18L11 12L17 6",0],["M7 6L7 18",0]],[],[15.988,7.012,3.77],1]);
export default GlassChevronFirst;
