// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: Sakani Figma icon set, icon "chrome"
import { createGlassIcon } from '../createGlassIcon';

export const GlassChrome = /*#__PURE__*/ createGlassIcon("chrome", [[["M22 12C22 17.523 17.523 22 12 22C6.477 22 2 17.523 2 12C2 6.477 6.477 2 12 2C17.523 2 22 6.477 22 12Z",1]],[["M12 8C9.791 8 8 9.791 8 12C8 14.209 9.791 16 12 16C14.209 16 16 14.209 16 12C16 9.791 14.209 8 12 8Z",1],["M12 8L21.17 8",1],["M3.95 6.06L8.54 14",1],["M10.88 21.94L15.46 14",1]],[20.4,3.6,4.75],0]);
export default GlassChrome;
