// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cigarette"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCigarette = /*#__PURE__*/ createGlassIcon("cigarette", [["path",{"d":"M17 12H3a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h14"},0],["path",{"d":"M18 8c0 -2.5 -2 -2.5 -2 -5"},0],["path",{"d":"M21 16a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1"},0],["path",{"d":"M22 8c0 -2.5 -2 -2.5 -2 -5"},0],["path",{"d":"M7 12v4"},0]]);
export default GlassCigarette;
