// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-user"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleUser = /*#__PURE__*/ createGlassIcon("circle-user", [["circle",{"cx":"12","cy":"12","r":"10"},1],["circle",{"cx":"12","cy":"10","r":"3"},1],["path",{"d":"M7 20.662V19a2 2 0 0 1 2 -2h6a2 2 0 0 1 2 2v1.662"},0]]);
export default GlassCircleUser;
