// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-pause"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCirclePause = /*#__PURE__*/ createGlassIcon("circle-pause", [[["M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z",1]],[["M10 15L10 9",1],["M14 15L14 9",1]],[20.4,3.6,4.75],0]);
export default GlassCirclePause;
