// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-arrow-out-down-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleArrowOutDownLeft = /*#__PURE__*/ createGlassIcon("circle-arrow-out-down-left", [["path",{"d":"M2 12a10 10 0 1 1 10 10"},0],["path",{"d":"M2 22l10 -10"},0],["path",{"d":"M8 22H2v-6"},0]]);
export default GlassCircleArrowOutDownLeft;
