// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-gauge"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleGauge = /*#__PURE__*/ createGlassIcon("circle-gauge", [["path",{"d":"M15.6 2.7a10 10 0 1 0 5.7 5.7"},0],["circle",{"cx":"12","cy":"12","r":"2"},1],["path",{"d":"M13.4 10.6L19 5"},0]]);
export default GlassCircleGauge;
