// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-user-round"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleUserRound = /*#__PURE__*/ createGlassIcon("circle-user-round", [["path",{"d":"M17.925 20.056a6 6 0 0 0 -11.851 0.001"},0],["circle",{"cx":"12","cy":"11","r":"4"},1],["circle",{"cx":"12","cy":"12","r":"10"},1]]);
export default GlassCircleUserRound;
