// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-chevron-down"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleChevronDown = /*#__PURE__*/ createGlassIcon("circle-chevron-down", [["circle",{"cx":"12","cy":"12","r":"10"},1],["path",{"d":"M16 10l-4 4l-4 -4"},0]]);
export default GlassCircleChevronDown;
