// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-slash"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleSlash = /*#__PURE__*/ createGlassIcon("circle-slash", [["circle",{"cx":"12","cy":"12","r":"10"},1],["line",{"x1":"9","x2":"15","y1":"15","y2":"9"},0]]);
export default GlassCircleSlash;
