// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-equal"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleEqual = /*#__PURE__*/ createGlassIcon("circle-equal", [["circle",{"cx":"12","cy":"12","r":"10"},1],["path",{"d":"M7 10h10"},0],["path",{"d":"M7 14h10"},0]]);
export default GlassCircleEqual;
