// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-check-big"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleCheckBig = /*#__PURE__*/ createGlassIcon("circle-check-big", [["path",{"d":"M21.801 10A10 10 0 1 1 17 3.335"},0],["path",{"d":"M9 11l3 3L22 4"},0]]);
export default GlassCircleCheckBig;
