// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-pause"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCirclePause = /*#__PURE__*/ createGlassIcon("circle-pause", [["circle",{"cx":"12","cy":"12","r":"10"},1],["line",{"x1":"10","x2":"10","y1":"15","y2":"9"},0],["line",{"x1":"14","x2":"14","y1":"15","y2":"9"},0]]);
export default GlassCirclePause;
