// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-slash-2"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleSlash2 = /*#__PURE__*/ createGlassIcon("circle-slash-2", [["circle",{"cx":"12","cy":"12","r":"10"},1],["path",{"d":"M22 2L2 22"},0]]);
export default GlassCircleSlash2;
