// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-arrow-down"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleArrowDown = /*#__PURE__*/ createGlassIcon("circle-arrow-down", [["circle",{"cx":"12","cy":"12","r":"10"},1],["path",{"d":"M12 8v8"},0],["path",{"d":"M8 12l4 4l4 -4"},0]]);
export default GlassCircleArrowDown;
