// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-arrow-out-down-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleArrowOutDownLeft = /*#__PURE__*/ createGlassIcon("circle-arrow-out-down-left", [[["M2 12A10 10 0 1 1 12 22Z",1]],[["M2 22L12 12",0],["M8 22L2 22L2 16",0]],[20.4,3.6,4.75],0]);
export default GlassCircleArrowOutDownLeft;
