// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCircleOff = /*#__PURE__*/ createGlassIcon("circle-off", [[["M19.08 19.08A10 10 0 1 1 4.92 4.92Z",1],["M2 2L22 22",0]],[["M8.35 2.69A10 10 0 0 1 21.3 15.65",0]],[20.4,3.6,4.75],0]);
export default GlassCircleOff;
