// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "clapperboard"
import { createGlassIcon } from '../createGlassIcon';

export const GlassClapperboard = /*#__PURE__*/ createGlassIcon("clapperboard", [[["M3 11L21 11L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19Z",1],["M20.2 6L3 11L2.1 8.6C1.8 7.5 2.4 6.4 3.4 6.1L16.9 2.1C18 1.8 19.1 2.4 19.4 3.4Z",1],["M12.296 3.464L15.316 7.42",0],["M6.18 5.276L9.28 9.175",0]],[],[19.4,3.623,4.75],0]);
export default GlassClapperboard;
