// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "clipboard-type"
import { createGlassIcon } from '../createGlassIcon';

export const GlassClipboardType = /*#__PURE__*/ createGlassIcon("clipboard-type", [[["M16 4L18 4A2 2 0 0 1 20 6L20 20A2 2 0 0 1 18 22L6 22A2 2 0 0 1 4 20L4 6A2 2 0 0 1 6 4L8 4Z",1]],[["M9 2L15 2A1 1 0 0 1 16 3L16 5A1 1 0 0 1 15 6L9 6A1 1 0 0 1 8 5L8 3A1 1 0 0 1 9 2Z",1],["M9 12L9 11L15 11L15 12",1],["M11 17L13 17",1],["M12 11L12 17",1]],[18.4,5.6,4.75],0]);
export default GlassClipboardType;
