// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "clock-arrow-up"
import { createGlassIcon } from '../createGlassIcon';

export const GlassClockArrowUp = /*#__PURE__*/ createGlassIcon("clock-arrow-up", [["path",{"d":"M12 6v6l1.56 0.78"},0],["path",{"d":"M13.227 21.925a10 10 0 1 1 8.767 -9.588"},0],["path",{"d":"M14 18l4 -4l4 4"},0],["path",{"d":"M18 22v-8"},0]]);
export default GlassClockArrowUp;
