// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "clock-1"
import { createGlassIcon } from '../createGlassIcon';

export const GlassClock1 = /*#__PURE__*/ createGlassIcon("clock-1", [["circle",{"cx":"12","cy":"12","r":"10"},1],["path",{"d":"M12 6v6l2 -4"},0]]);
export default GlassClock1;
