// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "clock-3"
import { createGlassIcon } from '../createGlassIcon';

export const GlassClock3 = /*#__PURE__*/ createGlassIcon("clock-3", [["circle",{"cx":"12","cy":"12","r":"10"},1],["path",{"d":"M12 6v6h4"},0]]);
export default GlassClock3;
