// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "clock-plus"
import { createGlassIcon } from '../createGlassIcon';

export const GlassClockPlus = /*#__PURE__*/ createGlassIcon("clock-plus", [[["M21.92 13.267A10 10 0 1 0 13.267 21.92Z",1]],[["M12 6L12 12L15.644 13.822",1],["M16 19L22 19",0],["M19 16L19 22",0]],[20.38,3.603,4.75],0]);
export default GlassClockPlus;
