// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "closed-caption"
import { createGlassIcon } from '../createGlassIcon';

export const GlassClosedCaption = /*#__PURE__*/ createGlassIcon("closed-caption", [["path",{"d":"M10 9.17a3 3 0 1 0 0 5.66"},0],["path",{"d":"M17 9.17a3 3 0 1 0 0 5.66"},0],["rect",{"x":"2","y":"5","width":"20","height":"14","rx":"2"},1]]);
export default GlassClosedCaption;
