// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cloud-sun"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCloudSun = /*#__PURE__*/ createGlassIcon("cloud-sun", [[["M13 22L7 22A5 5 0 1 1 11.9 16L13 16A3 3 0 0 1 13 22Z",1]],[["M12 2L12 4",0],["M4.93 4.93L6.34 6.34",0],["M20 12L22 12",0],["M19.07 4.93L17.66 6.34",0],["M15.947 12.65A4 4 0 0 0 10.022 8.522",0]],[14.676,13.324,4.29],0]);
export default GlassCloudSun;
