// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cloud-lightning"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCloudLightning = /*#__PURE__*/ createGlassIcon("cloud-lightning", [["path",{"d":"M6 16.326A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 0.5 8.973"},0],["path",{"d":"M13 12l-3 5h4l-3 5"},0]]);
export default GlassCloudLightning;
