// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cloud-sun-rain"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCloudSunRain = /*#__PURE__*/ createGlassIcon("cloud-sun-rain", [["path",{"d":"M12 2v2"},0],["path",{"d":"M4.93 4.93l1.41 1.41"},0],["path",{"d":"M20 12h2"},0],["path",{"d":"M19.07 4.93l-1.41 1.41"},0],["path",{"d":"M15.947 12.65a4 4 0 0 0 -5.925 -4.128"},0],["path",{"d":"M3 20a5 5 0 1 1 8.9 -4H13a3 3 0 0 1 2 5.24"},0],["path",{"d":"M11 20v2"},0],["path",{"d":"M7 19v2"},0]]);
export default GlassCloudSunRain;
