// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cloud-rain-wind"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCloudRainWind = /*#__PURE__*/ createGlassIcon("cloud-rain-wind", [["path",{"d":"M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"},0],["path",{"d":"M9.2 22l3 -7"},0],["path",{"d":"M9 13l-3 7"},0],["path",{"d":"M17 13l-3 7"},0]]);
export default GlassCloudRainWind;
