// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cloud-alert"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCloudAlert = /*#__PURE__*/ createGlassIcon("cloud-alert", [["path",{"d":"M12 12v4"},0],["path",{"d":"M12 20h0.01"},0],["path",{"d":"M8.128 16.949A7 7 0 1 1 15.71 8h1.79a1 1 0 0 1 0 9h-1.642"},0]]);
export default GlassCloudAlert;
