// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: Sakani Figma icon set, icon "codepen"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCodepen = /*#__PURE__*/ createGlassIcon("codepen", [[["M22 15.5L22 8.5L12 2L2 8.5L2 15.5L12 22L22 15.5Z",1]],[["M12 2L12 8.5",1],["M22 8.5L12 15.5",1],["M22 15.5L12 8.5",1],["M12 22L12 15.5",1],["M2 15.5L12 8.5",1],["M2 8.5L12 15.5",1]],[20.4,3.6,4.75],0]);
export default GlassCodepen;
