// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cog"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCog = /*#__PURE__*/ createGlassIcon("cog", [["path",{"d":"M11 10.27L7 3.34"},0],["path",{"d":"M11 13.73l-4 6.93"},0],["path",{"d":"M12 22v-2"},0],["path",{"d":"M12 2v2"},0],["path",{"d":"M14 12h8"},0],["path",{"d":"M17 20.66l-1 -1.73"},0],["path",{"d":"M17 3.34l-1 1.73"},0],["path",{"d":"M2 12h2"},0],["path",{"d":"M20.66 17l-1.73 -1"},0],["path",{"d":"M20.66 7l-1.73 1"},0],["path",{"d":"M3.34 17l1.73 -1"},0],["path",{"d":"M3.34 7l1.73 1"},0],["circle",{"cx":"12","cy":"12","r":"2"},1],["circle",{"cx":"12","cy":"12","r":"8"},1]]);
export default GlassCog;
