// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "coins"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCoins = /*#__PURE__*/ createGlassIcon("coins", [["path",{"d":"M13.744 17.736a6 6 0 1 1 -7.48 -7.48"},0],["path",{"d":"M15 6h1v4"},0],["path",{"d":"M6.134 14.768l0.866 -0.5l2 3.464"},0],["circle",{"cx":"16","cy":"8","r":"6"},1]]);
export default GlassCoins;
