// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "columns-4"
import { createGlassIcon } from '../createGlassIcon';

export const GlassColumns4 = /*#__PURE__*/ createGlassIcon("columns-4", [[["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z",1]],[["M7.5 3L7.5 21",1],["M12 3L12 21",1],["M16.5 3L16.5 21",1]],[19.4,4.6,4.75],0]);
export default GlassColumns4;
