// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "compass"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCompass = /*#__PURE__*/ createGlassIcon("compass", [["circle",{"cx":"12","cy":"12","r":"10"},1],["path",{"d":"M16.24 7.76l-1.804 5.411a2 2 0 0 1 -1.265 1.265L7.76 16.24l1.804 -5.411a2 2 0 0 1 1.265 -1.265z"},1]]);
export default GlassCompass;
