// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "construction"
import { createGlassIcon } from '../createGlassIcon';

export const GlassConstruction = /*#__PURE__*/ createGlassIcon("construction", [["rect",{"x":"2","y":"6","width":"20","height":"8","rx":"1"},1],["path",{"d":"M17 14v7"},0],["path",{"d":"M7 14v7"},0],["path",{"d":"M17 3v3"},0],["path",{"d":"M7 3v3"},0],["path",{"d":"M10 14L2.3 6.3"},0],["path",{"d":"M14 6l7.7 7.7"},0],["path",{"d":"M8 6l8 8"},0]]);
export default GlassConstruction;
