// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "construction"
import { createGlassIcon } from '../createGlassIcon';

export const GlassConstruction = /*#__PURE__*/ createGlassIcon("construction", [[["M3 6L21 6A1 1 0 0 1 22 7L22 13A1 1 0 0 1 21 14L3 14A1 1 0 0 1 2 13L2 7A1 1 0 0 1 3 6Z",1]],[["M17 14L17 21",0],["M7 14L7 21",0],["M17 3L17 6",0],["M7 3L7 6",0],["M10 14L2.3 6.3",1],["M14 6L21.7 13.7",1],["M8 6L16 14",1]],[20.4,7.6,4.75],0]);
export default GlassConstruction;
