// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cooking-pot"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCookingPot = /*#__PURE__*/ createGlassIcon("cooking-pot", [["path",{"d":"M2 12h20"},0],["path",{"d":"M20 12v8a2 2 0 0 1 -2 2H6a2 2 0 0 1 -2 -2v-8"},0],["path",{"d":"M4 8l16 -4"},0],["path",{"d":"M8.86 6.78l-0.45 -1.81a2 2 0 0 1 1.45 -2.43l1.94 -0.48a2 2 0 0 1 2.43 1.46l0.45 1.8"},0]]);
export default GlassCookingPot;
