// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "corner-right-down"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCornerRightDown = /*#__PURE__*/ createGlassIcon("corner-right-down", [["path",{"d":"M10 15l5 5l5 -5"},0],["path",{"d":"M4 4h7a4 4 0 0 1 4 4v12"},0]]);
export default GlassCornerRightDown;
