// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "corner-up-right"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCornerUpRight = /*#__PURE__*/ createGlassIcon("corner-up-right", [["path",{"d":"M15 14l5 -5l-5 -5"},0],["path",{"d":"M4 20v-7a4 4 0 0 1 4 -4h12"},0]]);
export default GlassCornerUpRight;
