// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "corner-right-up"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCornerRightUp = /*#__PURE__*/ createGlassIcon("corner-right-up", [["path",{"d":"M10 9l5 -5l5 5"},0],["path",{"d":"M4 20h7a4 4 0 0 0 4 -4V4"},0]]);
export default GlassCornerRightUp;
