// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "crop"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCrop = /*#__PURE__*/ createGlassIcon("crop", [["path",{"d":"M6 2v14a2 2 0 0 0 2 2h14"},0],["path",{"d":"M18 22V8a2 2 0 0 0 -2 -2H2"},0]]);
export default GlassCrop;
