// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cuboid"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCuboid = /*#__PURE__*/ createGlassIcon("cuboid", [["path",{"d":"M10 22v-8"},0],["path",{"d":"M2.336 8.89L10 14l11.715 -7.029"},0],["path",{"d":"M22 14a2 2 0 0 1 -0.971 1.715l-10 6a2 2 0 0 1 -2.138 -0.05l-6 -4A2 2 0 0 1 2 16v-6a2 2 0 0 1 0.971 -1.715l10 -6a2 2 0 0 1 2.138 0.05l6 4A2 2 0 0 1 22 8z"},1]]);
export default GlassCuboid;
