// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cylinder"
import { createGlassIcon } from '../createGlassIcon';

export const GlassCylinder = /*#__PURE__*/ createGlassIcon("cylinder", [["ellipse",{"cx":"12","cy":"5","rx":"9","ry":"3"},1],["path",{"d":"M3 5v14a9 3 0 0 0 18 0V5"},0]]);
export default GlassCylinder;
