// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "decimals-arrow-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassDecimalsArrowLeft = /*#__PURE__*/ createGlassIcon("decimals-arrow-left", [["path",{"d":"M13 21l-3 -3l3 -3"},0],["path",{"d":"M20 18H10"},0],["path",{"d":"M3 11h0.01"},0],["rect",{"x":"6","y":"3","width":"5","height":"8","rx":"2.5"},1]]);
export default GlassDecimalsArrowLeft;
