// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "diamond-plus"
import { createGlassIcon } from '../createGlassIcon';

export const GlassDiamondPlus = /*#__PURE__*/ createGlassIcon("diamond-plus", [[["M2.7 10.3A2.41 2.41 0 0 0 2.7 13.71L10.29 21.3A2.41 2.41 0 0 0 13.7 21.3L21.29 13.71A2.41 2.41 0 0 0 21.29 10.3L13.7 2.71A2.41 2.41 0 0 0 10.29 2.71Z",1]],[["M12 8L12 16",1],["M8 12L16 12",1]],[20.388,3.612,4.75],0]);
export default GlassDiamondPlus;
