// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "diameter"
import { createGlassIcon } from '../createGlassIcon';

export const GlassDiameter = /*#__PURE__*/ createGlassIcon("diameter", [["circle",{"cx":"19","cy":"19","r":"2"},1],["circle",{"cx":"5","cy":"5","r":"2"},1],["path",{"d":"M6.48 3.66a10 10 0 0 1 13.86 13.86"},0],["path",{"d":"M6.41 6.41l11.18 11.18"},0],["path",{"d":"M3.66 6.48a10 10 0 0 0 13.86 13.86"},0]]);
export default GlassDiameter;
