// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "dices"
import { createGlassIcon } from '../createGlassIcon';

export const GlassDices = /*#__PURE__*/ createGlassIcon("dices", [["rect",{"width":"12","height":"12","x":"2","y":"10","rx":"2","ry":"2"},1],["path",{"d":"M17.92 14l3.5 -3.5a2.24 2.24 0 0 0 0 -3l-5 -4.92a2.24 2.24 0 0 0 -3 0L10 6"},0],["path",{"d":"M6 18h0.01"},0],["path",{"d":"M10 14h0.01"},0],["path",{"d":"M15 6h0.01"},0],["path",{"d":"M18 9h0.01"},0]]);
export default GlassDices;
