// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "disc"
import { createGlassIcon } from '../createGlassIcon';

export const GlassDisc = /*#__PURE__*/ createGlassIcon("disc", [["circle",{"cx":"12","cy":"12","r":"10"},1],["circle",{"cx":"12","cy":"12","r":"2"},1]]);
export default GlassDisc;
