// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "disc-3"
import { createGlassIcon } from '../createGlassIcon';

export const GlassDisc3 = /*#__PURE__*/ createGlassIcon("disc-3", [["circle",{"cx":"12","cy":"12","r":"10"},1],["path",{"d":"M6 12c0 -1.7 0.7 -3.2 1.8 -4.2"},0],["circle",{"cx":"12","cy":"12","r":"2"},1],["path",{"d":"M18 12c0 1.7 -0.7 3.2 -1.8 4.2"},0]]);
export default GlassDisc3;
