// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "dna"
import { createGlassIcon } from '../createGlassIcon';

export const GlassDna = /*#__PURE__*/ createGlassIcon("dna", [[["M10 16L11.5 17.5",0],["M14 8L12.5 6.5",0],["M15 2C13.202 3.998 12.482 5.995 12.193 7.993",0],["M16.5 10.5L17.5 11.5",0],["M17 6L14.109 3.109",0],["M2 15C8.667 9 15.333 15 22 9",0],["M20 9L20.891 9.891",0],["M3.109 14.109L4 15",0],["M6.5 12.5L7.5 13.5",0],["M7 18L9.891 20.891",0],["M9 22C10.798 20.002 11.518 18.005 11.807 16.007",0]],[],[20.4,3.6,4.75],1]);
export default GlassDna;
