// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "download"
import { createGlassIcon } from '../createGlassIcon';

export const GlassDownload = /*#__PURE__*/ createGlassIcon("download", [[["M21 15L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 15Z",1]],[["M12 15L12 3",0],["M7 10L12 15L17 10",0]],[19.4,16.6,4.75],0]);
export default GlassDownload;
