// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "drum"
import { createGlassIcon } from '../createGlassIcon';

export const GlassDrum = /*#__PURE__*/ createGlassIcon("drum", [["path",{"d":"M2 2l8 8"},0],["path",{"d":"M22 2l-8 8"},0],["ellipse",{"cx":"12","cy":"9","rx":"10","ry":"5"},1],["path",{"d":"M7 13.4v7.9"},0],["path",{"d":"M12 14v8"},0],["path",{"d":"M17 13.4v7.9"},0],["path",{"d":"M2 9v8a10 5 0 0 0 20 0V9"},0]]);
export default GlassDrum;
