// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ear"
import { createGlassIcon } from '../createGlassIcon';

export const GlassEar = /*#__PURE__*/ createGlassIcon("ear", [[["M6 8.5A6.5 6.5 0 1 1 19 8.5C19 14.5 13 14.5 13 18.5A3.5 3.5 0 1 1 6 18.5Z",1]],[["M15 8.5A2.5 2.5 0 0 0 10 8.5L10 9.5A2 2 0 1 1 10 13.5",1]],[17.4,3.6,4.75],0]);
export default GlassEar;
