// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "eclipse"
import { createGlassIcon } from '../createGlassIcon';

export const GlassEclipse = /*#__PURE__*/ createGlassIcon("eclipse", [["circle",{"cx":"12","cy":"12","r":"10"},1],["path",{"d":"M12 2a7 7 0 1 0 10 10"},0]]);
export default GlassEclipse;
