// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ellipsis-vertical"
import { createGlassIcon } from '../createGlassIcon';

export const GlassEllipsisVertical = /*#__PURE__*/ createGlassIcon("ellipsis-vertical", [[["M11 12A1 1 0 1 0 13 12A1 1 0 1 0 11 12Z",0],["M11 5A1 1 0 1 0 13 5A1 1 0 1 0 11 5Z",0],["M11 19A1 1 0 1 0 13 19A1 1 0 1 0 11 19Z",0]],[],[11.4,5.6,4.75],1]);
export default GlassEllipsisVertical;
