// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ellipsis"
import { createGlassIcon } from '../createGlassIcon';

export const GlassEllipsis = /*#__PURE__*/ createGlassIcon("ellipsis", [[["M11 12A1 1 0 1 0 13 12A1 1 0 1 0 11 12Z",0],["M18 12A1 1 0 1 0 20 12A1 1 0 1 0 18 12Z",0],["M4 12A1 1 0 1 0 6 12A1 1 0 1 0 4 12Z",0]],[],[18.4,12.6,4.75],1]);
export default GlassEllipsis;
