// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "equal-approximately"
import { createGlassIcon } from '../createGlassIcon';

export const GlassEqualApproximately = /*#__PURE__*/ createGlassIcon("equal-approximately", [["path",{"d":"M5 15a6.5 6.5 0 0 1 7 0a6.5 6.5 0 0 0 7 0"},0],["path",{"d":"M5 9a6.5 6.5 0 0 1 7 0a6.5 6.5 0 0 0 7 0"},0]]);
export default GlassEqualApproximately;
