// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "factory"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFactory = /*#__PURE__*/ createGlassIcon("factory", [["path",{"d":"M12 16h0.01"},0],["path",{"d":"M16 16h0.01"},0],["path",{"d":"M3 19a2 2 0 0 0 2 2h14a2 2 0 0 0 2 -2V8.5a0.5 0.5 0 0 0 -0.769 -0.422l-4.462 2.844A0.5 0.5 0 0 1 15 10.5v-2a0.5 0.5 0 0 0 -0.769 -0.422L9.77 10.922A0.5 0.5 0 0 1 9 10.5V5a2 2 0 0 0 -2 -2H5a2 2 0 0 0 -2 2z"},1],["path",{"d":"M8 16h0.01"},0]]);
export default GlassFactory;
