// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-minus-corner" (alias of "file-minus-2")
import { createGlassIcon } from '../createGlassIcon';

export const GlassFileMinus2 = /*#__PURE__*/ createGlassIcon("file-minus-2", [["path",{"d":"M20 14V8a2.4 2.4 0 0 0 -0.706 -1.706l-3.588 -3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0 -2 2v16a2 2 0 0 0 2 2h12"},0],["path",{"d":"M14 2v5a1 1 0 0 0 1 1h5"},0],["path",{"d":"M14 18h6"},0]]);
export default GlassFileMinus2;
