// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-plus-corner" (alias of "file-plus-2")
import { createGlassIcon } from '../createGlassIcon';

export const GlassFilePlus2 = /*#__PURE__*/ createGlassIcon("file-plus-2", [[["M11.35 22L6 22A2 2 0 0 1 4 20L4 4A2 2 0 0 1 6 2L14 2A2.4 2.4 0 0 1 15.706 2.706L19.294 6.294A2.4 2.4 0 0 1 20 8L20 13.35Z",1]],[["M14 2L14 7A1 1 0 0 0 15 8L20 8",1],["M14 19L20 19",0],["M17 16L17 22",0]],[18.4,3.6,4.75],0]);
export default GlassFilePlus2;
