// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: Sakani Figma icon set, icon "file-key-2"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFileKey2 = /*#__PURE__*/ createGlassIcon("file-key-2", [["path",{"d":"M4 22H18C18.5304 22 19.0391 21.7893 19.4142 21.4142C19.7893 21.0391 20 20.5304 20 20V7L15 2H6C5.4696 2 4.9609 2.2107 4.5858 2.5858C4.2107 2.9609 4 3.4696 4 4V10"},0],["path",{"d":"M14 2V6C14 6.5304 14.2107 7.0391 14.5858 7.4142C14.9609 7.7893 15.4696 8 16 8H20"},0],["path",{"d":"M10 10L5.5 14.5"},0],["path",{"d":"M9 11L10 12"},0],["path",{"d":"M6 16C6 17.1046 5.1046 18 4 18C2.8954 18 2 17.1046 2 16C2 14.8954 2.8954 14 4 14C5.1046 14 6 14.8954 6 16Z"},1]]);
export default GlassFileKey2;
