// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-spreadsheet"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFileSpreadsheet = /*#__PURE__*/ createGlassIcon("file-spreadsheet", [["path",{"d":"M6 22a2 2 0 0 1 -2 -2V4a2 2 0 0 1 2 -2h8a2.4 2.4 0 0 1 1.704 0.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1 -2 2z"},1],["path",{"d":"M14 2v5a1 1 0 0 0 1 1h5"},0],["path",{"d":"M8 13h2"},0],["path",{"d":"M14 13h2"},0],["path",{"d":"M8 17h2"},0],["path",{"d":"M14 17h2"},0]]);
export default GlassFileSpreadsheet;
