// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-digit"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFileDigit = /*#__PURE__*/ createGlassIcon("file-digit", [["path",{"d":"M4 12V4a2 2 0 0 1 2 -2h8a2.4 2.4 0 0 1 1.706 0.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1 -2 2"},0],["path",{"d":"M14 2v5a1 1 0 0 0 1 1h5"},0],["path",{"d":"M10 16h2v6"},0],["path",{"d":"M10 22h4"},0],["rect",{"x":"2","y":"16","width":"4","height":"6","rx":"2"},1]]);
export default GlassFileDigit;
