// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-exclamation-point" (alias of "file-warning")
import { createGlassIcon } from '../createGlassIcon';

export const GlassFileWarning = /*#__PURE__*/ createGlassIcon("file-warning", [[["M6 22A2 2 0 0 1 4 20L4 4A2 2 0 0 1 6 2L14 2A2.4 2.4 0 0 1 15.704 2.706L19.292 6.294A2.4 2.4 0 0 1 20 8L20 20A2 2 0 0 1 18 22Z",1]],[["M12 9L12 13",1],["M12 17L12.01 17",1]],[18.4,3.6,4.75],0]);
export default GlassFileWarning;
