// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-box"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFileBox = /*#__PURE__*/ createGlassIcon("file-box", [["path",{"d":"M14 2v5a1 1 0 0 0 1 1h5"},0],["path",{"d":"M14.692 22H18a2 2 0 0 0 2 -2V8a2.4 2.4 0 0 0 -0.706 -1.706l-3.588 -3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0 -2 2v3.804"},0],["path",{"d":"M2.264 13.752L7 16.5l4.737 -2.748"},0],["path",{"d":"M2.995 13.014A2 2 0 0 0 2 14.744v3.516a2 2 0 0 0 0.996 1.73l3 1.74a2 2 0 0 0 2.008 0l3 -1.74A2 2 0 0 0 12 18.26v-3.517a2 2 0 0 0 -0.995 -1.73l-3 -1.742a2 2 0 0 0 -1.892 -0.064z"},1],["path",{"d":"M7 16.5V22"},0]]);
export default GlassFileBox;
