// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-pen-line"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFilePenLine = /*#__PURE__*/ createGlassIcon("file-pen-line", [["path",{"d":"M14.364 13.634a2 2 0 0 0 -0.506 0.854l-0.837 2.87a0.5 0.5 0 0 0 0.62 0.62l2.87 -0.837a2 2 0 0 0 0.854 -0.506l4.013 -4.009a1 1 0 0 0 -3.004 -3.004z"},1],["path",{"d":"M14.487 7.858A1 1 0 0 1 14 7V2"},0],["path",{"d":"M20 19.645V20a2 2 0 0 1 -2 2H6a2 2 0 0 1 -2 -2V4a2 2 0 0 1 2 -2h8a2.4 2.4 0 0 1 1.704 0.706l2.516 2.516"},0],["path",{"d":"M8 18h1"},0]]);
export default GlassFilePenLine;
