// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-signal" (alias of "file-volume-2")
import { createGlassIcon } from '../createGlassIcon';

export const GlassFileVolume2 = /*#__PURE__*/ createGlassIcon("file-volume-2", [["path",{"d":"M6 22a2 2 0 0 1 -2 -2V4a2 2 0 0 1 2 -2h8a2.4 2.4 0 0 1 1.704 0.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1 -2 2z"},1],["path",{"d":"M14 2v5a1 1 0 0 0 1 1h5"},0],["path",{"d":"M8 15h0.01"},0],["path",{"d":"M11.5 13.5a2.5 2.5 0 0 1 0 3"},0],["path",{"d":"M15 12a5 5 0 0 1 0 6"},0]]);
export default GlassFileVolume2;
