// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-image"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFileImage = /*#__PURE__*/ createGlassIcon("file-image", [[["M6 22A2 2 0 0 1 4 20L4 4A2 2 0 0 1 6 2L14 2A2.4 2.4 0 0 1 15.704 2.706L19.292 6.294A2.4 2.4 0 0 1 20 8L20 20A2 2 0 0 1 18 22Z",1]],[["M14 2L14 7A1 1 0 0 0 15 8L20 8",1],["M8 12A2 2 0 1 0 12 12A2 2 0 1 0 8 12Z",1],["M20 17L18.704 15.704A2.41 2.41 0 0 0 15.296 15.704L9 22",1]],[18.4,3.6,4.75],0]);
export default GlassFileImage;
