// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "fish-symbol"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFishSymbol = /*#__PURE__*/ createGlassIcon("fish-symbol", [[["M2 16C2 16 11 1 22 12C11 23 2 8 2 8",0]],[],[20.4,9.584,4.75],1]);
export default GlassFishSymbol;
