// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "flag-triangle-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFlagTriangleLeft = /*#__PURE__*/ createGlassIcon("flag-triangle-left", [["path",{"d":"M18 22V2.8a0.8 0.8 0 0 0 -1.17 -0.71L5.45 7.78a0.8 0.8 0 0 0 0 1.44L18 15.5"},0]]);
export default GlassFlagTriangleLeft;
