// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "flask-conical-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFlaskConicalOff = /*#__PURE__*/ createGlassIcon("flask-conical-off", [[["M20 20A2 2 0 0 1 18 22L6 22A2 2 0 0 1 4.245 19.04L9.472 9.477Z",1]],[["M10 2L10 4.343",0],["M14 2L14 8.343",0],["M2 2L22 22",1],["M6.453 15L15 15",1],["M8.5 2L15.5 2",0]],[18.4,11.077,4.75],0]);
export default GlassFlaskConicalOff;
