// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "flashlight-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFlashlightOff = /*#__PURE__*/ createGlassIcon("flashlight-off", [["path",{"d":"M11.652 6H18"},0],["path",{"d":"M12 13v1"},0],["path",{"d":"M16 16v4a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-8a4 4 0 0 0 -0.8 -2.4l-0.6 -0.8A3 3 0 0 1 6 7V6"},0],["path",{"d":"M2 2l20 20"},0],["path",{"d":"M7.649 2H17a1 1 0 0 1 1 1v4a3 3 0 0 1 -0.6 1.8l-0.6 0.8a4 4 0 0 0 -0.55 1.007"},0]]);
export default GlassFlashlightOff;
