// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "folder-search"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFolderSearch = /*#__PURE__*/ createGlassIcon("folder-search", [[["M10.7 20L4 20A2 2 0 0 1 2 18L2 5A2 2 0 0 1 4 3L7.9 3A2 2 0 0 1 9.59 3.9L10.4 5.1A2 2 0 0 0 12.07 6L20 6A2 2 0 0 1 22 8L22 12.1Z",1]],[["M21 21L19.1 19.1",0],["M14 17A3 3 0 1 0 20 17A3 3 0 1 0 14 17Z",0]],[20.4,4.6,4.75],0]);
export default GlassFolderSearch;
