// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "folder-down"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFolderDown = /*#__PURE__*/ createGlassIcon("folder-down", [[["M20 20A2 2 0 0 0 22 18L22 8A2 2 0 0 0 20 6L12.1 6A2 2 0 0 1 10.41 5.1L9.6 3.9A2 2 0 0 0 7.93 3L4 3A2 2 0 0 0 2 5L2 18A2 2 0 0 0 4 20Z",1]],[["M12 10L12 16",1],["M15 13L12 16L9 13",1]],[20.4,4.6,4.75],0]);
export default GlassFolderDown;
