// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "folder-archive"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFolderArchive = /*#__PURE__*/ createGlassIcon("folder-archive", [[["M20.9 19.8A2 2 0 0 0 22 18L22 8A2 2 0 0 0 20 6L12.1 6A2 2 0 0 1 10.41 5.1L9.6 3.9A2 2 0 0 0 7.93 3L4 3A2 2 0 0 0 2 5L2 18A2 2 0 0 0 4 20L9.1 20Z",1]],[["M13 19A2 2 0 1 0 17 19A2 2 0 1 0 13 19Z",1],["M15 11L15 10",1],["M15 17L15 15",1]],[20.4,4.6,4.75],0]);
export default GlassFolderArchive;
