// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "folder-cog"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFolderCog = /*#__PURE__*/ createGlassIcon("folder-cog", [["path",{"d":"M10.3 20H4a2 2 0 0 1 -2 -2V5a2 2 0 0 1 2 -2h3.98a2 2 0 0 1 1.69 0.9l0.66 1.2A2 2 0 0 0 12 6h8a2 2 0 0 1 2 2v3.3"},0],["path",{"d":"M14.305 19.53l0.923 -0.382"},0],["path",{"d":"M15.228 16.852l-0.923 -0.383"},0],["path",{"d":"M16.852 15.228l-0.383 -0.923"},0],["path",{"d":"M16.852 20.772l-0.383 0.924"},0],["path",{"d":"M19.148 15.228l0.383 -0.923"},0],["path",{"d":"M19.53 21.696l-0.382 -0.924"},0],["path",{"d":"M20.772 16.852l0.924 -0.383"},0],["path",{"d":"M20.772 19.148l0.924 0.383"},0],["circle",{"cx":"18","cy":"18","r":"3"},1]]);
export default GlassFolderCog;
