// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "folder-kanban"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFolderKanban = /*#__PURE__*/ createGlassIcon("folder-kanban", [[["M4 20L20 20A2 2 0 0 0 22 18L22 8A2 2 0 0 0 20 6L12.07 6A2 2 0 0 1 10.41 5.1L9.59 3.9A2 2 0 0 0 7.93 3L4 3A2 2 0 0 0 2 5L2 18C2 19.1 2.9 20 4 20Z",1]],[["M8 10L8 14",1],["M12 10L12 12",1],["M16 10L16 16",1]],[20.4,4.6,4.75],0]);
export default GlassFolderKanban;
