// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "folder-symlink"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFolderSymlink = /*#__PURE__*/ createGlassIcon("folder-symlink", [["path",{"d":"M2 9.35V5a2 2 0 0 1 2 -2h3.9a2 2 0 0 1 1.69 0.9l0.81 1.2a2 2 0 0 0 1.67 0.9H20a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2H4a2 2 0 0 1 -2 -2v-3a2 2 0 0 1 2 -2h7"},0],["path",{"d":"M8 16l3 -3l-3 -3"},0]]);
export default GlassFolderSymlink;
