// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "folder-output"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFolderOutput = /*#__PURE__*/ createGlassIcon("folder-output", [[["M2 7.5L2 5A2 2 0 0 1 4 3L7.9 3A2 2 0 0 1 9.59 3.9L10.4 5.1A2 2 0 0 0 12.07 6L20 6A2 2 0 0 1 22 8L22 18A2 2 0 0 1 20 20L4 20A2 2 0 0 1 2 18.5Z",1]],[["M2 13L12 13",1],["M5 10L2 13L5 16",1]],[20.4,4.6,4.75],0]);
export default GlassFolderOutput;
