// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "frame"
import { createGlassIcon } from '../createGlassIcon';

export const GlassFrame = /*#__PURE__*/ createGlassIcon("frame", [["line",{"x1":"22","x2":"2","y1":"6","y2":"6"},0],["line",{"x1":"22","x2":"2","y1":"18","y2":"18"},0],["line",{"x1":"6","x2":"6","y1":"2","y2":"22"},0],["line",{"x1":"18","x2":"18","y1":"2","y2":"22"},0]]);
export default GlassFrame;
