// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "gallery-vertical-end"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGalleryVerticalEnd = /*#__PURE__*/ createGlassIcon("gallery-vertical-end", [[["M5 10L19 10A2 2 0 0 1 21 12L21 20A2 2 0 0 1 19 22L5 22A2 2 0 0 1 3 20L3 12A2 2 0 0 1 5 10Z",1]],[["M7 2L17 2",0],["M5 6L19 6",0]],[19.4,11.6,4.75],0]);
export default GlassGalleryVerticalEnd;
