// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "gallery-thumbnails"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGalleryThumbnails = /*#__PURE__*/ createGlassIcon("gallery-thumbnails", [["rect",{"width":"18","height":"14","x":"3","y":"3","rx":"2"},1],["path",{"d":"M4 21h1"},0],["path",{"d":"M9 21h1"},0],["path",{"d":"M14 21h1"},0],["path",{"d":"M19 21h1"},0]]);
export default GlassGalleryThumbnails;
