// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "gavel"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGavel = /*#__PURE__*/ createGlassIcon("gavel", [["path",{"d":"M14 13l-8.381 8.38a1 1 0 0 1 -3.001 -3l8.384 -8.381"},0],["path",{"d":"M16 16l6 -6"},0],["path",{"d":"M21.5 10.5l-8 -8"},0],["path",{"d":"M8 8l6 -6"},0],["path",{"d":"M8.5 7.5l8 8"},0]]);
export default GlassGavel;
