// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "git-commit-horizontal"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGitCommitHorizontal = /*#__PURE__*/ createGlassIcon("git-commit-horizontal", [["circle",{"cx":"12","cy":"12","r":"3"},1],["line",{"x1":"3","x2":"9","y1":"12","y2":"12"},0],["line",{"x1":"15","x2":"21","y1":"12","y2":"12"},0]]);
export default GlassGitCommitHorizontal;
