// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "git-pull-request-draft"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGitPullRequestDraft = /*#__PURE__*/ createGlassIcon("git-pull-request-draft", [["circle",{"cx":"18","cy":"18","r":"3"},1],["circle",{"cx":"6","cy":"6","r":"3"},1],["path",{"d":"M18 6V5"},0],["path",{"d":"M18 11v-1"},0],["line",{"x1":"6","x2":"6","y1":"9","y2":"21"},0]]);
export default GlassGitPullRequestDraft;
