// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "git-commit-vertical"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGitCommitVertical = /*#__PURE__*/ createGlassIcon("git-commit-vertical", [["path",{"d":"M12 3v6"},0],["circle",{"cx":"12","cy":"12","r":"3"},1],["path",{"d":"M12 15v6"},0]]);
export default GlassGitCommitVertical;
