// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "git-fork"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGitFork = /*#__PURE__*/ createGlassIcon("git-fork", [["circle",{"cx":"12","cy":"18","r":"3"},1],["circle",{"cx":"6","cy":"6","r":"3"},1],["circle",{"cx":"18","cy":"6","r":"3"},1],["path",{"d":"M18 9v2c0 0.6 -0.4 1 -1 1H7c-0.6 0 -1 -0.4 -1 -1V9"},0],["path",{"d":"M12 12v3"},0]]);
export default GlassGitFork;
