// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "globe"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGlobe = /*#__PURE__*/ createGlassIcon("globe", [["circle",{"cx":"12","cy":"12","r":"10"},1],["path",{"d":"M12 2a14.5 14.5 0 0 0 0 20a14.5 14.5 0 0 0 0 -20"},1],["path",{"d":"M2 12h20"},0]]);
export default GlassGlobe;
