// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "globe"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGlobe = /*#__PURE__*/ createGlassIcon("globe", [[["M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z",1]],[["M12 2A14.5 14.5 0 0 0 12 22A14.5 14.5 0 0 0 12 2",1],["M2 12L22 12",1]],[20.4,3.6,4.75],0]);
export default GlassGlobe;
