// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "globe-lock"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGlobeLock = /*#__PURE__*/ createGlassIcon("globe-lock", [["path",{"d":"M15.686 15A14.5 14.5 0 0 1 12 22a14.5 14.5 0 0 1 0 -20a10 10 0 1 0 9.542 13"},0],["path",{"d":"M2 12h8.5"},0],["path",{"d":"M20 6V4a2 2 0 1 0 -4 0v2"},0],["rect",{"width":"8","height":"5","x":"14","y":"6","rx":"1"},1]]);
export default GlassGlobeLock;
