// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "gpu"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGpu = /*#__PURE__*/ createGlassIcon("gpu", [[["M2 17L20 17A2 2 0 0 0 22 15L22 7A2 2 0 0 0 20 5L2 5Z",1],["M2 21L2 3",0]],[["M7 17L7 20A1 1 0 0 0 8 21L13 21A1 1 0 0 0 14 20L14 17",0],["M14 11A2 2 0 1 0 18 11A2 2 0 1 0 14 11Z",1],["M6 11A2 2 0 1 0 10 11A2 2 0 1 0 6 11Z",1]],[20.4,4.6,4.75],0]);
export default GlassGpu;
