// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "gpu"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGpu = /*#__PURE__*/ createGlassIcon("gpu", [["path",{"d":"M2 17h18a2 2 0 0 0 2 -2V7a2 2 0 0 0 -2 -2H2"},0],["path",{"d":"M2 21V3"},0],["path",{"d":"M7 17v3a1 1 0 0 0 1 1h5a1 1 0 0 0 1 -1v-3"},0],["circle",{"cx":"16","cy":"11","r":"2"},1],["circle",{"cx":"8","cy":"11","r":"2"},1]]);
export default GlassGpu;
