// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "grid-2x2-check"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGrid2x2Check = /*#__PURE__*/ createGlassIcon("grid-2x2-check", [["path",{"d":"M12 3v17a1 1 0 0 1 -1 1H5a2 2 0 0 1 -2 -2V5a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v6a1 1 0 0 1 -1 1H3"},0],["path",{"d":"M16 19l2 2l4 -4"},0]]);
export default GlassGrid2x2Check;
