// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "grid-3x2"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGrid3x2 = /*#__PURE__*/ createGlassIcon("grid-3x2", [["path",{"d":"M15 3v18"},0],["path",{"d":"M3 12h18"},0],["path",{"d":"M9 3v18"},0],["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2"},1]]);
export default GlassGrid3x2;
