// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "grid-2x2-x"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGrid2x2X = /*#__PURE__*/ createGlassIcon("grid-2x2-x", [[["M12 3L12 20A1 1 0 0 1 11 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3L19 3A2 2 0 0 1 21 5L21 11A1 1 0 0 1 20 12L3 12",0],["M16.5 16.5L21.5 21.5",0],["M16.5 21.5L21.5 16.5",0]],[],[19.9,4.6,4.75],1]);
export default GlassGrid2x2X;
