// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "grid-3x3"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGrid3x3 = /*#__PURE__*/ createGlassIcon("grid-3x3", [[["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z",1]],[["M3 9L21 9",1],["M3 15L21 15",1],["M9 3L9 21",1],["M15 3L15 21",1]],[19.4,4.6,4.75],0]);
export default GlassGrid3x3;
