// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "guitar"
import { createGlassIcon } from '../createGlassIcon';

export const GlassGuitar = /*#__PURE__*/ createGlassIcon("guitar", [[["M8.23 9.85A3 3 0 0 1 11 8A5 5 0 0 1 16 13A3 3 0 0 1 14.15 15.77L13.23 16.15A2 2 0 0 0 12 18A4 4 0 0 1 8 22A6 6 0 0 1 2 16A4 4 0 0 1 6 12A2 2 0 0 0 7.85 10.77Z",1]],[["M11.9 12.1L16.414 7.586",1],["M20.1 2.3A1 1 0 0 0 18.7 2.3L17.586 3.414A2 2 0 0 0 17 4.828L17 6.172A2 2 0 0 1 16.414 7.586A2 2 0 0 1 17.828 7L19.172 7A2 2 0 0 0 20.586 6.414L21.7 5.3A1 1 0 0 0 21.7 3.9Z",0],["M6 16L8 18",1]],[14.676,9.324,4.29],0]);
export default GlassGuitar;
