// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "hammer"
import { createGlassIcon } from '../createGlassIcon';

export const GlassHammer = /*#__PURE__*/ createGlassIcon("hammer", [["path",{"d":"M15 12l-9.373 9.373a1 1 0 0 1 -3.001 -3L12 9"},0],["path",{"d":"M18 15l4 -4"},0],["path",{"d":"M21.5 11.5l-1.914 -1.914A2 2 0 0 1 19 8.172v-0.344a2 2 0 0 0 -0.586 -1.414l-1.657 -1.657A6 6 0 0 0 12.516 3H9l1.243 1.243A6 6 0 0 1 12 8.485V10l2 2h1.172a2 2 0 0 1 1.414 0.586L18.5 14.5"},0]]);
export default GlassHammer;
