// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "hand-heart"
import { createGlassIcon } from '../createGlassIcon';

export const GlassHandHeart = /*#__PURE__*/ createGlassIcon("hand-heart", [["path",{"d":"M11 14h2a2 2 0 0 0 0 -4h-3c-0.6 0 -1.1 0.2 -1.4 0.6L3 16"},0],["path",{"d":"M14.45 13.39l5.05 -4.694C20.196 8 21 6.85 21 5.75a2.75 2.75 0 0 0 -4.797 -1.837a0.276 0.276 0 0 1 -0.406 0A2.75 2.75 0 0 0 11 5.75c0 1.2 0.802 2.248 1.5 2.946L16 11.95"},0],["path",{"d":"M2 15l6 6"},0],["path",{"d":"M7 20l1.6 -1.4c0.3 -0.4 0.8 -0.6 1.4 -0.6h4c1.1 0 2.1 -0.4 2.8 -1.2l4.6 -4.4a1 1 0 0 0 -2.75 -2.91"},0]]);
export default GlassHandHeart;
