// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "haze"
import { createGlassIcon } from '../createGlassIcon';

export const GlassHaze = /*#__PURE__*/ createGlassIcon("haze", [["path",{"d":"M5.2 6.2l1.4 1.4"},0],["path",{"d":"M2 13h2"},0],["path",{"d":"M20 13h2"},0],["path",{"d":"M17.4 7.6l1.4 -1.4"},0],["path",{"d":"M22 17H2"},0],["path",{"d":"M22 21H2"},0],["path",{"d":"M16 13a4 4 0 0 0 -8 0"},0],["path",{"d":"M12 5V2.5"},0]]);
export default GlassHaze;
