// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "hdmi-port"
import { createGlassIcon } from '../createGlassIcon';

export const GlassHdmiPort = /*#__PURE__*/ createGlassIcon("hdmi-port", [["path",{"d":"M22 9a1 1 0 0 0 -1 -1H3a1 1 0 0 0 -1 1v4a1 1 0 0 0 1 1h0.5a2 2 0 0 1 1.6 0.8l0.3 0.4A2 2 0 0 0 7 16h10a2 2 0 0 0 1.6 -0.8l0.3 -0.4a2 2 0 0 1 1.6 -0.8h0.5a1 1 0 0 0 1 -1z"},1],["path",{"d":"M8 12h8"},0]]);
export default GlassHdmiPort;
