// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "heading-1"
import { createGlassIcon } from '../createGlassIcon';

export const GlassHeading1 = /*#__PURE__*/ createGlassIcon("heading-1", [[["M17 12L20 10L20 18Z",1]],[["M4 12L12 12",0],["M4 18L4 6",0],["M12 18L12 6",0]],[19.45,10.55,3],0]);
export default GlassHeading1;
