// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "headphone-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassHeadphoneOff = /*#__PURE__*/ createGlassIcon("headphone-off", [["path",{"d":"M21 14h-1.343"},0],["path",{"d":"M9.128 3.47A9 9 0 0 1 21 12v3.343"},0],["path",{"d":"M2 2l20 20"},0],["path",{"d":"M20.414 20.414A2 2 0 0 1 19 21h-1a2 2 0 0 1 -2 -2v-3"},0],["path",{"d":"M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2H5a2 2 0 0 1 -2 -2v-7a9 9 0 0 1 2.636 -6.364"},0]]);
export default GlassHeadphoneOff;
