// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "heart-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassHeartOff = /*#__PURE__*/ createGlassIcon("heart-off", [[["M16.967 16.967L13.508 20.313A2 2 0 0 1 10.508 20.332L5 15C3.5 13.5 2 11.8 2 9.5A5.5 5.5 0 0 1 4.747 4.739Z",1],["M10.5 4.893A5.5 5.5 0 0 1 11.591 5.824A0.56 0.56 0 0 0 12.409 5.824A5.49 5.49 0 0 1 22 9.5C22 11.372 20.998 12.856 19.813 14.155Z",1],["M2 2L22 22",0]],[],[20.4,3.6,4.75],0]);
export default GlassHeartOff;
