// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "heart-crack"
import { createGlassIcon } from '../createGlassIcon';

export const GlassHeartCrack = /*#__PURE__*/ createGlassIcon("heart-crack", [["path",{"d":"M12.409 5.824c-0.702 0.792 -1.15 1.496 -1.415 2.166l2.153 2.156a0.5 0.5 0 0 1 0 0.707l-2.293 2.293a0.5 0.5 0 0 0 0 0.707L12 15"},0],["path",{"d":"M13.508 20.313a2 2 0 0 1 -3 0.019L5 15c-1.5 -1.5 -3 -3.2 -3 -5.5a5.5 5.5 0 0 1 9.591 -3.677a0.6 0.6 0 0 0 0.818 0.001A5.5 5.5 0 0 1 22 9.5c0 2.29 -1.5 4 -3 5.5z"},1]]);
export default GlassHeartCrack;
