// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "heater"
import { createGlassIcon } from '../createGlassIcon';

export const GlassHeater = /*#__PURE__*/ createGlassIcon("heater", [["path",{"d":"M11 8c2 -3 -2 -3 0 -6"},0],["path",{"d":"M15.5 8c2 -3 -2 -3 0 -6"},0],["path",{"d":"M6 10h0.01"},0],["path",{"d":"M6 14h0.01"},0],["path",{"d":"M10 16v-4"},0],["path",{"d":"M14 16v-4"},0],["path",{"d":"M18 16v-4"},0],["path",{"d":"M20 6a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2H4a2 2 0 0 1 -2 -2V8a2 2 0 0 1 2 -2h3"},0],["path",{"d":"M5 20v2"},0],["path",{"d":"M19 20v2"},0]]);
export default GlassHeater;
