// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "hourglass"
import { createGlassIcon } from '../createGlassIcon';

export const GlassHourglass = /*#__PURE__*/ createGlassIcon("hourglass", [["path",{"d":"M5 22h14"},0],["path",{"d":"M5 2h14"},0],["path",{"d":"M17 22v-4.172a2 2 0 0 0 -0.586 -1.414L12 12l-4.414 4.414A2 2 0 0 0 7 17.828V22"},0],["path",{"d":"M7 2v4.172a2 2 0 0 0 0.586 1.414L12 12l4.414 -4.414A2 2 0 0 0 17 6.172V2"},0]]);
export default GlassHourglass;
