// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "house-wifi"
import { createGlassIcon } from '../createGlassIcon';

export const GlassHouseWifi = /*#__PURE__*/ createGlassIcon("house-wifi", [["path",{"d":"M9.5 13.866a4 4 0 0 1 5 0.01"},0],["path",{"d":"M12 17h0.01"},0],["path",{"d":"M3 10a2 2 0 0 1 0.709 -1.528l7 -6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1 -2 2H5a2 2 0 0 1 -2 -2z"},1],["path",{"d":"M7 10.754a8 8 0 0 1 10 0"},0]]);
export default GlassHouseWifi;
