// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ice-cream-bowl"
import { createGlassIcon } from '../createGlassIcon';

export const GlassIceCreamBowl = /*#__PURE__*/ createGlassIcon("ice-cream-bowl", [["path",{"d":"M12 17c5 0 8 -2.69 8 -6H4c0 3.31 3 6 8 6"},1],["path",{"d":"M8 21h8"},0],["path",{"d":"M12 18v3"},0],["path",{"d":"M5.14 11a3.5 3.5 0 1 1 6.71 0"},0],["path",{"d":"M12.14 11a3.5 3.5 0 1 1 6.71 0"},0],["path",{"d":"M15.5 6.5a3.5 3.5 0 1 0 -7 0"},0]]);
export default GlassIceCreamBowl;
