// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "id-card-lanyard"
import { createGlassIcon } from '../createGlassIcon';

export const GlassIdCardLanyard = /*#__PURE__*/ createGlassIcon("id-card-lanyard", [[["M15 2L14 4L17 4A2 2 0 0 1 19 6L19 20A2 2 0 0 1 17 22L7 22A2 2 0 0 1 5 20L5 6A2 2 0 0 1 7 4L10 4Z",1]],[["M13.5 8L10.5 8",1],["M16.899 22A5 5 0 0 0 7.1 22",1],["M9 2L12 8",1],["M9 15A3 3 0 1 0 15 15A3 3 0 1 0 9 15Z",1]],[17.4,3.6,4.75],0]);
export default GlassIdCardLanyard;
