// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "image-up"
import { createGlassIcon } from '../createGlassIcon';

export const GlassImageUp = /*#__PURE__*/ createGlassIcon("image-up", [["path",{"d":"M10.3 21H5a2 2 0 0 1 -2 -2V5a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10l-3.1 -3.1a2 2 0 0 0 -2.814 0.014L6 21"},0],["path",{"d":"M14 19.5l3 -3l3 3"},0],["path",{"d":"M17 22v-5.5"},0],["circle",{"cx":"9","cy":"9","r":"2"},1]]);
export default GlassImageUp;
