// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "image-plus"
import { createGlassIcon } from '../createGlassIcon';

export const GlassImagePlus = /*#__PURE__*/ createGlassIcon("image-plus", [["path",{"d":"M16 5h6"},0],["path",{"d":"M19 2v6"},0],["path",{"d":"M21 11.5V19a2 2 0 0 1 -2 2H5a2 2 0 0 1 -2 -2V5a2 2 0 0 1 2 -2h7.5"},0],["path",{"d":"M21 15l-3.086 -3.086a2 2 0 0 0 -2.828 0L6 21"},0],["circle",{"cx":"9","cy":"9","r":"2"},1]]);
export default GlassImagePlus;
