// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "image-plus"
import { createGlassIcon } from '../createGlassIcon';

export const GlassImagePlus = /*#__PURE__*/ createGlassIcon("image-plus", [[["M21 11.5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3L12.5 3Z",1]],[["M16 5L22 5",0],["M19 2L19 8",0],["M21 15L17.914 11.914A2 2 0 0 0 15.086 11.914L6 21",1],["M7 9A2 2 0 1 0 11 9A2 2 0 1 0 7 9Z",1]],[19.4,4.6,4.75],0]);
export default GlassImagePlus;
