// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "image-upscale"
import { createGlassIcon } from '../createGlassIcon';

export const GlassImageUpscale = /*#__PURE__*/ createGlassIcon("image-upscale", [[["M4 11L12 11A1 1 0 0 1 13 12L13 20A1 1 0 0 1 12 21L4 21A1 1 0 0 1 3 20L3 12A1 1 0 0 1 4 11Z",1]],[["M16 3L21 3L21 8",0],["M17 21L19 21A2 2 0 0 0 21 19",0],["M21 12L21 15",0],["M21 3L16 8",0],["M3 7L3 5A2 2 0 0 1 5 3",0],["M5 21L9.144 16.856A1.21 1.21 0 0 1 10.856 16.856L13 19",1],["M9 3L12 3",0]],[12.3,11.7,3.25],0]);
export default GlassImageUpscale;
