// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "image-play"
import { createGlassIcon } from '../createGlassIcon';

export const GlassImagePlay = /*#__PURE__*/ createGlassIcon("image-play", [[["M21 12.17L21 5A2 2 0 0 0 19 3L5 3A2 2 0 0 0 3 5L3 19A2 2 0 0 0 5 21L11 21Z",1]],[["M15 15.003A1 1 0 0 1 16.517 14.144L21.514 17.141A1 1 0 0 1 21.514 18.859L16.517 21.856A1 1 0 0 1 15 20.996Z",0],["M6 21L11 16",1],["M7 9A2 2 0 1 0 11 9A2 2 0 1 0 7 9Z",1]],[19.4,4.6,4.75],0]);
export default GlassImagePlay;
