// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "import"
import { createGlassIcon } from '../createGlassIcon';

export const GlassImport = /*#__PURE__*/ createGlassIcon("import", [[["M8 5L4 5A2 2 0 0 0 2 7L2 17A2 2 0 0 0 4 19L20 19A2 2 0 0 0 22 17L22 7A2 2 0 0 0 20 5L16 5Z",1]],[["M12 3L12 15",1],["M8 11L12 15L16 11",1]],[20.4,6.6,4.75],0]);
export default GlassImport;
