// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "indian-rupee"
import { createGlassIcon } from '../createGlassIcon';

export const GlassIndianRupee = /*#__PURE__*/ createGlassIcon("indian-rupee", [["path",{"d":"M6 3h12"},0],["path",{"d":"M6 8h12"},0],["path",{"d":"M6 13l8.5 8"},0],["path",{"d":"M6 13h3"},0],["path",{"d":"M9 13c6.667 0 6.667 -10 0 -10"},0]]);
export default GlassIndianRupee;
