// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "info"
import { createGlassIcon } from '../createGlassIcon';

export const GlassInfo = /*#__PURE__*/ createGlassIcon("info", [[["M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z",1]],[["M12 16L12 12",1],["M12 8L12.01 8",1]],[20.4,3.6,4.75],0]);
export default GlassInfo;
