// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "inspection-panel"
import { createGlassIcon } from '../createGlassIcon';

export const GlassInspectionPanel = /*#__PURE__*/ createGlassIcon("inspection-panel", [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1],["path",{"d":"M7 7h0.01"},0],["path",{"d":"M17 7h0.01"},0],["path",{"d":"M7 17h0.01"},0],["path",{"d":"M17 17h0.01"},0]]);
export default GlassInspectionPanel;
