// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "key"
import { createGlassIcon } from '../createGlassIcon';

export const GlassKey = /*#__PURE__*/ createGlassIcon("key", [[["M10 7.5A5.5 5.5 0 1 0 21 7.5A5.5 5.5 0 1 0 10 7.5Z",1]],[["M2 21L11.6 11.4",0],["M7.5 15.5L9.8 17.8A1 1 0 0 1 9.8 19.2L7.7 21.3A1 1 0 0 1 6.3 21.3L4 19",0]],[20.144,2.856,3.51],0]);
export default GlassKey;
