// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "lamp-floor"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLampFloor = /*#__PURE__*/ createGlassIcon("lamp-floor", [["path",{"d":"M12 10v12"},0],["path",{"d":"M17.929 7.629A1 1 0 0 1 17 9H7a1 1 0 0 1 -0.928 -1.371l2 -5A1 1 0 0 1 9 2h6a1 1 0 0 1 0.928 0.629z"},1],["path",{"d":"M9 22h6"},0]]);
export default GlassLampFloor;
