// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "lamp-wall-up"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLampWallUp = /*#__PURE__*/ createGlassIcon("lamp-wall-up", [[["M19.929 9.629A1 1 0 0 1 19 11L9 11A1 1 0 0 1 8.072 9.629L10.072 4.629A1 1 0 0 1 11 4L17 4A1 1 0 0 1 17.928 4.629Z",1],["M6 15A2 2 0 0 1 8 17L8 19A2 2 0 0 1 6 21L5 21A1 1 0 0 1 4 20L4 16A1 1 0 0 1 5 15Z",1]],[["M8 18L12 18A2 2 0 0 0 14 16L14 11",0]],[18.4,5.6,4.75],0]);
export default GlassLampWallUp;
