// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "lamp-wall-up"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLampWallUp = /*#__PURE__*/ createGlassIcon("lamp-wall-up", [["path",{"d":"M19.929 9.629A1 1 0 0 1 19 11H9a1 1 0 0 1 -0.928 -1.371l2 -5A1 1 0 0 1 11 4h6a1 1 0 0 1 0.928 0.629z"},1],["path",{"d":"M6 15a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2H5a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1z"},1],["path",{"d":"M8 18h4a2 2 0 0 0 2 -2v-5"},0]]);
export default GlassLampWallUp;
