// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "lamp-ceiling"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLampCeiling = /*#__PURE__*/ createGlassIcon("lamp-ceiling", [["path",{"d":"M12 2v5"},0],["path",{"d":"M14.829 15.998a3 3 0 1 1 -5.658 0"},0],["path",{"d":"M20.92 14.606A1 1 0 0 1 20 16H4a1 1 0 0 1 -0.92 -1.394l3 -7A1 1 0 0 1 7 7h10a1 1 0 0 1 0.92 0.606z"},1]]);
export default GlassLampCeiling;
