// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "landmark"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLandmark = /*#__PURE__*/ createGlassIcon("landmark", [["path",{"d":"M10 18v-7"},0],["path",{"d":"M11.119 2.205a2 2 0 0 1 1.762 0l7.84 3.846A0.5 0.5 0 0 1 20.5 7h-17a0.5 0.5 0 0 1 -0.22 -0.949z"},1],["path",{"d":"M14 18v-7"},0],["path",{"d":"M18 18v-7"},0],["path",{"d":"M3 22h18"},0],["path",{"d":"M6 18v-7"},0]]);
export default GlassLandmark;
