// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "layout-dashboard"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLayoutDashboard = /*#__PURE__*/ createGlassIcon("layout-dashboard", [["rect",{"width":"7","height":"9","x":"3","y":"3","rx":"1"},1],["rect",{"width":"7","height":"5","x":"14","y":"3","rx":"1"},1],["rect",{"width":"7","height":"9","x":"14","y":"12","rx":"1"},1],["rect",{"width":"7","height":"5","x":"3","y":"16","rx":"1"},1]]);
export default GlassLayoutDashboard;
