// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "layout-grid"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLayoutGrid = /*#__PURE__*/ createGlassIcon("layout-grid", [["rect",{"width":"7","height":"7","x":"3","y":"3","rx":"1"},1],["rect",{"width":"7","height":"7","x":"14","y":"3","rx":"1"},1],["rect",{"width":"7","height":"7","x":"14","y":"14","rx":"1"},1],["rect",{"width":"7","height":"7","x":"3","y":"14","rx":"1"},1]]);
export default GlassLayoutGrid;
