// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "layout-list"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLayoutList = /*#__PURE__*/ createGlassIcon("layout-list", [["rect",{"width":"7","height":"7","x":"3","y":"3","rx":"1"},1],["rect",{"width":"7","height":"7","x":"3","y":"14","rx":"1"},1],["path",{"d":"M14 4h7"},0],["path",{"d":"M14 9h7"},0],["path",{"d":"M14 15h7"},0],["path",{"d":"M14 20h7"},0]]);
export default GlassLayoutList;
