// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "life-buoy"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLifeBuoy = /*#__PURE__*/ createGlassIcon("life-buoy", [[["M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z",1]],[["M4.93 4.93L9.17 9.17",1],["M14.83 9.17L19.07 4.93",1],["M14.83 14.83L19.07 19.07",1],["M9.17 14.83L4.93 19.07",1],["M8 12A4 4 0 1 0 16 12A4 4 0 1 0 8 12Z",1]],[20.4,3.6,4.75],0]);
export default GlassLifeBuoy;
