// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "life-buoy"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLifeBuoy = /*#__PURE__*/ createGlassIcon("life-buoy", [["circle",{"cx":"12","cy":"12","r":"10"},1],["path",{"d":"M4.93 4.93l4.24 4.24"},0],["path",{"d":"M14.83 9.17l4.24 -4.24"},0],["path",{"d":"M14.83 14.83l4.24 4.24"},0],["path",{"d":"M9.17 14.83l-4.24 4.24"},0],["circle",{"cx":"12","cy":"12","r":"4"},1]]);
export default GlassLifeBuoy;
