// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ligature"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLigature = /*#__PURE__*/ createGlassIcon("ligature", [["path",{"d":"M14 12h2v8"},0],["path",{"d":"M14 20h4"},0],["path",{"d":"M6 12h4"},0],["path",{"d":"M6 20h4"},0],["path",{"d":"M8 20V8a4 4 0 0 1 7.464 -2"},0]]);
export default GlassLigature;
