// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "link"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLink = /*#__PURE__*/ createGlassIcon("link", [["path",{"d":"M10 13a5 5 0 0 0 7.54 0.54l3 -3a5 5 0 0 0 -7.07 -7.07l-1.72 1.71"},0],["path",{"d":"M14 11a5 5 0 0 0 -7.54 -0.54l-3 3a5 5 0 0 0 7.07 7.07l1.71 -1.71"},0]]);
export default GlassLink;
