// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: Sakani Figma icon set, icon "linkedin"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLinkedin = /*#__PURE__*/ createGlassIcon("linkedin", [[["M16 8C17.591 8 19.117 8.632 20.243 9.757C21.368 10.883 22 12.409 22 14L22 21L18 21L18 14C18 13.47 17.789 12.961 17.414 12.586C17.039 12.211 16.53 12 16 12C15.47 12 14.961 12.211 14.586 12.586C14.211 12.961 14 13.47 14 14L14 21L10 21L10 14C10 12.409 10.632 10.883 11.757 9.757C12.883 8.632 14.409 8 16 8Z",1],["M6 9L2 9L2 21L6 21L6 9Z",1]],[["M4 6C5.105 6 6 5.105 6 4C6 2.895 5.105 2 4 2C2.895 2 2 2.895 2 4C2 5.105 2.895 6 4 6Z",0]],[20.4,9.6,4.75],0]);
export default GlassLinkedin;
