// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "list-collapse"
import { createGlassIcon } from '../createGlassIcon';

export const GlassListCollapse = /*#__PURE__*/ createGlassIcon("list-collapse", [["path",{"d":"M10 5h11"},0],["path",{"d":"M10 12h11"},0],["path",{"d":"M10 19h11"},0],["path",{"d":"M3 10l3 -3l-3 -3"},0],["path",{"d":"M3 20l3 -3l-3 -3"},0]]);
export default GlassListCollapse;
