// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "list"
import { createGlassIcon } from '../createGlassIcon';

export const GlassList = /*#__PURE__*/ createGlassIcon("list", [[["M3 5L3.01 5",0],["M3 12L3.01 12",0],["M3 19L3.01 19",0],["M8 5L21 5",0],["M8 12L21 12",0],["M8 19L21 19",0]],[],[19.4,6.6,4.75],1]);
export default GlassList;
