// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "list-checks"
import { createGlassIcon } from '../createGlassIcon';

export const GlassListChecks = /*#__PURE__*/ createGlassIcon("list-checks", [["path",{"d":"M13 5h8"},0],["path",{"d":"M13 12h8"},0],["path",{"d":"M13 19h8"},0],["path",{"d":"M3 17l2 2l4 -4"},0],["path",{"d":"M3 7l2 2l4 -4"},0]]);
export default GlassListChecks;
