// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "list"
import { createGlassIcon } from '../createGlassIcon';

export const GlassList = /*#__PURE__*/ createGlassIcon("list", [["path",{"d":"M3 5h0.01"},0],["path",{"d":"M3 12h0.01"},0],["path",{"d":"M3 19h0.01"},0],["path",{"d":"M8 5h13"},0],["path",{"d":"M8 12h13"},0],["path",{"d":"M8 19h13"},0]]);
export default GlassList;
