// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "loader-pinwheel"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLoaderPinwheel = /*#__PURE__*/ createGlassIcon("loader-pinwheel", [["path",{"d":"M22 12a1 1 0 0 1 -10 0a1 1 0 0 0 -10 0"},0],["path",{"d":"M7 20.7a1 1 0 1 1 5 -8.7a1 1 0 1 0 5 -8.6"},0],["path",{"d":"M7 3.3a1 1 0 1 1 5 8.6a1 1 0 1 0 5 8.6"},0],["circle",{"cx":"12","cy":"12","r":"10"},1]]);
export default GlassLoaderPinwheel;
