// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "loader-circle"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLoaderCircle = /*#__PURE__*/ createGlassIcon("loader-circle", [["path",{"d":"M21 12a9 9 0 1 1 -6.219 -8.56"},0]]);
export default GlassLoaderCircle;
