// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "locate-fixed"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLocateFixed = /*#__PURE__*/ createGlassIcon("locate-fixed", [[["M5 12A7 7 0 1 0 19 12A7 7 0 1 0 5 12Z",1]],[["M2 12L5 12",0],["M19 12L22 12",0],["M12 2L12 5",0],["M12 19L12 22",0],["M9 12A3 3 0 1 0 15 12A3 3 0 1 0 9 12Z",1]],[17.676,6.324,4.29],0]);
export default GlassLocateFixed;
