// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "locate-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLocateOff = /*#__PURE__*/ createGlassIcon("locate-off", [["path",{"d":"M12 19v3"},0],["path",{"d":"M12 2v3"},0],["path",{"d":"M18.89 13.24a7 7 0 0 0 -8.13 -8.13"},0],["path",{"d":"M19 12h3"},0],["path",{"d":"M2 12h3"},0],["path",{"d":"M2 2l20 20"},0],["path",{"d":"M7.05 7.05a7 7 0 0 0 9.9 9.9"},0]]);
export default GlassLocateOff;
