// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "lock-keyhole"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLockKeyhole = /*#__PURE__*/ createGlassIcon("lock-keyhole", [["circle",{"cx":"12","cy":"16","r":"1"},1],["rect",{"x":"3","y":"10","width":"18","height":"12","rx":"2"},1],["path",{"d":"M7 10V7a5 5 0 0 1 10 0v3"},0]]);
export default GlassLockKeyhole;
