// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "log-out"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLogOut = /*#__PURE__*/ createGlassIcon("log-out", [["path",{"d":"M16 17l5 -5l-5 -5"},0],["path",{"d":"M21 12H9"},0],["path",{"d":"M9 21H5a2 2 0 0 1 -2 -2V5a2 2 0 0 1 2 -2h4"},0]]);
export default GlassLogOut;
