// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "logs"
import { createGlassIcon } from '../createGlassIcon';

export const GlassLogs = /*#__PURE__*/ createGlassIcon("logs", [["path",{"d":"M3 5h1"},0],["path",{"d":"M3 12h1"},0],["path",{"d":"M3 19h1"},0],["path",{"d":"M8 5h1"},0],["path",{"d":"M8 12h1"},0],["path",{"d":"M8 19h1"},0],["path",{"d":"M13 5h8"},0],["path",{"d":"M13 12h8"},0],["path",{"d":"M13 19h8"},0]]);
export default GlassLogs;
