// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "mail-x"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMailX = /*#__PURE__*/ createGlassIcon("mail-x", [["path",{"d":"M22 12.532V6a2 2 0 0 0 -2 -2H4a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h8.792"},0],["path",{"d":"M22 7l-8.991 5.727a2 2 0 0 1 -2.009 0L2 7"},0],["path",{"d":"M16.5 16.5l5 5"},0],["path",{"d":"M21.5 16.5l-5 5"},0]]);
export default GlassMailX;
