// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "map-pin-check"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMapPinCheck = /*#__PURE__*/ createGlassIcon("map-pin-check", [["path",{"d":"M19.43 12.935c0.357 -0.967 0.57 -1.955 0.57 -2.935a8 8 0 0 0 -16 0c0 4.993 5.539 10.193 7.399 11.799a1 1 0 0 0 1.202 0a32.197 32.197 0 0 0 0.813 -0.728"},0],["circle",{"cx":"12","cy":"10","r":"3"},1],["path",{"d":"M16 18l2 2l4 -4"},0]]);
export default GlassMapPinCheck;
