// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "map-pin-check-inside"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMapPinCheckInside = /*#__PURE__*/ createGlassIcon("map-pin-check-inside", [["path",{"d":"M20 10c0 4.993 -5.539 10.193 -7.399 11.799a1 1 0 0 1 -1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"},1],["path",{"d":"M9 10l2 2l4 -4"},0]]);
export default GlassMapPinCheckInside;
