// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "map-pin"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMapPin = /*#__PURE__*/ createGlassIcon("map-pin", [["path",{"d":"M20 10c0 4.993 -5.539 10.193 -7.399 11.799a1 1 0 0 1 -1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"},1],["circle",{"cx":"12","cy":"10","r":"3"},1]]);
export default GlassMapPin;
