// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "maximize-2"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMaximize2 = /*#__PURE__*/ createGlassIcon("maximize-2", [["path",{"d":"M15 3h6v6"},0],["path",{"d":"M21 3l-7 7"},0],["path",{"d":"M3 21l7 -7"},0],["path",{"d":"M9 21H3v-6"},0]]);
export default GlassMaximize2;
