// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "maximize"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMaximize = /*#__PURE__*/ createGlassIcon("maximize", [["path",{"d":"M8 3H5a2 2 0 0 0 -2 2v3"},0],["path",{"d":"M21 8V5a2 2 0 0 0 -2 -2h-3"},0],["path",{"d":"M3 16v3a2 2 0 0 0 2 2h3"},0],["path",{"d":"M16 21h3a2 2 0 0 0 2 -2v-3"},0]]);
export default GlassMaximize;
