// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "face-neutral" (alias of "meh")
import { createGlassIcon } from '../createGlassIcon';

export const GlassMeh = /*#__PURE__*/ createGlassIcon("meh", [[["M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z",1]],[["M15 10L15 9",1],["M8 16L16 16",1],["M9 10L9 9",1]],[20.4,3.6,4.75],0]);
export default GlassMeh;
