// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "message-square-dashed"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMessageSquareDashed = /*#__PURE__*/ createGlassIcon("message-square-dashed", [["path",{"d":"M14 3h2"},0],["path",{"d":"M16 19h-2"},0],["path",{"d":"M2 12v-2"},0],["path",{"d":"M2 16v5.286a0.71 0.71 0 0 0 1.212 0.502l1.149 -1.149"},0],["path",{"d":"M20 19a2 2 0 0 0 2 -2v-1"},0],["path",{"d":"M22 10v2"},0],["path",{"d":"M22 6V5a2 2 0 0 0 -2 -2"},0],["path",{"d":"M4 3a2 2 0 0 0 -2 2v1"},0],["path",{"d":"M8 19h2"},0],["path",{"d":"M8 3h2"},0]]);
export default GlassMessageSquareDashed;
