// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "message-square-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMessageSquareOff = /*#__PURE__*/ createGlassIcon("message-square-off", [["path",{"d":"M19 19H6.828a2 2 0 0 0 -1.414 0.586l-2.202 2.202A0.7 0.7 0 0 1 2 21.286V5a2 2 0 0 1 1.184 -1.826"},0],["path",{"d":"M2 2l20 20"},0],["path",{"d":"M8.656 3H20a2 2 0 0 1 2 2v11.344"},0]]);
export default GlassMessageSquareOff;
