// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "message-square-x"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMessageSquareX = /*#__PURE__*/ createGlassIcon("message-square-x", [[["M22 17A2 2 0 0 1 20 19L6.828 19A2 2 0 0 0 5.414 19.586L3.212 21.788A0.71 0.71 0 0 1 2 21.286L2 5A2 2 0 0 1 4 3L20 3A2 2 0 0 1 22 5Z",1]],[["M14.5 8.5L9.5 13.5",1],["M9.5 8.5L14.5 13.5",1]],[20.4,4.6,4.75],0]);
export default GlassMessageSquareX;
