// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "message-circle-dashed"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMessageCircleDashed = /*#__PURE__*/ createGlassIcon("message-circle-dashed", [[["M6.163 21.117L3.257 21.967A1 1 0 0 1 2.021 20.798L2.986 17.818Z",1]],[["M10.1 2.182A10 10 0 0 1 13.9 2.182",0],["M13.9 21.818A10 10 0 0 1 10.1 21.818",0],["M17.609 3.72A10 10 0 0 1 20.299 6.42",0],["M2.182 13.9A10 10 0 0 1 2.182 10.1",0],["M20.28 17.61A10 10 0 0 1 17.58 20.3",0],["M21.818 10.1A10 10 0 0 1 21.818 13.9",0],["M3.721 6.391A10 10 0 0 1 6.421 3.701",0]],[5.613,18.368,3],0]);
export default GlassMessageCircleDashed;
