// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "message-square-more"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMessageSquareMore = /*#__PURE__*/ createGlassIcon("message-square-more", [["path",{"d":"M22 17a2 2 0 0 1 -2 2H6.828a2 2 0 0 0 -1.414 0.586l-2.202 2.202A0.71 0.71 0 0 1 2 21.286V5a2 2 0 0 1 2 -2h16a2 2 0 0 1 2 2z"},1],["path",{"d":"M12 11h0.01"},0],["path",{"d":"M16 11h0.01"},0],["path",{"d":"M8 11h0.01"},0]]);
export default GlassMessageSquareMore;
