// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "message-circle-x"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMessageCircleX = /*#__PURE__*/ createGlassIcon("message-circle-x", [["path",{"d":"M2.992 16.342a2 2 0 0 1 0.094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413 -0.998a2 2 0 0 1 1.099 0.092a10 10 0 1 0 -4.777 -4.719"},1],["path",{"d":"M15 9l-6 6"},0],["path",{"d":"M9 9l6 6"},0]]);
export default GlassMessageCircleX;
