// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "message-square-heart"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMessageSquareHeart = /*#__PURE__*/ createGlassIcon("message-square-heart", [["path",{"d":"M22 17a2 2 0 0 1 -2 2H6.828a2 2 0 0 0 -1.414 0.586l-2.202 2.202A0.71 0.71 0 0 1 2 21.286V5a2 2 0 0 1 2 -2h16a2 2 0 0 1 2 2z"},1],["path",{"d":"M7.5 9.5c0 0.687 0.265 1.383 0.697 1.844l3.009 3.264a1.14 1.14 0 0 0 0.407 0.314a1 1 0 0 0 0.783 -0.004a1.14 1.14 0 0 0 0.398 -0.31l3.008 -3.264A2.77 2.77 0 0 0 16.5 9.5A2.5 2.5 0 0 0 12 8a2.5 2.5 0 0 0 -4.5 1.5"},1]]);
export default GlassMessageSquareHeart;
