// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "message-square-dot"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMessageSquareDot = /*#__PURE__*/ createGlassIcon("message-square-dot", [["path",{"d":"M12.7 3H4a2 2 0 0 0 -2 2v16.286a0.71 0.71 0 0 0 1.212 0.502l2.202 -2.202A2 2 0 0 1 6.828 19H20a2 2 0 0 0 2 -2v-4.7"},0],["circle",{"cx":"19","cy":"6","r":"3"},1]]);
export default GlassMessageSquareDot;
