// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "mic-vocal"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMicVocal = /*#__PURE__*/ createGlassIcon("mic-vocal", [[["M11 7A5 5 0 1 0 21 7A5 5 0 1 0 11 7Z",1],["M11 7.601L5.006 15.791A1 1 0 0 0 5.106 17.089L5.923 17.907A1 1 0 0 0 7.237 17.994L15.09 12Z",1]],[["M16.5 21.174C15.5 20.5 14.372 20 13 20C10.942 20 9.072 22.356 7 22C4.928 21.644 4.225 18.631 5.5 17.5",0]],[19.4,3.6,4.75],0]);
export default GlassMicVocal;
