// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "microwave"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMicrowave = /*#__PURE__*/ createGlassIcon("microwave", [["rect",{"width":"20","height":"15","x":"2","y":"4","rx":"2"},1],["rect",{"width":"8","height":"7","x":"6","y":"8","rx":"1"},1],["path",{"d":"M18 8v7"},0],["path",{"d":"M6 19v2"},0],["path",{"d":"M18 19v2"},0]]);
export default GlassMicrowave;
