// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "minimize-2"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMinimize2 = /*#__PURE__*/ createGlassIcon("minimize-2", [["path",{"d":"M14 10l7 -7"},0],["path",{"d":"M20 10h-6V4"},0],["path",{"d":"M3 21l7 -7"},0],["path",{"d":"M4 14h6v6"},0]]);
export default GlassMinimize2;
