// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "monitor-up"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMonitorUp = /*#__PURE__*/ createGlassIcon("monitor-up", [["path",{"d":"M9 10l3 -3l3 3"},0],["path",{"d":"M12 13V7"},0],["rect",{"width":"20","height":"14","x":"2","y":"3","rx":"2"},1],["path",{"d":"M12 17v4"},0],["path",{"d":"M8 21h8"},0]]);
export default GlassMonitorUp;
