// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "monitor-play"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMonitorPlay = /*#__PURE__*/ createGlassIcon("monitor-play", [["path",{"d":"M15.033 9.44a0.647 0.647 0 0 1 0 1.12l-4.065 2.352a0.645 0.645 0 0 1 -0.968 -0.56V7.648a0.645 0.645 0 0 1 0.967 -0.56z"},1],["path",{"d":"M12 17v4"},0],["path",{"d":"M8 21h8"},0],["rect",{"x":"2","y":"3","width":"20","height":"14","rx":"2"},1]]);
export default GlassMonitorPlay;
