// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "monitor-dot"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMonitorDot = /*#__PURE__*/ createGlassIcon("monitor-dot", [["path",{"d":"M12 17v4"},0],["path",{"d":"M22 12.307V15a2 2 0 0 1 -2 2H4a2 2 0 0 1 -2 -2V5a2 2 0 0 1 2 -2h8.693"},0],["path",{"d":"M8 21h8"},0],["circle",{"cx":"19","cy":"6","r":"3"},1]]);
export default GlassMonitorDot;
