// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "monitor-cog"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMonitorCog = /*#__PURE__*/ createGlassIcon("monitor-cog", [["path",{"d":"M12 17v4"},0],["path",{"d":"M14.305 7.53l0.923 -0.382"},0],["path",{"d":"M15.228 4.852l-0.923 -0.383"},0],["path",{"d":"M16.852 3.228l-0.383 -0.924"},0],["path",{"d":"M16.852 8.772l-0.383 0.923"},0],["path",{"d":"M19.148 3.228l0.383 -0.924"},0],["path",{"d":"M19.53 9.696l-0.382 -0.924"},0],["path",{"d":"M20.772 4.852l0.924 -0.383"},0],["path",{"d":"M20.772 7.148l0.924 0.383"},0],["path",{"d":"M22 13v2a2 2 0 0 1 -2 2H4a2 2 0 0 1 -2 -2V5a2 2 0 0 1 2 -2h7"},0],["path",{"d":"M8 21h8"},0],["circle",{"cx":"18","cy":"6","r":"3"},1]]);
export default GlassMonitorCog;
