// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "mountain"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMountain = /*#__PURE__*/ createGlassIcon("mountain", [["path",{"d":"M8 3l4 8l5 -5l5 15H2L8 3z"},1]]);
export default GlassMountain;
