// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "mouse-pointer-2"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMousePointer2 = /*#__PURE__*/ createGlassIcon("mouse-pointer-2", [[["M4.037 4.688A0.495 0.495 0 0 1 4.688 4.037L20.688 10.537A0.5 0.5 0 0 1 20.625 11.484L14.501 13.064A2 2 0 0 0 13.063 14.499L11.484 20.625A0.5 0.5 0 0 1 10.537 20.688Z",1]],[],[19.399,5.597,4.75],0]);
export default GlassMousePointer2;
