// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "move-up-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMoveUpLeft = /*#__PURE__*/ createGlassIcon("move-up-left", [["path",{"d":"M5 11V5H11"},0],["path",{"d":"M5 5L19 19"},0]]);
export default GlassMoveUpLeft;
