// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "move-horizontal"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMoveHorizontal = /*#__PURE__*/ createGlassIcon("move-horizontal", [["path",{"d":"M18 8l4 4l-4 4"},0],["path",{"d":"M2 12h20"},0],["path",{"d":"M6 8l-4 4l4 4"},0]]);
export default GlassMoveHorizontal;
