// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "move-horizontal"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMoveHorizontal = /*#__PURE__*/ createGlassIcon("move-horizontal", [[["M18 8L22 12L18 16",0],["M2 12L22 12",0],["M6 8L2 12L6 16",0]],[],[20.4,9.6,4.75],1]);
export default GlassMoveHorizontal;
