// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "music"
import { createGlassIcon } from '../createGlassIcon';

export const GlassMusic = /*#__PURE__*/ createGlassIcon("music", [["path",{"d":"M9 18V5l12 -2v13"},0],["circle",{"cx":"6","cy":"18","r":"3"},1],["circle",{"cx":"18","cy":"16","r":"3"},1]]);
export default GlassMusic;
