// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "navigation-2"
import { createGlassIcon } from '../createGlassIcon';

export const GlassNavigation2 = /*#__PURE__*/ createGlassIcon("navigation-2", [[["M12 2L19 21L12 17L5 21L12 2Z",1]],[],[17.4,3.6,4.75],0]);
export default GlassNavigation2;
