// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "newspaper"
import { createGlassIcon } from '../createGlassIcon';

export const GlassNewspaper = /*#__PURE__*/ createGlassIcon("newspaper", [["path",{"d":"M15 18h-5"},0],["path",{"d":"M18 14h-8"},0],["path",{"d":"M4 22h16a2 2 0 0 0 2 -2V4a2 2 0 0 0 -2 -2H8a2 2 0 0 0 -2 2v16a2 2 0 0 1 -4 0v-9a2 2 0 0 1 2 -2h2"},0],["rect",{"width":"8","height":"4","x":"10","y":"6","rx":"1"},1]]);
export default GlassNewspaper;
