// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "notebook-tabs"
import { createGlassIcon } from '../createGlassIcon';

export const GlassNotebookTabs = /*#__PURE__*/ createGlassIcon("notebook-tabs", [[["M6 2L18 2A2 2 0 0 1 20 4L20 20A2 2 0 0 1 18 22L6 22A2 2 0 0 1 4 20L4 4A2 2 0 0 1 6 2Z",1]],[["M2 6L6 6",1],["M2 10L6 10",1],["M2 14L6 14",1],["M2 18L6 18",1],["M15 2L15 22",1],["M15 7L20 7",1],["M15 12L20 12",1],["M15 17L20 17",1]],[18.4,3.6,4.75],0]);
export default GlassNotebookTabs;
