// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "notebook-tabs"
import { createGlassIcon } from '../createGlassIcon';

export const GlassNotebookTabs = /*#__PURE__*/ createGlassIcon("notebook-tabs", [["path",{"d":"M2 6h4"},0],["path",{"d":"M2 10h4"},0],["path",{"d":"M2 14h4"},0],["path",{"d":"M2 18h4"},0],["rect",{"width":"16","height":"20","x":"4","y":"2","rx":"2"},1],["path",{"d":"M15 2v20"},0],["path",{"d":"M15 7h5"},0],["path",{"d":"M15 12h5"},0],["path",{"d":"M15 17h5"},0]]);
export default GlassNotebookTabs;
