// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "notepad-text"
import { createGlassIcon } from '../createGlassIcon';

export const GlassNotepadText = /*#__PURE__*/ createGlassIcon("notepad-text", [["path",{"d":"M8 2v4"},0],["path",{"d":"M12 2v4"},0],["path",{"d":"M16 2v4"},0],["rect",{"width":"16","height":"18","x":"4","y":"4","rx":"2"},1],["path",{"d":"M8 10h6"},0],["path",{"d":"M8 14h8"},0],["path",{"d":"M8 18h5"},0]]);
export default GlassNotepadText;
