// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "notebook-text"
import { createGlassIcon } from '../createGlassIcon';

export const GlassNotebookText = /*#__PURE__*/ createGlassIcon("notebook-text", [["path",{"d":"M2 6h4"},0],["path",{"d":"M2 10h4"},0],["path",{"d":"M2 14h4"},0],["path",{"d":"M2 18h4"},0],["rect",{"width":"16","height":"20","x":"4","y":"2","rx":"2"},1],["path",{"d":"M9.5 8h5"},0],["path",{"d":"M9.5 12H16"},0],["path",{"d":"M9.5 16H14"},0]]);
export default GlassNotebookText;
