// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "notebook"
import { createGlassIcon } from '../createGlassIcon';

export const GlassNotebook = /*#__PURE__*/ createGlassIcon("notebook", [["path",{"d":"M2 6h4"},0],["path",{"d":"M2 10h4"},0],["path",{"d":"M2 14h4"},0],["path",{"d":"M2 18h4"},0],["rect",{"width":"16","height":"20","x":"4","y":"2","rx":"2"},1],["path",{"d":"M16 2v20"},0]]);
export default GlassNotebook;
