// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "package-minus"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPackageMinus = /*#__PURE__*/ createGlassIcon("package-minus", [["path",{"d":"M12 22V12"},0],["path",{"d":"M16 17h6"},0],["path",{"d":"M21 13V8a2 2 0 0 0 -1 -1.73l-7 -4a2 2 0 0 0 -2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.729l7 4a2 2 0 0 0 2 0.001l1.675 -0.955"},0],["path",{"d":"M3.29 7L12 12l8.71 -5"},0],["path",{"d":"M7.5 4.27l8.997 5.148"},0]]);
export default GlassPackageMinus;
