// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "package"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPackage = /*#__PURE__*/ createGlassIcon("package", [[["M11 21.73A2 2 0 0 0 13 21.73L20 17.73A2 2 0 0 0 21 16L21 8A2 2 0 0 0 20 6.27L13 2.27A2 2 0 0 0 11 2.27L4 6.27A2 2 0 0 0 3 8L3 16A2 2 0 0 0 4 17.73Z",1]],[["M12 22L12 12",1],["M3.29 7L12 12L20.71 7",1],["M7.5 4.27L16.5 9.42",1]],[19.4,3.602,4.75],0]);
export default GlassPackage;
