// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "paintbrush-vertical"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPaintbrushVertical = /*#__PURE__*/ createGlassIcon("paintbrush-vertical", [["path",{"d":"M10 2v2"},0],["path",{"d":"M14 2v4"},0],["path",{"d":"M17 2a1 1 0 0 1 1 1v9H6V3a1 1 0 0 1 1 -1z"},1],["path",{"d":"M6 12a1 1 0 0 0 -1 1v1a2 2 0 0 0 2 2h2a1 1 0 0 1 1 1v2.9a2 2 0 1 0 4 0V17a1 1 0 0 1 1 -1h2a2 2 0 0 0 2 -2v-1a1 1 0 0 0 -1 -1"},0]]);
export default GlassPaintbrushVertical;
