// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "paint-bucket"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPaintBucket = /*#__PURE__*/ createGlassIcon("paint-bucket", [["path",{"d":"M11 7L6 2"},0],["path",{"d":"M18.992 12H2.041"},0],["path",{"d":"M21.145 18.38A3.34 3.34 0 0 1 20 16.5a3.3 3.3 0 0 1 -1.145 1.88c-0.575 0.46 -0.855 1.02 -0.855 1.595A2 2 0 0 0 20 22a2 2 0 0 0 2 -2.025c0 -0.58 -0.285 -1.13 -0.855 -1.595"},1],["path",{"d":"M8.5 4.5l2.148 -2.148a1.205 1.205 0 0 1 1.704 0l7.296 7.296a1.205 1.205 0 0 1 0 1.704l-7.592 7.592a3.615 3.615 0 0 1 -5.112 0l-3.888 -3.888a3.615 3.615 0 0 1 0 -5.112L5.67 7.33"},0]]);
export default GlassPaintBucket;
