// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "palette"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPalette = /*#__PURE__*/ createGlassIcon("palette", [[["M12 22A1 1 0 0 1 12 2A10 9 0 0 1 22 11A5 5 0 0 1 17 16L14.75 16A1.75 1.75 0 0 0 13.35 18.8L13.65 19.2A1.75 1.75 0 0 1 12.25 22Z",1]],[["M13 6.5A0.5 0.5 0 1 0 14 6.5A0.5 0.5 0 1 0 13 6.5Z",1],["M17 10.5A0.5 0.5 0 1 0 18 10.5A0.5 0.5 0 1 0 17 10.5Z",1],["M6 12.5A0.5 0.5 0 1 0 7 12.5A0.5 0.5 0 1 0 6 12.5Z",1],["M8 7.5A0.5 0.5 0 1 0 9 7.5A0.5 0.5 0 1 0 8 7.5Z",1]],[20.4,3.6,4.75],0]);
export default GlassPalette;
