// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "palette"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPalette = /*#__PURE__*/ createGlassIcon("palette", [["path",{"d":"M12 22a1 1 0 0 1 0 -20a10 9 0 0 1 10 9a5 5 0 0 1 -5 5h-2.25a1.75 1.75 0 0 0 -1.4 2.8l0.3 0.4a1.75 1.75 0 0 1 -1.4 2.8z"},1],["circle",{"cx":"13.5","cy":"6.5","r":".5"},1],["circle",{"cx":"17.5","cy":"10.5","r":".5"},1],["circle",{"cx":"6.5","cy":"12.5","r":".5"},1],["circle",{"cx":"8.5","cy":"7.5","r":".5"},1]]);
export default GlassPalette;
