// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "panels-left-bottom"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPanelsLeftBottom = /*#__PURE__*/ createGlassIcon("panels-left-bottom", [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1],["path",{"d":"M9 3v18"},0],["path",{"d":"M9 15h12"},0]]);
export default GlassPanelsLeftBottom;
