// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "panel-bottom-close"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPanelBottomClose = /*#__PURE__*/ createGlassIcon("panel-bottom-close", [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1],["path",{"d":"M3 15h18"},0],["path",{"d":"M15 8l-3 3l-3 -3"},0]]);
export default GlassPanelBottomClose;
