// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "panel-bottom-open"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPanelBottomOpen = /*#__PURE__*/ createGlassIcon("panel-bottom-open", [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1],["path",{"d":"M3 15h18"},0],["path",{"d":"M9 10l3 -3l3 3"},0]]);
export default GlassPanelBottomOpen;
