// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "panel-left-close"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPanelLeftClose = /*#__PURE__*/ createGlassIcon("panel-left-close", [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1],["path",{"d":"M9 3v18"},0],["path",{"d":"M16 15l-3 -3l3 -3"},0]]);
export default GlassPanelLeftClose;
