// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "panels-top-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPanelsTopLeft = /*#__PURE__*/ createGlassIcon("panels-top-left", [[["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z",1]],[["M3 9L21 9",1],["M9 21L9 9",1]],[19.4,4.6,4.75],0]);
export default GlassPanelsTopLeft;
