// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "panel-bottom-dashed"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPanelBottomDashed = /*#__PURE__*/ createGlassIcon("panel-bottom-dashed", [[["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z",1]],[["M14 15L15 15",1],["M19 15L21 15",1],["M3 15L5 15",1],["M9 15L10 15",1]],[19.4,4.6,4.75],0]);
export default GlassPanelBottomDashed;
