// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pc-case"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPcCase = /*#__PURE__*/ createGlassIcon("pc-case", [["rect",{"width":"14","height":"20","x":"5","y":"2","rx":"2"},1],["path",{"d":"M15 14h0.01"},0],["path",{"d":"M9 6h6"},0],["path",{"d":"M9 10h6"},0]]);
export default GlassPcCase;
