// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "phone-incoming"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPhoneIncoming = /*#__PURE__*/ createGlassIcon("phone-incoming", [["path",{"d":"M16 2v6h6"},0],["path",{"d":"M22 2l-6 6"},0],["path",{"d":"M13.832 16.568a1 1 0 0 0 1.213 -0.303l0.355 -0.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2A18 18 0 0 1 2 4a2 2 0 0 1 2 -2h3a2 2 0 0 1 2 2v3a2 2 0 0 1 -0.8 1.6l-0.468 0.351a1 1 0 0 0 -0.292 1.233a14 14 0 0 0 6.392 6.384"},1]]);
export default GlassPhoneIncoming;
