// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "piano"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPiano = /*#__PURE__*/ createGlassIcon("piano", [["path",{"d":"M10 13v4"},0],["path",{"d":"M14 13v4"},0],["path",{"d":"M18 13v4"},0],["path",{"d":"M2 13h20"},0],["path",{"d":"M22 11.5A3.5 3.5 0 0 0 18.5 8a3.52 3.52 0 0 1 -3.173 -2A7 7 0 0 0 2 9v10a2 2 0 0 0 2 2h16a2 2 0 0 0 2 -2z"},1],["path",{"d":"M6 13v4"},0]]);
export default GlassPiano;
