// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pickaxe"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPickaxe = /*#__PURE__*/ createGlassIcon("pickaxe", [["path",{"d":"M14 13l-8.381 8.38a1 1 0 0 1 -3.001 -3L11 9.999"},0],["path",{"d":"M15.973 4.027A13 13 0 0 0 5.902 2.373c-1.398 0.342 -1.092 2.158 0.277 2.601a19.9 19.9 0 0 1 5.822 3.024"},0],["path",{"d":"M16.001 11.999a19.9 19.9 0 0 1 3.024 5.824c0.444 1.369 2.26 1.676 2.603 0.278A13 13 0 0 0 20 8.069"},0],["path",{"d":"M18.352 3.352a1.205 1.205 0 0 0 -1.704 0l-5.296 5.296a1.205 1.205 0 0 0 0 1.704l2.296 2.296a1.205 1.205 0 0 0 1.704 0l5.296 -5.296a1.205 1.205 0 0 0 0 -1.704z"},1]]);
export default GlassPickaxe;
