// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pilcrow-right"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPilcrowRight = /*#__PURE__*/ createGlassIcon("pilcrow-right", [["path",{"d":"M10 3v11"},0],["path",{"d":"M10 9H7a1 1 0 0 1 0 -6h8"},0],["path",{"d":"M14 3v11"},0],["path",{"d":"M18 14l4 4H2"},0],["path",{"d":"M22 18l-4 4"},0]]);
export default GlassPilcrowRight;
