// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pin"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPin = /*#__PURE__*/ createGlassIcon("pin", [[["M9 10.76A2 2 0 0 1 7.89 12.55L6.11 13.45A2 2 0 0 0 5 15.24L5 16A1 1 0 0 0 6 17L18 17A1 1 0 0 0 19 16L19 15.24A2 2 0 0 0 17.89 13.45L16.11 12.55A2 2 0 0 1 15 10.76L15 7A1 1 0 0 1 16 6A2 2 0 0 0 16 2L8 2A2 2 0 0 0 8 6A1 1 0 0 1 9 7Z",1]],[["M12 17L12 22",0]],[17.52,3.48,4.55],0]);
export default GlassPin;
