// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "plug"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPlug = /*#__PURE__*/ createGlassIcon("plug", [[["M17 8A1 1 0 0 1 18 9L18 13A4 4 0 0 1 14 17L10 17A4 4 0 0 1 6 13L6 9A1 1 0 0 1 7 8Z",1]],[["M12 22L12 17",0],["M15 8L15 2",0],["M9 8L9 2",0]],[16.988,9.012,3.77],0]);
export default GlassPlug;
