// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "plug"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPlug = /*#__PURE__*/ createGlassIcon("plug", [["path",{"d":"M12 22v-5"},0],["path",{"d":"M15 8V2"},0],["path",{"d":"M17 8a1 1 0 0 1 1 1v4a4 4 0 0 1 -4 4h-4a4 4 0 0 1 -4 -4V9a1 1 0 0 1 1 -1z"},1],["path",{"d":"M9 8V2"},0]]);
export default GlassPlug;
