// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "plug-2"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPlug2 = /*#__PURE__*/ createGlassIcon("plug-2", [["path",{"d":"M9 2v6"},0],["path",{"d":"M15 2v6"},0],["path",{"d":"M12 17v5"},0],["path",{"d":"M5 8h14"},0],["path",{"d":"M6 11V8h12v3a6 6 0 1 1 -12 0Z"},1]]);
export default GlassPlug2;
