// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "mic-signal" (alias of "podcast")
import { createGlassIcon } from '../createGlassIcon';

export const GlassPodcast = /*#__PURE__*/ createGlassIcon("podcast", [[["M12 9L12 9A2 2 0 0 1 14 11L14 15A2 2 0 0 1 12 17L12 17A2 2 0 0 1 10 15L10 11A2 2 0 0 1 12 9Z",1]],[["M12 17L12 21",0],["M18 11A6 6 0 0 0 15 5.803",0],["M2 11A10 10 0 0 1 7 2.338",0],["M22 11A10 10 0 0 0 17 2.338",0],["M6 11A6 6 0 0 1 9 5.803",0],["M9 21L15 21",0]],[13.45,9.55,3],0]);
export default GlassPodcast;
