// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "popcorn"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPopcorn = /*#__PURE__*/ createGlassIcon("popcorn", [[["M20 8C20.5 8 20.9 8.4 20.8 9L18.2 21C18.1 21.5 17.5 22 17 22L7 22C6.4 22 5.9 21.6 5.8 21L3.2 9C3.1 8.4 3.5 8 4 8Z",1],["M18 8A2 2 0 0 0 18 4A2 2 0 0 0 14 4A2 2 0 0 0 10 4A2 2 0 0 0 6 4A2 2 0 0 0 6 8Z",1]],[["M10 22L9 8",1],["M14 22L15 8",1]],[19.215,3.6,4.75],0]);
export default GlassPopcorn;
