// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pound-sterling"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPoundSterling = /*#__PURE__*/ createGlassIcon("pound-sterling", [[["M18 7C18 1.667 10 1.667 10 7Z",1]],[["M10 7L10 21",0],["M6 21L18 21",0],["M6 13L16 13",0]],[17.45,3.55,3],0]);
export default GlassPoundSterling;
