// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "power-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPowerOff = /*#__PURE__*/ createGlassIcon("power-off", [[["M6.16 6.16A9 9 0 1 0 18.84 18.84Z",1],["M2 2L22 22",0]],[["M18.36 6.64A9 9 0 0 1 20.77 15",0],["M12 2L12 6",0]],[20.4,3.6,4.75],0]);
export default GlassPowerOff;
