// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "presentation"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPresentation = /*#__PURE__*/ createGlassIcon("presentation", [[["M21 3L21 14A2 2 0 0 1 19 16L5 16A2 2 0 0 1 3 14L3 3Z",1],["M2 3L22 3",0]],[["M7 21L12 16L17 21",0]],[20.4,4.6,4.75],0]);
export default GlassPresentation;
