// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "puzzle"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPuzzle = /*#__PURE__*/ createGlassIcon("puzzle", [["path",{"d":"M15.39 4.39a1 1 0 0 0 1.68 -0.474a2.5 2.5 0 1 1 3.014 3.015a1 1 0 0 0 -0.474 1.68l1.683 1.682a2.414 2.414 0 0 1 0 3.414L19.61 15.39a1 1 0 0 1 -1.68 -0.474a2.5 2.5 0 1 0 -3.014 3.015a1 1 0 0 1 0.474 1.68l-1.683 1.682a2.414 2.414 0 0 1 -3.414 0L8.61 19.61a1 1 0 0 0 -1.68 0.474a2.5 2.5 0 1 1 -3.014 -3.015a1 1 0 0 0 0.474 -1.68l-1.683 -1.682a2.414 2.414 0 0 1 0 -3.414L4.39 8.61a1 1 0 0 1 1.68 0.474a2.5 2.5 0 1 0 3.014 -3.015a1 1 0 0 1 -0.474 -1.68l1.683 -1.682a2.414 2.414 0 0 1 3.414 0z"},1]]);
export default GlassPuzzle;
