// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pyramid"
import { createGlassIcon } from '../createGlassIcon';

export const GlassPyramid = /*#__PURE__*/ createGlassIcon("pyramid", [["path",{"d":"M2.5 16.88a1 1 0 0 1 -0.32 -1.43l9 -13.02a1 1 0 0 1 1.64 0l9 13.01a1 1 0 0 1 -0.32 1.44l-8.51 4.86a2 2 0 0 1 -1.98 0Z"},1],["path",{"d":"M12 2v20"},0]]);
export default GlassPyramid;
