// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "qr-code"
import { createGlassIcon } from '../createGlassIcon';

export const GlassQrCode = /*#__PURE__*/ createGlassIcon("qr-code", [["rect",{"width":"5","height":"5","x":"3","y":"3","rx":"1"},1],["rect",{"width":"5","height":"5","x":"16","y":"3","rx":"1"},1],["rect",{"width":"5","height":"5","x":"3","y":"16","rx":"1"},1],["path",{"d":"M21 16h-3a2 2 0 0 0 -2 2v3"},0],["path",{"d":"M21 21v0.01"},0],["path",{"d":"M12 7v3a2 2 0 0 1 -2 2H7"},0],["path",{"d":"M3 12h0.01"},0],["path",{"d":"M12 3h0.01"},0],["path",{"d":"M12 16v0.01"},0],["path",{"d":"M16 12h1"},0],["path",{"d":"M21 12v0.01"},0],["path",{"d":"M12 21v-1"},0]]);
export default GlassQrCode;
