// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "radio-tower"
import { createGlassIcon } from '../createGlassIcon';

export const GlassRadioTower = /*#__PURE__*/ createGlassIcon("radio-tower", [["path",{"d":"M4.9 16.1C1 12.2 1 5.8 4.9 1.9"},0],["path",{"d":"M7.8 4.7a6.14 6.14 0 0 0 -0.8 7.5"},0],["circle",{"cx":"12","cy":"9","r":"2"},1],["path",{"d":"M16.2 4.8c2 2 2.26 5.11 0.8 7.47"},0],["path",{"d":"M19.1 1.9a9.96 9.96 0 0 1 0 14.1"},0],["path",{"d":"M9.5 18h5"},0],["path",{"d":"M8 22l4 -11l4 11"},0]]);
export default GlassRadioTower;
