// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: Sakani Figma icon set, icon "rail-symbol"
import { createGlassIcon } from '../createGlassIcon';

export const GlassRailSymbol = /*#__PURE__*/ createGlassIcon("rail-symbol", [["path",{"d":"M5 15H19"},0],["path",{"d":"M5 9H19"},0],["path",{"d":"M14 20L9 15L15 9L10 4"},0]]);
export default GlassRailSymbol;
