// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "receipt-turkish-lira"
import { createGlassIcon } from '../createGlassIcon';

export const GlassReceiptTurkishLira = /*#__PURE__*/ createGlassIcon("receipt-turkish-lira", [["path",{"d":"M10 7v10a5 5 0 0 0 5 -5"},0],["path",{"d":"M14 8l-6 3"},0],["path",{"d":"M4 3a1 1 0 0 1 1 -1a1.3 1.3 0 0 1 0.7 0.2l0.933 0.6a1.3 1.3 0 0 0 1.4 0l0.934 -0.6a1.3 1.3 0 0 1 1.4 0l0.933 0.6a1.3 1.3 0 0 0 1.4 0l0.933 -0.6a1.3 1.3 0 0 1 1.4 0l0.934 0.6a1.3 1.3 0 0 0 1.4 0l0.933 -0.6A1.3 1.3 0 0 1 19 2a1 1 0 0 1 1 1v18a1 1 0 0 1 -1 1a1.3 1.3 0 0 1 -0.7 -0.2l-0.933 -0.6a1.3 1.3 0 0 0 -1.4 0l-0.934 0.6a1.3 1.3 0 0 1 -1.4 0l-0.933 -0.6a1.3 1.3 0 0 0 -1.4 0l-0.933 0.6a1.3 1.3 0 0 1 -1.4 0l-0.934 -0.6a1.3 1.3 0 0 0 -1.4 0l-0.933 0.6a1.3 1.3 0 0 1 -0.7 0.2a1 1 0 0 1 -1 -1z"},1]]);
export default GlassReceiptTurkishLira;
