// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "receipt-indian-rupee"
import { createGlassIcon } from '../createGlassIcon';

export const GlassReceiptIndianRupee = /*#__PURE__*/ createGlassIcon("receipt-indian-rupee", [["path",{"d":"M4 3a1 1 0 0 1 1 -1a1.3 1.3 0 0 1 0.7 0.2l0.933 0.6a1.3 1.3 0 0 0 1.4 0l0.934 -0.6a1.3 1.3 0 0 1 1.4 0l0.933 0.6a1.3 1.3 0 0 0 1.4 0l0.933 -0.6a1.3 1.3 0 0 1 1.4 0l0.934 0.6a1.3 1.3 0 0 0 1.4 0l0.933 -0.6A1.3 1.3 0 0 1 19 2a1 1 0 0 1 1 1v18a1 1 0 0 1 -1 1a1.3 1.3 0 0 1 -0.7 -0.2l-0.933 -0.6a1.3 1.3 0 0 0 -1.4 0l-0.934 0.6a1.3 1.3 0 0 1 -1.4 0l-0.933 -0.6a1.3 1.3 0 0 0 -1.4 0l-0.933 0.6a1.3 1.3 0 0 1 -1.4 0l-0.934 -0.6a1.3 1.3 0 0 0 -1.4 0l-0.933 0.6a1.3 1.3 0 0 1 -0.7 0.2a1 1 0 0 1 -1 -1z"},1],["path",{"d":"M8 11h8"},0],["path",{"d":"M8 7h8"},0],["path",{"d":"M9 7a4 4 0 0 1 0 8H8l3 2"},0]]);
export default GlassReceiptIndianRupee;
