// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "rectangle-ellipsis"
import { createGlassIcon } from '../createGlassIcon';

export const GlassRectangleEllipsis = /*#__PURE__*/ createGlassIcon("rectangle-ellipsis", [["rect",{"width":"20","height":"12","x":"2","y":"6","rx":"2"},1],["path",{"d":"M12 12h0.01"},0],["path",{"d":"M17 12h0.01"},0],["path",{"d":"M7 12h0.01"},0]]);
export default GlassRectangleEllipsis;
