// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "recycle"
import { createGlassIcon } from '../createGlassIcon';

export const GlassRecycle = /*#__PURE__*/ createGlassIcon("recycle", [[["M7 19L4.815 19A1.83 1.83 0 0 1 3.245 18.119A1.785 1.785 0 0 1 3.241 16.335L7.196 9.5",0],["M11 19L19.203 19A1.83 1.83 0 0 0 20.759 18.11A1.784 1.784 0 0 0 20.759 16.335L19.533 14.215",0],["M14 16L11 19L14 22",0],["M8.293 13.596L7.196 9.5L3.1 10.598",0],["M9.344 5.811L10.437 3.919A1.83 1.83 0 0 1 11.985 3A1.784 1.784 0 0 1 13.531 3.888L17.474 10.731",0],["M13.378 9.633L17.474 10.731L18.571 6.635",0]],[],[19.395,4.6,4.75],1]);
export default GlassRecycle;
