// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "recycle"
import { createGlassIcon } from '../createGlassIcon';

export const GlassRecycle = /*#__PURE__*/ createGlassIcon("recycle", [["path",{"d":"M7 19H4.815a1.83 1.83 0 0 1 -1.57 -0.881a1.785 1.785 0 0 1 -0.004 -1.784L7.196 9.5"},0],["path",{"d":"M11 19h8.203a1.83 1.83 0 0 0 1.556 -0.89a1.784 1.784 0 0 0 0 -1.775l-1.226 -2.12"},0],["path",{"d":"M14 16l-3 3l3 3"},0],["path",{"d":"M8.293 13.596L7.196 9.5L3.1 10.598"},0],["path",{"d":"M9.344 5.811l1.093 -1.892A1.83 1.83 0 0 1 11.985 3a1.784 1.784 0 0 1 1.546 0.888l3.943 6.843"},0],["path",{"d":"M13.378 9.633l4.096 1.098l1.097 -4.096"},0]]);
export default GlassRecycle;
