// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "refresh-ccw-dot"
import { createGlassIcon } from '../createGlassIcon';

export const GlassRefreshCcwDot = /*#__PURE__*/ createGlassIcon("refresh-ccw-dot", [[["M21 12A9 9 0 0 0 12 3A9.75 9.75 0 0 0 5.26 5.74L3 8",0],["M3 3L3 8L8 8",0],["M3 12A9 9 0 0 0 12 21A9.75 9.75 0 0 0 18.74 18.26L21 16",0],["M16 16L21 16L21 21",0],["M11 12A1 1 0 1 0 13 12A1 1 0 1 0 11 12Z",0]],[],[19.4,4.6,4.75],1]);
export default GlassRefreshCcwDot;
