// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "repeat"
import { createGlassIcon } from '../createGlassIcon';

export const GlassRepeat = /*#__PURE__*/ createGlassIcon("repeat", [[["M17 2L21 6L17 10",0],["M3 11L3 10A4 4 0 0 1 7 6L21 6",0],["M7 22L3 18L7 14",0],["M21 13L21 14A4 4 0 0 1 17 18L3 18",0]],[],[19.4,3.6,4.75],1]);
export default GlassRepeat;
