// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "reply"
import { createGlassIcon } from '../createGlassIcon';

export const GlassReply = /*#__PURE__*/ createGlassIcon("reply", [["path",{"d":"M20 18v-2a4 4 0 0 0 -4 -4H4"},0],["path",{"d":"M9 17l-5 -5l5 -5"},0]]);
export default GlassReply;
