// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "rocket"
import { createGlassIcon } from '../createGlassIcon';

export const GlassRocket = /*#__PURE__*/ createGlassIcon("rocket", [["path",{"d":"M12 15v5s3.03 -0.55 4 -2c1.08 -1.62 0 -5 0 -5"},0],["path",{"d":"M4.5 16.5c-1.5 1.26 -2 5 -2 5s3.74 -0.5 5 -2c0.71 -0.84 0.7 -2.13 -0.09 -2.91a2.18 2.18 0 0 0 -2.91 -0.09"},1],["path",{"d":"M9 12a22 22 0 0 1 2 -3.95A12.88 12.88 0 0 1 22 2c0 2.72 -0.78 7.5 -6 11a22.4 22.4 0 0 1 -4 2z"},1],["path",{"d":"M9 12H4s0.55 -3.03 2 -4c1.62 -1.08 5 0.05 5 0.05"},0]]);
export default GlassRocket;
