// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "rotate-ccw"
import { createGlassIcon } from '../createGlassIcon';

export const GlassRotateCcw = /*#__PURE__*/ createGlassIcon("rotate-ccw", [[["M3 12A9 9 0 1 0 12 3A9.75 9.75 0 0 0 5.26 5.74L3 8Z",1]],[["M3 3L3 8L8 8",1]],[19.4,4.6,4.75],0]);
export default GlassRotateCcw;
