// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "rotate-ccw-key"
import { createGlassIcon } from '../createGlassIcon';

export const GlassRotateCcwKey = /*#__PURE__*/ createGlassIcon("rotate-ccw-key", [["path",{"d":"M12 7v6"},0],["path",{"d":"M12 9h2"},0],["path",{"d":"M3 12a9 9 0 1 0 9 -9a9.74 9.74 0 0 0 -6.74 2.74L3 8"},0],["path",{"d":"M3 3v5h5"},0],["circle",{"cx":"12","cy":"15","r":"2"},1]]);
export default GlassRotateCcwKey;
