// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "router"
import { createGlassIcon } from '../createGlassIcon';

export const GlassRouter = /*#__PURE__*/ createGlassIcon("router", [["rect",{"width":"20","height":"8","x":"2","y":"14","rx":"2"},1],["path",{"d":"M6.01 18H6"},0],["path",{"d":"M10.01 18H10"},0],["path",{"d":"M15 10v4"},0],["path",{"d":"M17.84 7.17a4 4 0 0 0 -5.66 0"},0],["path",{"d":"M20.66 4.34a8 8 0 0 0 -11.31 0"},0]]);
export default GlassRouter;
