// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "save"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSave = /*#__PURE__*/ createGlassIcon("save", [[["M15.2 3A2 2 0 0 1 16.6 3.6L20.4 7.4A2 2 0 0 1 21 8.8L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z",1]],[["M17 21L17 14A1 1 0 0 0 16 13L8 13A1 1 0 0 0 7 14L7 21",1],["M7 3L7 7A1 1 0 0 0 8 8L15 8",1]],[19.4,4.6,4.75],0]);
export default GlassSave;
