// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "school"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSchool = /*#__PURE__*/ createGlassIcon("school", [["path",{"d":"M14 21v-3a2 2 0 0 0 -4 0v3"},0],["path",{"d":"M18 4.933V21"},0],["path",{"d":"M4 6l7.106 -3.79a2 2 0 0 1 1.788 0L20 6"},0],["path",{"d":"M6 11l-3.52 2.147a1 1 0 0 0 -0.48 0.854V19a2 2 0 0 0 2 2h16a2 2 0 0 0 2 -2v-5a1 1 0 0 0 -0.48 -0.853L18 11"},0],["path",{"d":"M6 4.933V21"},0],["circle",{"cx":"12","cy":"9","r":"2"},1]]);
export default GlassSchool;
