// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "screen-share-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassScreenShareOff = /*#__PURE__*/ createGlassIcon("screen-share-off", [["path",{"d":"M13 3H4a2 2 0 0 0 -2 2v10a2 2 0 0 0 2 2h16a2 2 0 0 0 2 -2v-3"},0],["path",{"d":"M8 21h8"},0],["path",{"d":"M12 17v4"},0],["path",{"d":"M22 3l-5 5"},0],["path",{"d":"M17 3l5 5"},0]]);
export default GlassScreenShareOff;
