// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "scroll-text"
import { createGlassIcon } from '../createGlassIcon';

export const GlassScrollText = /*#__PURE__*/ createGlassIcon("scroll-text", [["path",{"d":"M15 12h-5"},0],["path",{"d":"M15 8h-5"},0],["path",{"d":"M19 17V5a2 2 0 0 0 -2 -2H4"},0],["path",{"d":"M8 21h12a2 2 0 0 0 2 -2v-1a1 1 0 0 0 -1 -1H11a1 1 0 0 0 -1 1v1a2 2 0 1 1 -4 0V5a2 2 0 1 0 -4 0v2a1 1 0 0 0 1 1h3"},0]]);
export default GlassScrollText;
