// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "settings"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSettings = /*#__PURE__*/ createGlassIcon("settings", [[["M9.671 4.136A2.34 2.34 0 0 1 14.33 4.136A2.34 2.34 0 0 0 17.649 6.051A2.34 2.34 0 0 1 19.979 10.084A2.34 2.34 0 0 0 19.979 13.915A2.34 2.34 0 0 1 17.649 17.948A2.34 2.34 0 0 0 14.33 19.863A2.34 2.34 0 0 1 9.671 19.863A2.34 2.34 0 0 0 6.351 17.948A2.34 2.34 0 0 1 4.021 13.915A2.34 2.34 0 0 0 4.021 10.084A2.34 2.34 0 0 1 6.35 6.051A2.34 2.34 0 0 0 9.669 4.136",1]],[["M9 12A3 3 0 1 0 15 12A3 3 0 1 0 9 12Z",1]],[19.355,3.617,4.75],0]);
export default GlassSettings;
