// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "share-2"
import { createGlassIcon } from '../createGlassIcon';

export const GlassShare2 = /*#__PURE__*/ createGlassIcon("share-2", [["circle",{"cx":"18","cy":"5","r":"3"},1],["circle",{"cx":"6","cy":"12","r":"3"},1],["circle",{"cx":"18","cy":"19","r":"3"},1],["line",{"x1":"8.59","x2":"15.42","y1":"13.51","y2":"17.49"},0],["line",{"x1":"15.41","x2":"8.59","y1":"6.51","y2":"10.49"},0]]);
export default GlassShare2;
