// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "shower-head"
import { createGlassIcon } from '../createGlassIcon';

export const GlassShowerHead = /*#__PURE__*/ createGlassIcon("shower-head", [[["M13.5 6.5A4.95 4.95 0 0 0 6.5 13.5Z",1],["M15 5L5 15",0]],[["M4 4L6.5 6.5",0],["M14 17L14 17.01",0],["M10 16L10 16.01",0],["M13 13L13 13.01",0],["M16 10L16 10.01",0],["M11 20L11 20.01",0],["M17 14L17 14.01",0],["M20 11L20 11.01",0]],[14.3,5.7,3.25],0]);
export default GlassShowerHead;
