// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "shower-head"
import { createGlassIcon } from '../createGlassIcon';

export const GlassShowerHead = /*#__PURE__*/ createGlassIcon("shower-head", [["path",{"d":"M4 4l2.5 2.5"},0],["path",{"d":"M13.5 6.5a4.95 4.95 0 0 0 -7 7"},0],["path",{"d":"M15 5L5 15"},0],["path",{"d":"M14 17v0.01"},0],["path",{"d":"M10 16v0.01"},0],["path",{"d":"M13 13v0.01"},0],["path",{"d":"M16 10v0.01"},0],["path",{"d":"M11 20v0.01"},0],["path",{"d":"M17 14v0.01"},0],["path",{"d":"M20 11v0.01"},0]]);
export default GlassShowerHead;
