// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "shrink"
import { createGlassIcon } from '../createGlassIcon';

export const GlassShrink = /*#__PURE__*/ createGlassIcon("shrink", [["path",{"d":"M15 15l6 6"},0],["path",{"d":"M15 15v4.8"},0],["path",{"d":"M15 15h4.8"},0],["path",{"d":"M9 19.8V15"},0],["path",{"d":"M9 15H4.2"},0],["path",{"d":"M9 15l-6 6"},0],["path",{"d":"M15 4.2V9"},0],["path",{"d":"M15 9h4.8"},0],["path",{"d":"M15 9l6 -6"},0],["path",{"d":"M9 4.2V9"},0],["path",{"d":"M9 9H4.2"},0],["path",{"d":"M9 9L3 3"},0]]);
export default GlassShrink;
