// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "sigma"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSigma = /*#__PURE__*/ createGlassIcon("sigma", [["path",{"d":"M18 7V5a1 1 0 0 0 -1 -1H6.5a0.5 0.5 0 0 0 -0.4 0.8l4.5 6a2 2 0 0 1 0 2.4l-4.5 6a0.5 0.5 0 0 0 0.4 0.8H17a1 1 0 0 0 1 -1v-2"},0]]);
export default GlassSigma;
