// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "signpost-big"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSignpostBig = /*#__PURE__*/ createGlassIcon("signpost-big", [[["M10 9L4 9L2 7L4 5L10 5Z",1],["M14 5L20 5L22 7L20 9L14 9Z",1]],[["M10 22L10 4A2 2 0 1 1 14 4L14 22",0],["M8 22L16 22",0]],[20.4,6.6,4.75],0]);
export default GlassSignpostBig;
