// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "signpost"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSignpost = /*#__PURE__*/ createGlassIcon("signpost", [["path",{"d":"M12 13v8"},0],["path",{"d":"M12 3v3"},0],["path",{"d":"M2.354 10.354a1.207 1.207 0 0 1 0 -1.708l2.06 -2.06A2 2 0 0 1 5.828 6h12.344a2 2 0 0 1 1.414 0.586l2.06 2.06a1.207 1.207 0 0 1 0 1.708l-2.06 2.06a2 2 0 0 1 -1.414 0.586H5.828a2 2 0 0 1 -1.414 -0.586z"},1]]);
export default GlassSignpost;
