// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "signature"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSignature = /*#__PURE__*/ createGlassIcon("signature", [["path",{"d":"M21 17l-2.156 -1.868A0.5 0.5 0 0 0 18 15.5v0.5a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1c0 -2.545 -3.991 -3.97 -8.5 -4a1 1 0 0 0 0 5c4.153 0 4.745 -11.295 5.708 -13.5a2.5 2.5 0 1 1 3.31 3.284"},0],["path",{"d":"M3 21h18"},0]]);
export default GlassSignature;
