// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "smartphone-nfc"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSmartphoneNfc = /*#__PURE__*/ createGlassIcon("smartphone-nfc", [["rect",{"width":"7","height":"12","x":"2","y":"6","rx":"1"},1],["path",{"d":"M13 8.32a7.43 7.43 0 0 1 0 7.36"},0],["path",{"d":"M16.46 6.21a11.76 11.76 0 0 1 0 11.58"},0],["path",{"d":"M19.91 4.1a15.91 15.91 0 0 1 0.01 15.8"},0]]);
export default GlassSmartphoneNfc;
