// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "face-slightly-smiling-plus" (alias of "smile-plus")
import { createGlassIcon } from '../createGlassIcon';

export const GlassSmilePlus = /*#__PURE__*/ createGlassIcon("smile-plus", [[["M13.267 2.08A10 10 0 1 0 21.92 10.733Z",1]],[["M15 10L15 9",1],["M16 5L22 5",0],["M16.472 15A6 6 0 0 1 7.529 15",1],["M19 2L19 8",0],["M9 10L9 9",1]],[20.38,3.62,4.75],0]);
export default GlassSmilePlus;
