// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "soap-dispenser-droplet"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSoapDispenserDroplet = /*#__PURE__*/ createGlassIcon("soap-dispenser-droplet", [["path",{"d":"M10.5 2v4"},0],["path",{"d":"M14 2H7a2 2 0 0 0 -2 2"},0],["path",{"d":"M19.29 14.76A6.67 6.67 0 0 1 17 11a6.6 6.6 0 0 1 -2.29 3.76c-1.15 0.92 -1.71 2.04 -1.71 3.19c0 2.22 1.8 4.05 4 4.05s4 -1.83 4 -4.05c0 -1.16 -0.57 -2.26 -1.71 -3.19"},1],["path",{"d":"M9.607 21H6a2 2 0 0 1 -2 -2v-7a2 2 0 0 1 2 -2h7V7a1 1 0 0 0 -1 -1H9a1 1 0 0 0 -1 1v3"},0]]);
export default GlassSoapDispenserDroplet;
