// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "sofa"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSofa = /*#__PURE__*/ createGlassIcon("sofa", [["path",{"d":"M20 9V6a2 2 0 0 0 -2 -2H6a2 2 0 0 0 -2 2v3"},0],["path",{"d":"M2 16a2 2 0 0 0 2 2h16a2 2 0 0 0 2 -2v-5a2 2 0 0 0 -4 0v1.5a0.5 0.5 0 0 1 -0.5 0.5h-11a0.5 0.5 0 0 1 -0.5 -0.5V11a2 2 0 0 0 -4 0z"},1],["path",{"d":"M4 18v2"},0],["path",{"d":"M20 18v2"},0],["path",{"d":"M12 4v9"},0]]);
export default GlassSofa;
