// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "soup"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSoup = /*#__PURE__*/ createGlassIcon("soup", [["path",{"d":"M12 21a9 9 0 0 0 9 -9H3a9 9 0 0 0 9 9Z"},1],["path",{"d":"M7 21h10"},0],["path",{"d":"M19.5 12L22 6"},0],["path",{"d":"M16.25 3c0.27 0.1 0.8 0.53 0.75 1.36c-0.06 0.83 -0.93 1.2 -1 2.02c-0.05 0.78 0.34 1.24 0.73 1.62"},0],["path",{"d":"M11.25 3c0.27 0.1 0.8 0.53 0.74 1.36c-0.05 0.83 -0.93 1.2 -0.98 2.02c-0.06 0.78 0.33 1.24 0.72 1.62"},0],["path",{"d":"M6.25 3c0.27 0.1 0.8 0.53 0.75 1.36c-0.06 0.83 -0.93 1.2 -1 2.02c-0.05 0.78 0.34 1.24 0.74 1.62"},0]]);
export default GlassSoup;
