// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "space"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSpace = /*#__PURE__*/ createGlassIcon("space", [["path",{"d":"M22 17v1c0 0.5 -0.5 1 -1 1H3c-0.5 0 -1 -0.5 -1 -1v-1"},0]]);
export default GlassSpace;
