// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "spray-can"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSprayCan = /*#__PURE__*/ createGlassIcon("spray-can", [["path",{"d":"M3 3h0.01"},0],["path",{"d":"M7 5h0.01"},0],["path",{"d":"M11 7h0.01"},0],["path",{"d":"M3 7h0.01"},0],["path",{"d":"M7 9h0.01"},0],["path",{"d":"M3 11h0.01"},0],["rect",{"width":"4","height":"4","x":"15","y":"5"},1],["path",{"d":"M19 9l2 2v10c0 0.6 -0.4 1 -1 1h-6c-0.6 0 -1 -0.4 -1 -1V11l2 -2"},0],["path",{"d":"M13 14l8 -2"},0],["path",{"d":"M13 19l8 -2"},0]]);
export default GlassSprayCan;
