// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-pause"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquarePause = /*#__PURE__*/ createGlassIcon("square-pause", [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1],["line",{"x1":"10","x2":"10","y1":"15","y2":"9"},0],["line",{"x1":"14","x2":"14","y1":"15","y2":"9"},0]]);
export default GlassSquarePause;
