// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-arrow-up"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareArrowUp = /*#__PURE__*/ createGlassIcon("square-arrow-up", [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1],["path",{"d":"M16 12l-4 -4l-4 4"},0],["path",{"d":"M12 16V8"},0]]);
export default GlassSquareArrowUp;
