// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-arrow-out-up-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareArrowOutUpLeft = /*#__PURE__*/ createGlassIcon("square-arrow-out-up-left", [[["M13 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 13Z",1]],[["M3 3L12 12",0],["M3 9L3 3L9 3",0]],[19.4,4.6,4.75],0]);
export default GlassSquareArrowOutUpLeft;
