// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-dot"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareDot = /*#__PURE__*/ createGlassIcon("square-dot", [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1],["circle",{"cx":"12","cy":"12","r":"1"},1]]);
export default GlassSquareDot;
