// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquare = /*#__PURE__*/ createGlassIcon("square", [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1]]);
export default GlassSquare;
