// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-library"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareLibrary = /*#__PURE__*/ createGlassIcon("square-library", [[["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z",1]],[["M7 7L7 17",1],["M11 7L11 17",1],["M15 7L17 17",1]],[19.4,4.6,4.75],0]);
export default GlassSquareLibrary;
