// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-code"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareCode = /*#__PURE__*/ createGlassIcon("square-code", [["path",{"d":"M10 9l-3 3l3 3"},0],["path",{"d":"M14 15l3 -3l-3 -3"},0],["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2"},1]]);
export default GlassSquareCode;
