// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-chevron-right"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareChevronRight = /*#__PURE__*/ createGlassIcon("square-chevron-right", [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1],["path",{"d":"M10 8l4 4l-4 4"},0]]);
export default GlassSquareChevronRight;
