// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-arrow-up-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareArrowUpLeft = /*#__PURE__*/ createGlassIcon("square-arrow-up-left", [["path",{"d":"M15 15L9 9"},0],["path",{"d":"M9 15V9h6"},0],["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2"},1]]);
export default GlassSquareArrowUpLeft;
