// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-slash"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareSlash = /*#__PURE__*/ createGlassIcon("square-slash", [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1],["line",{"x1":"9","x2":"15","y1":"15","y2":"9"},0]]);
export default GlassSquareSlash;
