// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-dashed-top-solid"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareDashedTopSolid = /*#__PURE__*/ createGlassIcon("square-dashed-top-solid", [["path",{"d":"M14 21h1"},0],["path",{"d":"M21 14v1"},0],["path",{"d":"M21 19a2 2 0 0 1 -2 2"},0],["path",{"d":"M21 9v1"},0],["path",{"d":"M3 14v1"},0],["path",{"d":"M3 5a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2"},0],["path",{"d":"M3 9v1"},0],["path",{"d":"M5 21a2 2 0 0 1 -2 -2"},0],["path",{"d":"M9 21h1"},0]]);
export default GlassSquareDashedTopSolid;
