// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-user-round"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareUserRound = /*#__PURE__*/ createGlassIcon("square-user-round", [["path",{"d":"M18 21a6 6 0 0 0 -12 0"},0],["circle",{"cx":"12","cy":"11","r":"4"},1],["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"},1]]);
export default GlassSquareUserRound;
