// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-mouse-pointer"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareMousePointer = /*#__PURE__*/ createGlassIcon("square-mouse-pointer", [["path",{"d":"M12.034 12.681a0.498 0.498 0 0 1 0.647 -0.647l9 3.5a0.5 0.5 0 0 1 -0.033 0.943l-3.444 1.068a1 1 0 0 0 -0.66 0.66l-1.067 3.443a0.5 0.5 0 0 1 -0.943 0.033z"},1],["path",{"d":"M21 11V5a2 2 0 0 0 -2 -2H5a2 2 0 0 0 -2 2v14a2 2 0 0 0 2 2h6"},0]]);
export default GlassSquareMousePointer;
