// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-round-corner"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareRoundCorner = /*#__PURE__*/ createGlassIcon("square-round-corner", [["path",{"d":"M21 11a8 8 0 0 0 -8 -8"},0],["path",{"d":"M21 15v4a2 2 0 0 1 -2 2H5a2 2 0 0 1 -2 -2V5a2 2 0 0 1 2 -2h4"},0]]);
export default GlassSquareRoundCorner;
