// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-arrow-out-down-left"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquareArrowOutDownLeft = /*#__PURE__*/ createGlassIcon("square-arrow-out-down-left", [["path",{"d":"M13 21h6a2 2 0 0 0 2 -2V5a2 2 0 0 0 -2 -2H5a2 2 0 0 0 -2 2v6"},0],["path",{"d":"M3 21l9 -9"},0],["path",{"d":"M9 21H3v-6"},0]]);
export default GlassSquareArrowOutDownLeft;
