// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "squircle-dashed"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquircleDashed = /*#__PURE__*/ createGlassIcon("squircle-dashed", [[["M13.77 3.043A34 34 0 0 0 10.23 3.043",0],["M13.771 20.956A33 33 0 0 1 10.23 20.957",0],["M20.18 17.74C19.67 18.89 18.89 19.67 17.741 20.18",0],["M20.18 6.259C19.67 5.111 18.889 4.33 17.74 3.821",0],["M20.957 10.23A33 33 0 0 1 20.957 13.77",0],["M3.043 10.23A34 34 0 0 0 3.044 13.771",0],["M6.26 20.179C5.11 19.671 4.33 18.889 3.82 17.741",0],["M6.26 3.82C5.111 4.33 4.33 5.111 3.82 6.26",0]],[],[19.405,4.597,4.75],1]);
export default GlassSquircleDashed;
