// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "squircle"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSquircle = /*#__PURE__*/ createGlassIcon("squircle", [[["M12 3C19.2 3 21 4.8 21 12C21 19.2 19.2 21 12 21C4.8 21 3 19.2 3 12C3 4.8 4.8 3 12 3",1]],[],[19.4,4.6,4.75],0]);
export default GlassSquircle;
