// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "sticker"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSticker = /*#__PURE__*/ createGlassIcon("sticker", [["path",{"d":"M21 9a2.4 2.4 0 0 0 -0.706 -1.706l-3.588 -3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0 -2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2 -2z"},1],["path",{"d":"M15 3v5a1 1 0 0 0 1 1h5"},0],["path",{"d":"M8 13h0.01"},0],["path",{"d":"M16 13h0.01"},0],["path",{"d":"M10 16s0.8 1 2 1c1.3 0 2 -1 2 -1"},0]]);
export default GlassSticker;
