// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "sun"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSun = /*#__PURE__*/ createGlassIcon("sun", [["circle",{"cx":"12","cy":"12","r":"4"},1],["path",{"d":"M12 2v2"},0],["path",{"d":"M12 20v2"},0],["path",{"d":"M4.93 4.93l1.41 1.41"},0],["path",{"d":"M17.66 17.66l1.41 1.41"},0],["path",{"d":"M2 12h2"},0],["path",{"d":"M20 12h2"},0],["path",{"d":"M6.34 17.66l-1.41 1.41"},0],["path",{"d":"M19.07 4.93l-1.41 1.41"},0]]);
export default GlassSun;
