// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "swiss-franc"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSwissFranc = /*#__PURE__*/ createGlassIcon("swiss-franc", [[["M10 21L10 3L18 3",0],["M6 16L15 16",0],["M10 9.5L17 9.5",0]],[],[16.4,4.6,4.75],1]);
export default GlassSwissFranc;
