// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "swords"
import { createGlassIcon } from '../createGlassIcon';

export const GlassSwords = /*#__PURE__*/ createGlassIcon("swords", [["path",{"d":"M13 19l6 -6"},0],["path",{"d":"M14.5 17.5L3.586 6.586A2 2 0 0 1 3 5.172V3h2.172a2 2 0 0 1 1.414 0.586L17.5 14.5"},0],["path",{"d":"M14.828 6.172l2.586 -2.586A2 2 0 0 1 18.828 3H21v2.172a2 2 0 0 1 -0.586 1.414l-2.586 2.586"},0],["path",{"d":"M16 16l4 4"},0],["path",{"d":"M19 21l2 -2"},0],["path",{"d":"M5 14l4 4"},0],["path",{"d":"M5 21l-2 -2"},0],["path",{"d":"M7.5 16.5L4 20"},0]]);
export default GlassSwords;
