// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tablet"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTablet = /*#__PURE__*/ createGlassIcon("tablet", [["rect",{"width":"16","height":"20","x":"4","y":"2","rx":"2","ry":"2"},1],["line",{"x1":"12","x2":"12.01","y1":"18","y2":"18"},0]]);
export default GlassTablet;
