// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tablet-smartphone"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTabletSmartphone = /*#__PURE__*/ createGlassIcon("tablet-smartphone", [["rect",{"width":"10","height":"14","x":"3","y":"8","rx":"2"},1],["path",{"d":"M5 4a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v16a2 2 0 0 1 -2 2h-2.4"},0],["path",{"d":"M8 18h0.01"},0]]);
export default GlassTabletSmartphone;
