// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tally-5"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTally5 = /*#__PURE__*/ createGlassIcon("tally-5", [["path",{"d":"M4 4v16"},0],["path",{"d":"M9 4v16"},0],["path",{"d":"M14 4v16"},0],["path",{"d":"M19 4v16"},0],["path",{"d":"M22 6L2 18"},0]]);
export default GlassTally5;
