// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tally-3"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTally3 = /*#__PURE__*/ createGlassIcon("tally-3", [["path",{"d":"M4 4v16"},0],["path",{"d":"M9 4v16"},0],["path",{"d":"M14 4v16"},0]]);
export default GlassTally3;
