// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tally-4"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTally4 = /*#__PURE__*/ createGlassIcon("tally-4", [[["M4 4L4 20",0],["M9 4L9 20",0],["M14 4L14 20",0],["M19 4L19 20",0]],[],[17.4,5.6,4.75],1]);
export default GlassTally4;
