// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tally-4"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTally4 = /*#__PURE__*/ createGlassIcon("tally-4", [["path",{"d":"M4 4v16"},0],["path",{"d":"M9 4v16"},0],["path",{"d":"M14 4v16"},0],["path",{"d":"M19 4v16"},0]]);
export default GlassTally4;
