// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "test-tubes"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTestTubes = /*#__PURE__*/ createGlassIcon("test-tubes", [[["M9 2L9 19.5A2.5 2.5 0 0 1 6.5 22A2.5 2.5 0 0 1 4 19.5L4 2Z",1],["M20 2L20 19.5A2.5 2.5 0 0 1 17.5 22A2.5 2.5 0 0 1 15 19.5L15 2Z",1],["M3 2L10 2",0],["M14 2L21 2",0]],[["M9 16L4 16",1],["M20 16L15 16",1]],[19.4,3.6,4.75],0]);
export default GlassTestTubes;
