// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "test-tubes"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTestTubes = /*#__PURE__*/ createGlassIcon("test-tubes", [["path",{"d":"M9 2v17.5A2.5 2.5 0 0 1 6.5 22A2.5 2.5 0 0 1 4 19.5V2"},0],["path",{"d":"M20 2v17.5a2.5 2.5 0 0 1 -2.5 2.5a2.5 2.5 0 0 1 -2.5 -2.5V2"},0],["path",{"d":"M3 2h7"},0],["path",{"d":"M14 2h7"},0],["path",{"d":"M9 16H4"},0],["path",{"d":"M20 16h-5"},0]]);
export default GlassTestTubes;
