// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "test-tube-diagonal"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTestTubeDiagonal = /*#__PURE__*/ createGlassIcon("test-tube-diagonal", [[["M21 7L6.82 21.18A2.83 2.83 0 0 1 2.83 21.17A2.83 2.83 0 0 1 2.83 17.17L17 3Z",1],["M16 2L22 8",0]],[["M12 16L4 16",1]],[20.4,3.6,4.75],0]);
export default GlassTestTubeDiagonal;
