// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "text-cursor"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTextCursor = /*#__PURE__*/ createGlassIcon("text-cursor", [["path",{"d":"M17 22h-1a4 4 0 0 1 -4 -4V6a4 4 0 0 1 4 -4h1"},0],["path",{"d":"M7 22h1a4 4 0 0 0 4 -4"},0],["path",{"d":"M7 2h1a4 4 0 0 1 4 4"},0]]);
export default GlassTextCursor;
