// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "thermometer-snowflake"
import { createGlassIcon } from '../createGlassIcon';

export const GlassThermometerSnowflake = /*#__PURE__*/ createGlassIcon("thermometer-snowflake", [["path",{"d":"M10 20l-1.25 -2.5L6 18"},0],["path",{"d":"M10 4L8.75 6.5L6 6"},0],["path",{"d":"M10.585 15H10"},0],["path",{"d":"M2 12h6.5L10 9"},0],["path",{"d":"M20 14.54a4 4 0 1 1 -4 0V4a2 2 0 0 1 4 0z"},1],["path",{"d":"M4 10l1.5 2L4 14"},0],["path",{"d":"M7 21l3 -6l-1.5 -3"},0],["path",{"d":"M7 3l3 6h2"},0]]);
export default GlassThermometerSnowflake;
