// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ticket-check"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTicketCheck = /*#__PURE__*/ createGlassIcon("ticket-check", [["path",{"d":"M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2 -2v-2a3 3 0 0 1 0 -6V7a2 2 0 0 0 -2 -2H4a2 2 0 0 0 -2 2Z"},1],["path",{"d":"M9 12l2 2l4 -4"},0]]);
export default GlassTicketCheck;
