// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ticket-check"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTicketCheck = /*#__PURE__*/ createGlassIcon("ticket-check", [[["M2 9A3 3 0 0 1 2 15L2 17A2 2 0 0 0 4 19L20 19A2 2 0 0 0 22 17L22 15A3 3 0 0 1 22 9L22 7A2 2 0 0 0 20 5L4 5A2 2 0 0 0 2 7Z",1]],[["M9 12L11 14L15 10",1]],[20.4,6.6,4.75],0]);
export default GlassTicketCheck;
