// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "touchpad"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTouchpad = /*#__PURE__*/ createGlassIcon("touchpad", [["rect",{"width":"20","height":"16","x":"2","y":"4","rx":"2"},1],["path",{"d":"M2 14h20"},0],["path",{"d":"M12 20v-6"},0]]);
export default GlassTouchpad;
