// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "traffic-cone"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTrafficCone = /*#__PURE__*/ createGlassIcon("traffic-cone", [["path",{"d":"M16.05 10.966a5 2.5 0 0 1 -8.1 0"},0],["path",{"d":"M16.923 14.049l4.48 2.04a1 1 0 0 1 0.001 1.831l-8.574 3.9a2 2 0 0 1 -1.66 0l-8.574 -3.91a1 1 0 0 1 0 -1.83l4.484 -2.04"},0],["path",{"d":"M16.949 14.14a5 2.5 0 1 1 -9.9 0L10.063 3.5a2 2 0 0 1 3.874 0z"},1],["path",{"d":"M9.194 6.57a5 2.5 0 0 0 5.61 0"},0]]);
export default GlassTrafficCone;
