// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "transgender"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTransgender = /*#__PURE__*/ createGlassIcon("transgender", [["path",{"d":"M12 16v6"},0],["path",{"d":"M14 20h-4"},0],["path",{"d":"M18 2h4v4"},0],["path",{"d":"M2 2l7.17 7.17"},0],["path",{"d":"M2 5.355V2h3.357"},0],["path",{"d":"M22 2l-7.17 7.17"},0],["path",{"d":"M8 5L5 8"},0],["circle",{"cx":"12","cy":"12","r":"4"},1]]);
export default GlassTransgender;
