// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tree-pine"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTreePine = /*#__PURE__*/ createGlassIcon("tree-pine", [["path",{"d":"M17 14l3 3.3a1 1 0 0 1 -0.7 1.7H4.7a1 1 0 0 1 -0.7 -1.7L7 14h-0.3a1 1 0 0 1 -0.7 -1.7L9 9h-0.2A1 1 0 0 1 8 7.3L12 3l4 4.3a1 1 0 0 1 -0.8 1.7H15l3 3.3a1 1 0 0 1 -0.7 1.7H17Z"},1],["path",{"d":"M12 22v-3"},0]]);
export default GlassTreePine;
