// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "triangle-dashed"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTriangleDashed = /*#__PURE__*/ createGlassIcon("triangle-dashed", [["path",{"d":"M10.17 4.193a2 2 0 0 1 3.666 0.013"},0],["path",{"d":"M14 21h2"},0],["path",{"d":"M15.874 7.743l1 1.732"},0],["path",{"d":"M18.849 12.952l1 1.732"},0],["path",{"d":"M21.824 18.18a2 2 0 0 1 -1.835 2.824"},0],["path",{"d":"M4.024 21a2 2 0 0 1 -1.839 -2.839"},0],["path",{"d":"M5.136 12.952l-1 1.732"},0],["path",{"d":"M8 21h2"},0],["path",{"d":"M8.102 7.743l-1 1.732"},0]]);
export default GlassTriangleDashed;
