// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "triangle"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTriangle = /*#__PURE__*/ createGlassIcon("triangle", [[["M13.73 4A2 2 0 0 0 10.27 4L2.27 18A2 2 0 0 0 4 21L20 21A2 2 0 0 0 21.73 18Z",1]],[],[20.396,4.613,4.75],0]);
export default GlassTriangle;
