// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "trophy"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTrophy = /*#__PURE__*/ createGlassIcon("trophy", [["path",{"d":"M10 14.66V17a1 1 0 0 1 -1 1a2 2 0 0 0 -2 2v2"},0],["path",{"d":"M14 14.66V17a1 1 0 0 0 1 1a2 2 0 0 1 2 2v2"},0],["path",{"d":"M17.916 10H19.5A2.5 2.5 0 0 0 22 7.5V5a1 1 0 0 0 -1 -1h-3"},0],["path",{"d":"M4 22h16"},0],["path",{"d":"M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0 -1 -1H7a1 1 0 0 0 -1 1z"},1],["path",{"d":"M6.084 10H4.5A2.5 2.5 0 0 1 2 7.5V5a1 1 0 0 1 1 -1h3"},0]]);
export default GlassTrophy;
