// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "trophy"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTrophy = /*#__PURE__*/ createGlassIcon("trophy", [[["M6 9A6 6 0 0 0 18 9L18 3A1 1 0 0 0 17 2L7 2A1 1 0 0 0 6 3Z",1]],[["M10 14.66L10 17A1 1 0 0 1 9 18A2 2 0 0 0 7 20L7 22",0],["M14 14.66L14 17A1 1 0 0 0 15 18A2 2 0 0 1 17 20L17 22",0],["M17.916 10L19.5 10A2.5 2.5 0 0 0 22 7.5L22 5A1 1 0 0 0 21 4L18 4",0],["M4 22L20 22",0],["M6.084 10L4.5 10A2.5 2.5 0 0 1 2 7.5L2 5A1 1 0 0 1 3 4L6 4",0]],[16.832,3.168,4.03],0]);
export default GlassTrophy;
