// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "truck-electric"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTruckElectric = /*#__PURE__*/ createGlassIcon("truck-electric", [[["M19 19L21 19A1 1 0 0 0 22 18L22 14.35A1 1 0 0 0 21.78 13.73L18.3 9.38A1 1 0 0 0 17.52 9L14 9Z",1]],[["M14 19L14 7A2 2 0 0 0 12 5L9 5",0],["M15 19L9 19",0],["M2 13L2 18A1 1 0 0 0 3 19L5 19",0],["M4 3L2.15 5.15A0.495 0.495 0 0 0 2.5 6.01L4.65 6.01A0.47 0.47 0 0 1 5 6.87L3 9.02",0],["M15 19A2 2 0 1 0 19 19A2 2 0 1 0 15 19Z",0],["M5 19A2 2 0 1 0 9 19A2 2 0 1 0 5 19Z",0]],[21.3,9.7,3.25],0]);
export default GlassTruckElectric;
