// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "turntable"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTurntable = /*#__PURE__*/ createGlassIcon("turntable", [["path",{"d":"M10 12.01h0.01"},0],["path",{"d":"M18 8v4a8 8 0 0 1 -1.07 4"},0],["circle",{"cx":"10","cy":"12","r":"4"},1],["rect",{"x":"2","y":"4","width":"20","height":"16","rx":"2"},1]]);
export default GlassTurntable;
