// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "turtle"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTurtle = /*#__PURE__*/ createGlassIcon("turtle", [["path",{"d":"M12 10l2 4v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-3a8 8 0 1 0 -16 0v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-3l2 -4h4Z"},1],["path",{"d":"M4.82 7.9L8 10"},0],["path",{"d":"M15.18 7.9L12 10"},0],["path",{"d":"M16.93 10H20a2 2 0 0 1 0 4H2"},0]]);
export default GlassTurtle;
