// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tv-minimal-play"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTvMinimalPlay = /*#__PURE__*/ createGlassIcon("tv-minimal-play", [["path",{"d":"M15.033 9.44a0.647 0.647 0 0 1 0 1.12l-4.065 2.352a0.645 0.645 0 0 1 -0.968 -0.56V7.648a0.645 0.645 0 0 1 0.967 -0.56z"},1],["path",{"d":"M7 21h10"},0],["rect",{"width":"20","height":"14","x":"2","y":"3","rx":"2"},1]]);
export default GlassTvMinimalPlay;
