// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tv"
import { createGlassIcon } from '../createGlassIcon';

export const GlassTv = /*#__PURE__*/ createGlassIcon("tv", [["path",{"d":"M17 2l-5 5l-5 -5"},0],["rect",{"width":"20","height":"15","x":"2","y":"7","rx":"2"},1]]);
export default GlassTv;
