// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "type"
import { createGlassIcon } from '../createGlassIcon';

export const GlassType = /*#__PURE__*/ createGlassIcon("type", [["path",{"d":"M12 4v16"},0],["path",{"d":"M4 7V5a1 1 0 0 1 1 -1h14a1 1 0 0 1 1 1v2"},0],["path",{"d":"M9 20h6"},0]]);
export default GlassType;
