// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "undo-dot"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUndoDot = /*#__PURE__*/ createGlassIcon("undo-dot", [["path",{"d":"M21 17a9 9 0 0 0 -15 -6.7L3 13"},0],["path",{"d":"M3 7v6h6"},0],["circle",{"cx":"12","cy":"17","r":"1"},1]]);
export default GlassUndoDot;
