// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "undo"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUndo = /*#__PURE__*/ createGlassIcon("undo", [[["M3 7L3 13L9 13",0],["M21 17A9 9 0 0 0 12 8A9 9 0 0 0 6 10.3L3 13",0]],[],[19.4,8.6,4.75],1]);
export default GlassUndo;
