// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "undo"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUndo = /*#__PURE__*/ createGlassIcon("undo", [["path",{"d":"M3 7v6h6"},0],["path",{"d":"M21 17a9 9 0 0 0 -9 -9a9 9 0 0 0 -6 2.3L3 13"},0]]);
export default GlassUndo;
