// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "unfold-vertical"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUnfoldVertical = /*#__PURE__*/ createGlassIcon("unfold-vertical", [[["M12 22L12 16",0],["M12 8L12 2",0],["M4 12L2 12",0],["M10 12L8 12",0],["M16 12L14 12",0],["M22 12L20 12",0],["M15 19L12 22L9 19",0],["M15 5L12 2L9 5",0]],[],[20.4,3.6,4.75],1]);
export default GlassUnfoldVertical;
