// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "unfold-horizontal"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUnfoldHorizontal = /*#__PURE__*/ createGlassIcon("unfold-horizontal", [["path",{"d":"M16 12h6"},0],["path",{"d":"M8 12H2"},0],["path",{"d":"M12 2v2"},0],["path",{"d":"M12 8v2"},0],["path",{"d":"M12 14v2"},0],["path",{"d":"M12 20v2"},0],["path",{"d":"M19 15l3 -3l-3 -3"},0],["path",{"d":"M5 9l-3 3l3 3"},0]]);
export default GlassUnfoldHorizontal;
