// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "university"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUniversity = /*#__PURE__*/ createGlassIcon("university", [["path",{"d":"M14 21v-3a2 2 0 0 0 -4 0v3"},0],["path",{"d":"M18 12h0.01"},0],["path",{"d":"M18 16h0.01"},0],["path",{"d":"M22 7a1 1 0 0 0 -1 -1h-2a2 2 0 0 1 -1.143 -0.359L13.143 2.36a2 2 0 0 0 -2.286 -0.001L6.143 5.64A2 2 0 0 1 5 6H3a1 1 0 0 0 -1 1v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2 -2z"},1],["path",{"d":"M6 12h0.01"},0],["path",{"d":"M6 16h0.01"},0],["circle",{"cx":"12","cy":"10","r":"2"},1]]);
export default GlassUniversity;
