// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "unlink"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUnlink = /*#__PURE__*/ createGlassIcon("unlink", [["path",{"d":"M18.84 12.25l1.72 -1.71h-0.02a5.004 5.004 0 0 0 -0.12 -7.07a5.006 5.006 0 0 0 -6.95 0l-1.72 1.71"},0],["path",{"d":"M5.17 11.75l-1.71 1.71a5.004 5.004 0 0 0 0.12 7.07a5.006 5.006 0 0 0 6.95 0l1.71 -1.71"},0],["line",{"x1":"8","x2":"8","y1":"2","y2":"5"},0],["line",{"x1":"2","x2":"5","y1":"8","y2":"8"},0],["line",{"x1":"16","x2":"16","y1":"19","y2":"22"},0],["line",{"x1":"19","x2":"22","y1":"16","y2":"16"},0]]);
export default GlassUnlink;
