// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "upload"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUpload = /*#__PURE__*/ createGlassIcon("upload", [["path",{"d":"M12 3v12"},0],["path",{"d":"M17 8l-5 -5l-5 5"},0],["path",{"d":"M21 15v4a2 2 0 0 1 -2 2H5a2 2 0 0 1 -2 -2v-4"},0]]);
export default GlassUpload;
