// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "users"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUsers = /*#__PURE__*/ createGlassIcon("users", [["path",{"d":"M16 21v-2a4 4 0 0 0 -4 -4H6a4 4 0 0 0 -4 4v2"},0],["path",{"d":"M16 3.128a4 4 0 0 1 0 7.744"},0],["path",{"d":"M22 21v-2a4 4 0 0 0 -3 -3.87"},0],["circle",{"cx":"9","cy":"7","r":"4"},1]]);
export default GlassUsers;
