// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "user-round-plus"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUserRoundPlus = /*#__PURE__*/ createGlassIcon("user-round-plus", [[["M5 8A5 5 0 1 0 15 8A5 5 0 1 0 5 8Z",1]],[["M2 21A8 8 0 0 1 15.292 15",0],["M19 16L19 22",0],["M22 19L16 19",0]],[14.3,3.7,3.25],0]);
export default GlassUserRoundPlus;
