// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "user-search"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUserSearch = /*#__PURE__*/ createGlassIcon("user-search", [["circle",{"cx":"10","cy":"7","r":"4"},1],["path",{"d":"M10.3 15H7a4 4 0 0 0 -4 4v2"},0],["circle",{"cx":"17","cy":"17","r":"3"},1],["path",{"d":"M21 21l-1.9 -1.9"},0]]);
export default GlassUserSearch;
