// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "user-check"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUserCheck = /*#__PURE__*/ createGlassIcon("user-check", [["path",{"d":"M16 11l2 2l4 -4"},0],["path",{"d":"M16 21v-2a4 4 0 0 0 -4 -4H6a4 4 0 0 0 -4 4v2"},0],["circle",{"cx":"9","cy":"7","r":"4"},1]]);
export default GlassUserCheck;
