// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "user-cog"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUserCog = /*#__PURE__*/ createGlassIcon("user-cog", [["path",{"d":"M10 15H6a4 4 0 0 0 -4 4v2"},0],["path",{"d":"M14.305 16.53l0.923 -0.382"},0],["path",{"d":"M15.228 13.852l-0.923 -0.383"},0],["path",{"d":"M16.852 12.228l-0.383 -0.923"},0],["path",{"d":"M16.852 17.772l-0.383 0.924"},0],["path",{"d":"M19.148 12.228l0.383 -0.923"},0],["path",{"d":"M19.53 18.696l-0.382 -0.924"},0],["path",{"d":"M20.772 13.852l0.924 -0.383"},0],["path",{"d":"M20.772 16.148l0.924 0.383"},0],["circle",{"cx":"18","cy":"15","r":"3"},1],["circle",{"cx":"9","cy":"7","r":"4"},1]]);
export default GlassUserCog;
