// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "user"
import { createGlassIcon } from '../createGlassIcon';

export const GlassUser = /*#__PURE__*/ createGlassIcon("user", [["path",{"d":"M19 21v-2a4 4 0 0 0 -4 -4H9a4 4 0 0 0 -4 4v2"},0],["circle",{"cx":"12","cy":"7","r":"4"},1]]);
export default GlassUser;
