// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "vibrate-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassVibrateOff = /*#__PURE__*/ createGlassIcon("vibrate-off", [["path",{"d":"M2 8l2 2l-2 2l2 2l-2 2"},0],["path",{"d":"M22 8l-2 2l2 2l-2 2l2 2"},0],["path",{"d":"M8 8v10c0 0.55 0.45 1 1 1h6c0.55 0 1 -0.45 1 -1v-2"},0],["path",{"d":"M16 10.34V6c0 -0.55 -0.45 -1 -1 -1h-4.34"},0],["line",{"x1":"2","x2":"22","y1":"2","y2":"22"},0]]);
export default GlassVibrateOff;
