// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "vibrate"
import { createGlassIcon } from '../createGlassIcon';

export const GlassVibrate = /*#__PURE__*/ createGlassIcon("vibrate", [["path",{"d":"M2 8l2 2l-2 2l2 2l-2 2"},0],["path",{"d":"M22 8l-2 2l2 2l-2 2l2 2"},0],["rect",{"width":"8","height":"14","x":"8","y":"5","rx":"1"},1]]);
export default GlassVibrate;
