// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "view"
import { createGlassIcon } from '../createGlassIcon';

export const GlassView = /*#__PURE__*/ createGlassIcon("view", [["path",{"d":"M21 17v2a2 2 0 0 1 -2 2H5a2 2 0 0 1 -2 -2v-2"},0],["path",{"d":"M21 7V5a2 2 0 0 0 -2 -2H5a2 2 0 0 0 -2 2v2"},0],["circle",{"cx":"12","cy":"12","r":"1"},1],["path",{"d":"M18.944 12.33a1 1 0 0 0 0 -0.66a7.5 7.5 0 0 0 -13.888 0a1 1 0 0 0 0 0.66a7.5 7.5 0 0 0 13.888 0"},1]]);
export default GlassView;
