// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "voicemail"
import { createGlassIcon } from '../createGlassIcon';

export const GlassVoicemail = /*#__PURE__*/ createGlassIcon("voicemail", [[["M2 12A4 4 0 1 0 10 12A4 4 0 1 0 2 12Z",1],["M14 12A4 4 0 1 0 22 12A4 4 0 1 0 14 12Z",1]],[["M6 16L18 16",1]],[20.4,9.6,4.75],0]);
export default GlassVoicemail;
