// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "volume-2"
import { createGlassIcon } from '../createGlassIcon';

export const GlassVolume2 = /*#__PURE__*/ createGlassIcon("volume-2", [["path",{"d":"M11 4.702a0.705 0.705 0 0 0 -1.203 -0.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 0.997 0.413l3.383 3.384A0.705 0.705 0 0 0 11 19.298z"},1],["path",{"d":"M16 9a5 5 0 0 1 0 6"},0],["path",{"d":"M19.364 18.364a9 9 0 0 0 0 -12.728"},0]]);
export default GlassVolume2;
