// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "wallet-minimal"
import { createGlassIcon } from '../createGlassIcon';

export const GlassWalletMinimal = /*#__PURE__*/ createGlassIcon("wallet-minimal", [[["M17 14L17.01 14",0],["M7 7L19 7A2 2 0 0 1 21 9L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3L19 3",0]],[],[19.4,4.6,4.75],1]);
export default GlassWalletMinimal;
