// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "waypoints"
import { createGlassIcon } from '../createGlassIcon';

export const GlassWaypoints = /*#__PURE__*/ createGlassIcon("waypoints", [["path",{"d":"M10.586 5.414l-5.172 5.172"},0],["path",{"d":"M18.586 13.414l-5.172 5.172"},0],["path",{"d":"M6 12h12"},0],["circle",{"cx":"12","cy":"20","r":"2"},1],["circle",{"cx":"12","cy":"4","r":"2"},1],["circle",{"cx":"20","cy":"12","r":"2"},1],["circle",{"cx":"4","cy":"12","r":"2"},1]]);
export default GlassWaypoints;
