// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "webhook"
import { createGlassIcon } from '../createGlassIcon';

export const GlassWebhook = /*#__PURE__*/ createGlassIcon("webhook", [["path",{"d":"M18 16.98h-5.99c-1.1 0 -1.95 0.94 -2.48 1.9A4 4 0 0 1 2 17c0.01 -0.7 0.2 -1.4 0.57 -2"},0],["path",{"d":"M6 17l3.13 -5.78c0.53 -0.97 0.1 -2.18 -0.5 -3.1a4 4 0 1 1 6.89 -4.06"},0],["path",{"d":"M12 6l3.13 5.73C15.66 12.7 16.9 13 18 13a4 4 0 0 1 0 8"},0]]);
export default GlassWebhook;
