// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "wine"
import { createGlassIcon } from '../createGlassIcon';

export const GlassWine = /*#__PURE__*/ createGlassIcon("wine", [["path",{"d":"M8 22h8"},0],["path",{"d":"M7 10h10"},0],["path",{"d":"M12 15v7"},0],["path",{"d":"M12 15a5 5 0 0 0 5 -5c0 -2 -0.5 -4 -2 -8H9c-1.5 4 -2 6 -2 8a5 5 0 0 0 5 5Z"},1]]);
export default GlassWine;
