// Generated by scripts/glass-icons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "wine-off"
import { createGlassIcon } from '../createGlassIcon';

export const GlassWineOff = /*#__PURE__*/ createGlassIcon("wine-off", [[["M8 22L16 22",0],["M7 10L10 10",0],["M17 10L15.657 10",0],["M12 15L12 22",0],["M7.307 7.307A12.33 12.33 0 0 0 7 10A5 5 0 0 0 14.391 14.391",0],["M8.638 2.981C8.75 2.668 8.872 2.34 9 2L15 2C16.5 6 17 8 17 10C17 10.407 16.95 10.809 16.855 11.198",0],["M2 2L22 22",0]],[],[20.4,3.6,4.75],1]);
export default GlassWineOff;
