// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "accessibility"
import { createSicon } from '../createSicon';

export const SiconAccessibility = /*#__PURE__*/ createSicon("accessibility", ["M15 4A1 1 0 1 0 17 4A1 1 0 1 0 15 4Z","M18 19L18.807 13.352A1 1 0 0 0 17.652 12.225L13 13","M5 8L7.471 5.529A1 1 0 0 1 8.657 5.358L12.536 7.474A1 1 0 0 1 12.886 8.911L11.14 11.5","M4.24 14.5A5 5 0 0 0 11.12 20.5","M13.76 17.5A5 5 0 0 0 6.88 11.5"]);
export default SiconAccessibility;
