// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "alarm-smoke"
import { createSicon } from '../createSicon';

export const SiconAlarmSmoke = /*#__PURE__*/ createSicon("alarm-smoke", [["M11 21C11 18.5 13 18.5 13 16","M16 21C16 18.5 18 18.5 18 16","M19 8L18.2 11A1.25 1.25 0 0 1 17 12L7 12A1.25 1.25 0 0 1 5.8 11L5 8","M21 3A1 1 0 0 1 22 4L22 6A2 2 0 0 1 20 8L4 8A2 2 0 0 1 2 6L2 4A1 1 0 0 1 3 3L21 3Z","M6 21C6 18.5 8 18.5 8 16"],"fffbf"]);
export default SiconAlarmSmoke;
