// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "align-start-vertical"
import { createSicon } from '../createSicon';

export const SiconAlignStartVertical = /*#__PURE__*/ createSicon("align-start-vertical", [["M8 14L13 14A2 2 0 0 1 15 16L15 18A2 2 0 0 1 13 20L8 20A2 2 0 0 1 6 18L6 16A2 2 0 0 1 8 14Z","M8 4L20 4A2 2 0 0 1 22 6L22 8A2 2 0 0 1 20 10L8 10A2 2 0 0 1 6 8L6 6A2 2 0 0 1 8 4Z","M2 2L2 22"],"bbf"]);
export default SiconAlignStartVertical;
