// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "text-align-center" (alias of "align-center")
import { createSicon } from '../createSicon';

export const SiconAlignCenter = /*#__PURE__*/ createSicon("align-center", ["M21 5L3 5","M17 12L7 12","M19 19L5 19"]);
export default SiconAlignCenter;
