// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "align-vertical-distribute-start"
import { createSicon } from '../createSicon';

export const SiconAlignVerticalDistributeStart = /*#__PURE__*/ createSicon("align-vertical-distribute-start", [["M7 14L17 14A2 2 0 0 1 19 16L19 18A2 2 0 0 1 17 20L7 20A2 2 0 0 1 5 18L5 16A2 2 0 0 1 7 14Z","M9 4L15 4A2 2 0 0 1 17 6L17 8A2 2 0 0 1 15 10L9 10A2 2 0 0 1 7 8L7 6A2 2 0 0 1 9 4Z","M2 14L22 14","M2 4L22 4"],"bbef"]);
export default SiconAlignVerticalDistributeStart;
