// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ambulance"
import { createSicon } from '../createSicon';

export const SiconAmbulance = /*#__PURE__*/ createSicon("ambulance", ["M10 10L6 10","M14 18L14 6A2 2 0 0 0 12 4L4 4A2 2 0 0 0 2 6L2 17A1 1 0 0 0 3 18L5 18","M19 18L21 18A1 1 0 0 0 22 17L22 13.72A1 1 0 0 0 21.316 12.772L19.393 12.131A1 1 0 0 1 18.815 11.629L17.276 8.553A1 1 0 0 0 16.382 8L14 8","M8 8L8 12","M9 18L15 18","M15 18A2 2 0 1 0 19 18A2 2 0 1 0 15 18Z","M5 18A2 2 0 1 0 9 18A2 2 0 1 0 5 18Z"]);
export default SiconAmbulance;
