// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "amphora"
import { createSicon } from '../createSicon';

export const SiconAmphora = /*#__PURE__*/ createSicon("amphora", [["M10 2L10 7.632C10 8.056 9.728 8.427 9.347 8.614A6 6 0 0 0 6 14C6.006 18 9 21 11 22","M10 5L8 5A2 2 0 0 0 8 9L8.68 9","M14 2L14 7.632C14 8.056 14.272 8.427 14.652 8.614A6 6 0 0 1 18 14C18 18 15 21 13 22","M14 5L16 5A2 2 0 0 1 16 9L15.32 9","M18 22L6 22","M9 2L15 2"],"fbfbff"]);
export default SiconAmphora;
