// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "armchair"
import { createSicon } from '../createSicon';

export const SiconArmchair = /*#__PURE__*/ createSicon("armchair", [["M19 9L19 6A2 2 0 0 0 17 4L7 4A2 2 0 0 0 5 6L5 9","M3 16A2 2 0 0 0 5 18L19 18A2 2 0 0 0 21 16L21 11A2 2 0 0 0 17 11L17 12.5A0.5 0.5 0 0 1 16.5 13L7.5 13A0.5 0.5 0 0 1 7 12.5L7 11A2 2 0 0 0 3 11L3 16Z","M5 18L5 20","M19 18L19 20"],"bbnn"]);
export default SiconArmchair;
