// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-up-left"
import { createSicon } from '../createSicon';

export const SiconArrowUpLeft = /*#__PURE__*/ createSicon("arrow-up-left", [["M7 17L7 7L17 7","M17 17L7 7"],"pp"]);
export default SiconArrowUpLeft;
