// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "arrow-up-z-a"
import { createSicon } from '../createSicon';

export const SiconArrowUpZA = /*#__PURE__*/ createSicon("arrow-up-z-a", ["M3 8L7 4L11 8","M7 4L7 20","M15 4L17.865 4A1 1 0 0 1 18.633 5.64L16.367 8.36A1 1 0 0 0 17.135 10L20 10","M15 20L15 16.5A2.5 2.5 0 0 1 20 16.5L20 20","M20 18L15 18"]);
export default SiconArrowUpZA;
