// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "atom"
import { createSicon } from '../createSicon';

export const SiconAtom = /*#__PURE__*/ createSicon("atom", ["M11 12A1 1 0 1 0 13 12A1 1 0 1 0 11 12Z","M20.2 20.2C22.24 18.17 20.22 12.84 15.7 8.3C11.16 3.78 5.83 1.76 3.8 3.8C1.76 5.83 3.78 11.16 8.3 15.7C12.84 20.22 18.17 22.24 20.2 20.2Z","M15.7 15.7C20.22 11.16 22.24 5.83 20.2 3.8C18.17 1.76 12.84 3.78 8.3 8.3C3.78 12.84 1.76 18.17 3.8 20.2C5.83 22.24 11.16 20.22 15.7 15.7Z"]);
export default SiconAtom;
