// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "badge-japanese-yen"
import { createSicon } from '../createSicon';

export const SiconBadgeJapaneseYen = /*#__PURE__*/ createSicon("badge-japanese-yen", [["M3.85 8.62A4 4 0 0 1 8.63 3.85A4 4 0 0 1 15.37 3.85A4 4 0 0 1 20.15 8.63A4 4 0 0 1 20.15 15.37A4 4 0 0 1 15.38 20.15A4 4 0 0 1 8.63 20.15A4 4 0 0 1 3.85 15.38A4 4 0 0 1 3.85 8.62Z","M9 8L12 11L12 18","M12 11L15 8","M9 12L15 12","M9 16L15 16"],"bnnnn"]);
export default SiconBadgeJapaneseYen;
