// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "badge-info"
import { createSicon } from '../createSicon';

export const SiconBadgeInfo = /*#__PURE__*/ createSicon("badge-info", ["M3.85 8.62A4 4 0 0 1 8.63 3.85A4 4 0 0 1 15.37 3.85A4 4 0 0 1 20.15 8.63A4 4 0 0 1 20.15 15.37A4 4 0 0 1 15.38 20.15A4 4 0 0 1 8.63 20.15A4 4 0 0 1 3.85 15.38A4 4 0 0 1 3.85 8.62Z","M12 16L12 12","M12 8L12.01 8"]);
export default SiconBadgeInfo;
