// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "badge-russian-ruble"
import { createSicon } from '../createSicon';

export const SiconBadgeRussianRuble = /*#__PURE__*/ createSicon("badge-russian-ruble", ["M3.85 8.62A4 4 0 0 1 8.63 3.85A4 4 0 0 1 15.37 3.85A4 4 0 0 1 20.15 8.63A4 4 0 0 1 20.15 15.37A4 4 0 0 1 15.38 20.15A4 4 0 0 1 8.63 20.15A4 4 0 0 1 3.85 15.38A4 4 0 0 1 3.85 8.62Z","M9 16L14 16","M9 12L14 12A2 2 0 1 0 14 8L12 8A1 1 0 0 0 11 9L11 17"]);
export default SiconBadgeRussianRuble;
