// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bean-off"
import { createSicon } from '../createSicon';

export const SiconBeanOff = /*#__PURE__*/ createSicon("bean-off", ["M9 9C8.36 9.64 7.479 9.954 6.598 10.165A6 6 0 0 0 8 22A13.96 13.96 0 0 0 17.9 17.9","M10.75 5.093A6 6 0 0 1 22 8C22 10.411 21.39 12.68 20.317 14.66","M5.341 10.62A4 4 0 0 0 11.828 11.828","M10.62 5.341A4.015 4.015 0 0 1 12.659 7.381","M2 2L22 22"]);
export default SiconBeanOff;
