// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bell"
import { createSicon } from '../createSicon';

export const SiconBell = /*#__PURE__*/ createSicon("bell", ["M10.268 21A2 2 0 0 0 13.732 21","M3.262 15.326A1 1 0 0 0 4 17L20 17A1 1 0 0 0 20.74 15.327C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8C6 12.499 4.589 13.956 3.262 15.326"]);
export default SiconBell;
