// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bell-plus"
import { createSicon } from '../createSicon';

export const SiconBellPlus = /*#__PURE__*/ createSicon("bell-plus", ["M10.268 21A2 2 0 0 0 13.732 21","M15 8L21 8","M18 5L18 11","M20.002 14.464A9 9 0 0 0 20.74 15.327A1 1 0 0 1 20 17L4 17A1 1 0 0 1 3.26 15.327C4.59 13.956 6 12.499 6 8A6 6 0 0 1 14.75 2.668"]);
export default SiconBellPlus;
