// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "between-vertical-end"
import { createSicon } from '../createSicon';

export const SiconBetweenVerticalEnd = /*#__PURE__*/ createSicon("between-vertical-end", ["M4 3L9 3A1 1 0 0 1 10 4L10 15A1 1 0 0 1 9 16L4 16A1 1 0 0 1 3 15L3 4A1 1 0 0 1 4 3Z","M9 22L11.293 19.707A1 1 0 0 1 12.707 19.707L15 22","M15 3L20 3A1 1 0 0 1 21 4L21 15A1 1 0 0 1 20 16L15 16A1 1 0 0 1 14 15L14 4A1 1 0 0 1 15 3Z"]);
export default SiconBetweenVerticalEnd;
