// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "blocks"
import { createSicon } from '../createSicon';

export const SiconBlocks = /*#__PURE__*/ createSicon("blocks", [["M10 22L10 7A1 1 0 0 0 9 6L4 6A2 2 0 0 0 2 8L2 20A2 2 0 0 0 4 22L16 22A2 2 0 0 0 18 20L18 15A1 1 0 0 0 17 14L2 14","M15 2L21 2A1 1 0 0 1 22 3L22 9A1 1 0 0 1 21 10L15 10A1 1 0 0 1 14 9L14 3A1 1 0 0 1 15 2Z"],"fb"]);
export default SiconBlocks;
