// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bold"
import { createSicon } from '../createSicon';

export const SiconBold = /*#__PURE__*/ createSicon("bold", ["M6 12L15 12A4 4 0 0 1 15 20L7 20A1 1 0 0 1 6 19L6 5A1 1 0 0 1 7 4L14 4A4 4 0 0 1 14 12"]);
export default SiconBold;
