// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "book-plus"
import { createSicon } from '../createSicon';

export const SiconBookPlus = /*#__PURE__*/ createSicon("book-plus", ["M12 7L12 13","M4 19.5L4 4.5A2.5 2.5 0 0 1 6.5 2L19 2A1 1 0 0 1 20 3L20 21A1 1 0 0 1 19 22L6.5 22A1 1 0 0 1 6.5 17L20 17","M9 10L15 10"]);
export default SiconBookPlus;
