// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "book-type"
import { createSicon } from '../createSicon';

export const SiconBookType = /*#__PURE__*/ createSicon("book-type", [["M10 13L14 13","M12 6L12 13","M16 8L16 7A1 1 0 0 0 15 6L9 6A1 1 0 0 0 8 7L8 8","M4 19.5L4 4.5A2.5 2.5 0 0 1 6.5 2L19 2A1 1 0 0 1 20 3L20 21A1 1 0 0 1 19 22L6.5 22A1 1 0 0 1 6.5 17L20 17"],"ffbf"]);
export default SiconBookType;
