// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "bot-off"
import { createSicon } from '../createSicon';

export const SiconBotOff = /*#__PURE__*/ createSicon("bot-off", [["M13.67 8L18 8A2 2 0 0 1 20 10L20 14.33","M2 14L4 14","M20 14L22 14","M22 22L2 2","M8 8L6 8A2 2 0 0 0 4 10L4 18A2 2 0 0 0 6 20L18 20A2 2 0 0 0 19.414 19.414","M9 13L9 15","M9.67 4L10.835 4A1.165 1.165 0 0 1 12 5.165L12 6.33"],"fnfnbnf"]);
export default SiconBotOff;
