// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "brain-cog"
import { createSicon } from '../createSicon';

export const SiconBrainCog = /*#__PURE__*/ createSicon("brain-cog", ["M10.852 14.772L10.469 15.695","M10.852 9.228L10.469 8.305","M13.148 14.772L13.53 15.696","M13.531 8.305L13.148 9.228","M14.772 10.852L15.695 10.469","M14.772 13.148L15.695 13.531","M17.598 6.5A3 3 0 1 0 12 5A3 3 0 0 0 6.37 3.554A3 3 0 0 0 6.002 5.125A4 4 0 0 0 3.477 10.896","M17.998 5.125A4 4 0 0 1 20.523 10.896","M19.505 10.294A4 4 0 0 1 18.005 18","M4.032 17.483A4 4 0 0 0 11.464 20C11.644 19.689 12.356 19.689 12.536 20A4 4 0 0 0 19.968 17.484","M4.5 10.291A4 4 0 0 0 6 18","M6.002 5.125A3 3 0 0 0 6.402 6.5","M9.228 10.852L8.305 10.469","M9.228 13.148L8.305 13.531","M9 12A3 3 0 1 0 15 12A3 3 0 1 0 9 12Z"]);
export default SiconBrainCog;
