// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "calendar-sync"
import { createSicon } from '../createSicon';

export const SiconCalendarSync = /*#__PURE__*/ createSicon("calendar-sync", [["M11 10L11 14L15 14","M11 14L12.535 12.395A5 5 0 0 1 20.535 13.895","M16 2L16 5","M21 18L19.465 19.605A5 5 0 0 1 11.465 18.105","M21 22L21 18L17 18","M21 8.517L21 5A2 2 0 0 0 19 3L5 3A2 2 0 0 0 3 5L3 19A2 2 0 0 0 5 21L8.517 21","M3 9L7 9","M8 2L8 5"],"nneffbne"]);
export default SiconCalendarSync;
