// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "calendar-off"
import { createSicon } from '../createSicon';

export const SiconCalendarOff = /*#__PURE__*/ createSicon("calendar-off", ["M16 2L16 5","M2 2L22 22","M21 9L15.5 9","M3 9L9 9","M3.586 3.586A2 2 0 0 0 3 5L3 19A2 2 0 0 0 5 21L19 21A2 2 0 0 0 20.414 20.414","M8.656 3L19 3A2 2 0 0 1 21 5L21 15.344"]);
export default SiconCalendarOff;
