// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "camera"
import { createSicon } from '../createSicon';

export const SiconCamera = /*#__PURE__*/ createSicon("camera", ["M13.997 4A2 2 0 0 1 15.757 5.05L16.243 5.95A2 2 0 0 0 18.003 7L20 7A2 2 0 0 1 22 9L22 18A2 2 0 0 1 20 20L4 20A2 2 0 0 1 2 18L2 9A2 2 0 0 1 4 7L5.997 7A2 2 0 0 0 7.756 5.952L8.245 5.048A2 2 0 0 1 10.004 4L13.997 4Z","M9 13A3 3 0 1 0 15 13A3 3 0 1 0 9 13Z"]);
export default SiconCamera;
