// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "captions-off"
import { createSicon } from '../createSicon';

export const SiconCaptionsOff = /*#__PURE__*/ createSicon("captions-off", ["M10.5 5L19 5A2 2 0 0 1 21 7L21 15.5","M17 11L16.5 11","M19 19L5 19A2 2 0 0 1 3 17L3 7A2 2 0 0 1 5 5","M2 2L22 22","M7 11L11 11","M7 15L9.5 15"]);
export default SiconCaptionsOff;
