// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "case-lower"
import { createSicon } from '../createSicon';

export const SiconCaseLower = /*#__PURE__*/ createSicon("case-lower", ["M10 9L10 16","M14 6L14 16","M14 12.5A3.5 3.5 0 1 0 21 12.5A3.5 3.5 0 1 0 14 12.5Z","M3 12.5A3.5 3.5 0 1 0 10 12.5A3.5 3.5 0 1 0 3 12.5Z"]);
export default SiconCaseLower;
