// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cat"
import { createSicon } from '../createSicon';

export const SiconCat = /*#__PURE__*/ createSicon("cat", [["M12 5C12.67 5 13.35 5.09 14 5.26C15.78 3.26 19.03 2.42 20.42 3C21.82 3.58 20 10 20 10C20.57 11.07 21 12.24 21 13.44C21 17.9 16.97 21 12 21C7.03 21 3 18 3 13.44C3 12.19 3.5 11.04 4 10C4 10 2.11 3.58 3.5 3C4.89 2.42 8.22 3.23 10 5.23A9.04 9.04 0 0 1 12 5Z","M8 14L8 14.5","M16 14L16 14.5","M11.78 16.25L12.22 16.25A0.22 0.22 0 0 1 12.375 16.625L12.375 16.625A0.53 0.53 0 0 1 11.625 16.625L11.625 16.625A0.22 0.22 0 0 1 11.78 16.25Z"],"bnnn"]);
export default SiconCat;
