// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chart-bar"
import { createSicon } from '../createSicon';

export const SiconChartBar = /*#__PURE__*/ createSicon("chart-bar", ["M3 3L3 19A2 2 0 0 0 5 21L21 21","M7 16L15 16","M7 11L19 11","M7 6L10 6"]);
export default SiconChartBar;
