// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chart-network"
import { createSicon } from '../createSicon';

export const SiconChartNetwork = /*#__PURE__*/ createSicon("chart-network", [["M13.11 7.664L14.89 10.336","M14.162 12.788L10.838 14.212","M20 4L13.94 5.515","M3 3L3 19A2 2 0 0 0 5 21L21 21","M10 6A2 2 0 1 0 14 6A2 2 0 1 0 10 6Z","M14 12A2 2 0 1 0 18 12A2 2 0 1 0 14 12Z","M7 15A2 2 0 1 0 11 15A2 2 0 1 0 7 15Z"],"eeffbbb"]);
export default SiconChartNetwork;
