// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chart-bar-increasing"
import { createSicon } from '../createSicon';

export const SiconChartBarIncreasing = /*#__PURE__*/ createSicon("chart-bar-increasing", [["M3 3L3 19A2 2 0 0 0 5 21L21 21","M7 11L15 11","M7 16L19 16","M7 6L10 6"],"pppp"]);
export default SiconChartBarIncreasing;
