// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chart-column"
import { createSicon } from '../createSicon';

export const SiconChartColumn = /*#__PURE__*/ createSicon("chart-column", [["M3 3L3 19A2 2 0 0 0 5 21L21 21","M18 17L18 9","M13 17L13 5","M8 17L8 14"],"pppp"]);
export default SiconChartColumn;
