// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "chevrons-up"
import { createSicon } from '../createSicon';

export const SiconChevronsUp = /*#__PURE__*/ createSicon("chevrons-up", ["M17 11L12.707 6.707A1 1 0 0 0 11.293 6.707L7 11","M17 18L12.707 13.707A1 1 0 0 0 11.293 13.707L7 18"]);
export default SiconChevronsUp;
