// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cigarette-off"
import { createSicon } from '../createSicon';

export const SiconCigaretteOff = /*#__PURE__*/ createSicon("cigarette-off", ["M12 12L3 12A1 1 0 0 0 2 13L2 15A1 1 0 0 0 3 16L16 16","M18 8C18 5.5 16 5.5 16 3","M2 2L22 22","M21 12A1 1 0 0 1 22 13L22 15A1 1 0 0 1 21.5 15.866","M22 8C22 5.5 20 5.5 20 3","M7 12L7 16"]);
export default SiconCigaretteOff;
