// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-equal"
import { createSicon } from '../createSicon';

export const SiconCircleEqual = /*#__PURE__*/ createSicon("circle-equal", ["M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z","M7 10L17 10","M7 14L17 14"]);
export default SiconCircleEqual;
