// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "circle-arrow-out-down-right"
import { createSicon } from '../createSicon';

export const SiconCircleArrowOutDownRight = /*#__PURE__*/ createSicon("circle-arrow-out-down-right", ["M12 22A10 10 0 1 1 22 12","M22 22L12 12","M22 16L22 22L16 22"]);
export default SiconCircleArrowOutDownRight;
