// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "clock-3"
import { createSicon } from '../createSicon';

export const SiconClock3 = /*#__PURE__*/ createSicon("clock-3", ["M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z","M12 6L12 11A1 1 0 0 0 13 12L16 12"]);
export default SiconClock3;
