// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "clock-9"
import { createSicon } from '../createSicon';

export const SiconClock9 = /*#__PURE__*/ createSicon("clock-9", [["M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z","M12 6L12 10A2 2 0 0 1 10 12L8 12"],"bn"]);
export default SiconClock9;
