// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "clock-2"
import { createSicon } from '../createSicon';

export const SiconClock2 = /*#__PURE__*/ createSicon("clock-2", ["M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z","M12 6L12 10.382A1 1 0 0 0 13.447 11.276L16 10"]);
export default SiconClock2;
