// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "clock-arrow-down"
import { createSicon } from '../createSicon';

export const SiconClockArrowDown = /*#__PURE__*/ createSicon("clock-arrow-down", ["M12 6L12 11.382A1 1 0 0 0 12.553 12.276L14 13","M12.337 21.994A10 10 0 1 1 21.925 13.227","M14 18L18 22L22 18","M18 14L18 22"]);
export default SiconClockArrowDown;
