// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cloud-download"
import { createSicon } from '../createSicon';

export const SiconCloudDownload = /*#__PURE__*/ createSicon("cloud-download", [["M12 13L12 21L8 17","M12 21L16 17","M4.393 15.269A7 7 0 1 1 15.71 8L17.5 8A4.5 4.5 0 0 1 19.936 16.284"],"ffb"]);
export default SiconCloudDownload;
