// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cloud-check"
import { createSicon } from '../createSicon';

export const SiconCloudCheck = /*#__PURE__*/ createSicon("cloud-check", ["M17 15L12.207 19.793A1 1 0 0 1 10.793 19.793L9 18","M5.516 16.07A7 7 0 1 1 15.71 8L17.5 8A4.5 4.5 0 0 1 21.001 15.327"]);
export default SiconCloudCheck;
