// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cloud-upload"
import { createSicon } from '../createSicon';

export const SiconCloudUpload = /*#__PURE__*/ createSicon("cloud-upload", [["M12 13L12 21","M4 14.899A7 7 0 1 1 15.71 8L17.5 8A4.5 4.5 0 0 1 20 16.242","M8 17L12 13L16 17"],"fbe"]);
export default SiconCloudUpload;
