// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cloud-hail"
import { createSicon } from '../createSicon';

export const SiconCloudHail = /*#__PURE__*/ createSicon("cloud-hail", [["M4 14.899A7 7 0 1 1 15.71 8L17.5 8A4.5 4.5 0 0 1 20 16.242","M16 14L16 16","M8 14L8 16","M16 20L16.01 20","M8 20L8.01 20","M12 16L12 18","M12 22L12.01 22"],"bneffff"]);
export default SiconCloudHail;
