// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "club"
import { createSicon } from '../createSicon';

export const SiconClub = /*#__PURE__*/ createSicon("club", ["M17.28 9.05A5.5 5.5 0 1 0 6.72 9.05A5.5 5.5 0 1 0 12 17.66A5.5 5.5 0 1 0 17.28 9.06L17.28 9.05Z","M12 17.66L12 22"]);
export default SiconClub;
