// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "code"
import { createSicon } from '../createSicon';

export const SiconCode = /*#__PURE__*/ createSicon("code", [["M16 18L19.172 14.828A4 4 0 0 0 19.172 9.172L16 6","M8 6L4.828 9.172A4 4 0 0 0 4.828 14.828L8 18"],"pp"]);
export default SiconCode;
