// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "coffee"
import { createSicon } from '../createSicon';

export const SiconCoffee = /*#__PURE__*/ createSicon("coffee", ["M10 2L10 4","M14 2L14 4","M16 8A1 1 0 0 1 17 9L17 17A4 4 0 0 1 13 21L7 21A4 4 0 0 1 3 17L3 9A1 1 0 0 1 4 8L18 8A4 4 0 1 1 18 16L17 16","M6 2L6 4"]);
export default SiconCoffee;
