// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "columns-4"
import { createSicon } from '../createSicon';

export const SiconColumns4 = /*#__PURE__*/ createSicon("columns-4", [["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z","M7.5 3L7.5 21","M12 3L12 21","M16.5 3L16.5 21"],"bnnn"]);
export default SiconColumns4;
