// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "columns-3"
import { createSicon } from '../createSicon';

export const SiconColumns3 = /*#__PURE__*/ createSicon("columns-3", ["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z","M9 3L9 21","M15 3L15 21"]);
export default SiconColumns3;
