// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "contrast"
import { createSicon } from '../createSicon';

export const SiconContrast = /*#__PURE__*/ createSicon("contrast", ["M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z","M12 18A6 6 0 0 0 12 6L12 18Z"]);
export default SiconContrast;
