// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "copyleft"
import { createSicon } from '../createSicon';

export const SiconCopyleft = /*#__PURE__*/ createSicon("copyleft", [["M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z","M9.17 14.83A4 4 0 1 0 9.17 9.17"],"bn"]);
export default SiconCopyleft;
