// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "cpu"
import { createSicon } from '../createSicon';

export const SiconCpu = /*#__PURE__*/ createSicon("cpu", [["M12 20L12 22","M12 2L12 4","M17 20L17 22","M17 2L17 4","M2 12L4 12","M2 17L4 17","M2 7L4 7","M20 12L22 12","M20 17L22 17","M20 7L22 7","M7 20L7 22","M7 2L7 4","M6 4L18 4A2 2 0 0 1 20 6L20 18A2 2 0 0 1 18 20L6 20A2 2 0 0 1 4 18L4 6A2 2 0 0 1 6 4Z","M9 8L15 8A1 1 0 0 1 16 9L16 15A1 1 0 0 1 15 16L9 16A1 1 0 0 1 8 15L8 9A1 1 0 0 1 9 8Z"],"nnnnnnnnnnnnbn"]);
export default SiconCpu;
