// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "decimals-arrow-left"
import { createSicon } from '../createSicon';

export const SiconDecimalsArrowLeft = /*#__PURE__*/ createSicon("decimals-arrow-left", [["M13 21L10 18L13 15","M20 18L10 18","M3 11L3.01 11","M8.5 3L8.5 3A2.5 2.5 0 0 1 11 5.5L11 8.5A2.5 2.5 0 0 1 8.5 11L8.5 11A2.5 2.5 0 0 1 6 8.5L6 5.5A2.5 2.5 0 0 1 8.5 3Z"],"fffb"]);
export default SiconDecimalsArrowLeft;
