// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "diamond-minus"
import { createSicon } from '../createSicon';

export const SiconDiamondMinus = /*#__PURE__*/ createSicon("diamond-minus", [["M2.7 10.3A2.41 2.41 0 0 0 2.7 13.71L10.29 21.3A2.41 2.41 0 0 0 13.7 21.3L21.29 13.71A2.41 2.41 0 0 0 21.29 10.3L13.7 2.71A2.41 2.41 0 0 0 10.29 2.71L2.7 10.3Z","M8 12L16 12"],"bn"]);
export default SiconDiamondMinus;
