// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "door-closed"
import { createSicon } from '../createSicon';

export const SiconDoorClosed = /*#__PURE__*/ createSicon("door-closed", ["M19 21L19 5A2 2 0 0 0 17 3L7 3A2 2 0 0 0 5 5L5 21","M2 21L22 21","M9 12L9.01 12"]);
export default SiconDoorClosed;
