// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "download"
import { createSicon } from '../createSicon';

export const SiconDownload = /*#__PURE__*/ createSicon("download", ["M12 15L12 3","M21 15L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 15","M7 10L12 15L17 10"]);
export default SiconDownload;
