// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "drama"
import { createSicon } from '../createSicon';

export const SiconDrama = /*#__PURE__*/ createSicon("drama", ["M10 11L10.01 11","M14 6L14.01 6","M18 6L18.01 6","M6.5 13.1L6.51 13.1","M22 5C22 14 18 17 16 17C14 17 10 14 10 5C10 3 12 2 16 2C20 2 22 3 22 5","M17.4 9.9C16.6 10.7 15.4 10.7 14.6 9.9","M10.1 7.1C9 7.2 7.7 7.7 6 8.6C2.5 10.6 1.3 12.5 2.3 14.2C6.8 22 11.8 22.6 13.5 21.6C14.4 21.1 15.4 19.5 15.4 16.9","M9.1 16.5C9.4 15.4 10.5 14.8 11.5 15.1"]);
export default SiconDrama;
