// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "earth-lock"
import { createSicon } from '../createSicon';

export const SiconEarthLock = /*#__PURE__*/ createSicon("earth-lock", ["M7 3.34L7 5A3 3 0 0 0 10 8","M11 21.95L11 18A2 2 0 0 0 9 16A2 2 0 0 1 7 14L7 13A2 2 0 0 0 5 11L2.05 11","M21.54 15L17 15A2 2 0 0 0 15 17L15 21.54","M12 2A10 10 0 1 0 21.54 15","M20 6L20 4A2 2 0 1 0 16 4L16 6","M15 6L21 6A1 1 0 0 1 22 7L22 10A1 1 0 0 1 21 11L15 11A1 1 0 0 1 14 10L14 7A1 1 0 0 1 15 6Z"]);
export default SiconEarthLock;
