// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "expand"
import { createSicon } from '../createSicon';

export const SiconExpand = /*#__PURE__*/ createSicon("expand", ["M15 15L21 21","M15 9L21 3","M21 16L21 21L16 21","M21 8L21 3L16 3","M3 16L3 21L8 21","M3 21L9 15","M3 8L3 3L8 3","M9 9L3 3"]);
export default SiconExpand;
