// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "eye-off"
import { createSicon } from '../createSicon';

export const SiconEyeOff = /*#__PURE__*/ createSicon("eye-off", [["M10.733 5.076A10.744 10.744 0 0 1 21.938 11.651A1 1 0 0 1 21.938 12.347A10.747 10.747 0 0 1 20.494 14.837","M14.084 14.158A3 3 0 0 1 9.842 9.916","M17.479 17.499A10.75 10.75 0 0 1 2.062 12.348A1 1 0 0 1 2.062 11.652A10.75 10.75 0 0 1 6.508 6.509","M2 2L22 22"],"fnbn"]);
export default SiconEyeOff;
