// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-signal" (alias of "file-volume-2")
import { createSicon } from '../createSicon';

export const SiconFileVolume2 = /*#__PURE__*/ createSicon("file-volume-2", [["M6 22A2 2 0 0 1 4 20L4 4A2 2 0 0 1 6 2L14 2A2.4 2.4 0 0 1 15.704 2.706L19.292 6.294A2.4 2.4 0 0 1 20 8L20 20A2 2 0 0 1 18 22L6 22Z","M14 2L14 7A1 1 0 0 0 15 8L20 8","M8 15L8.01 15","M11.5 13.5A2.5 2.5 0 0 1 11.5 16.5","M15 12A5 5 0 0 1 15 18"],"bnnnn"]);
export default SiconFileVolume2;
