// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-headphone" (alias of "file-audio")
import { createSicon } from '../createSicon';

export const SiconFileAudio = /*#__PURE__*/ createSicon("file-audio", [["M4 6.835L4 4A2 2 0 0 1 6 2L14 2A2.4 2.4 0 0 1 15.706 2.706L19.294 6.294A2.4 2.4 0 0 1 20 8L20 20A2 2 0 0 1 18 22L17.657 22","M14 2L14 7A1 1 0 0 0 15 8L20 8","M2 19A2 2 0 0 1 6 19L6 20A2 2 0 0 1 2 20L2 16A6 6 0 0 1 14 16L14 20A2 2 0 0 1 10 20L10 19A2 2 0 0 1 14 19"],"bnf"]);
export default SiconFileAudio;
