// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-digit"
import { createSicon } from '../createSicon';

export const SiconFileDigit = /*#__PURE__*/ createSicon("file-digit", ["M4 12L4 4A2 2 0 0 1 6 2L14 2A2.4 2.4 0 0 1 15.706 2.706L19.294 6.294A2.4 2.4 0 0 1 20 8L20 20A2 2 0 0 1 18 22","M14 2L14 7A1 1 0 0 0 15 8L20 8","M10 16L11 16A1 1 0 0 1 12 17L12 22","M10 22L14 22","M4 16L4 16A2 2 0 0 1 6 18L6 20A2 2 0 0 1 4 22L4 22A2 2 0 0 1 2 20L2 18A2 2 0 0 1 4 16Z"]);
export default SiconFileDigit;
