// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-check-corner" (alias of "file-check-2")
import { createSicon } from '../createSicon';

export const SiconFileCheck2 = /*#__PURE__*/ createSicon("file-check-2", [["M10.5 22L6 22A2 2 0 0 1 4 20L4 4A2 2 0 0 1 6 2L14 2A2.4 2.4 0 0 1 15.706 2.706L19.294 6.294A2.4 2.4 0 0 1 20 8L20 14","M14 2L14 7A1 1 0 0 0 15 8L20 8","M14 20L15 21A1.414 1.414 0 0 0 17 21L20 18"],"bnf"]);
export default SiconFileCheck2;
