// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "file-output"
import { createSicon } from '../createSicon';

export const SiconFileOutput = /*#__PURE__*/ createSicon("file-output", ["M4.226 20.925A2 2 0 0 0 6 22L18 22A2 2 0 0 0 20 20L20 8A2.4 2.4 0 0 0 19.294 6.294L15.706 2.706A2.4 2.4 0 0 0 14 2L6 2A2 2 0 0 0 4 4L4 7.127","M14 2L14 7A1 1 0 0 0 15 8L20 8","M5 11L2 14","M5 17L2 14L12 14"]);
export default SiconFileOutput;
