// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: Sakani Figma icon set, icon "file-key-2"
import { createSicon } from '../createSicon';

export const SiconFileKey2 = /*#__PURE__*/ createSicon("file-key-2", ["M4 22L18 22C18.53 22 19.039 21.789 19.414 21.414C19.789 21.039 20 20.53 20 20L20 8.657A4 4 0 0 0 18.828 5.828L16.172 3.172A4 4 0 0 0 13.343 2L6 2C5.47 2 4.961 2.211 4.586 2.586C4.211 2.961 4 3.47 4 4L4 10","M14 2L14 6C14 6.53 14.211 7.039 14.586 7.414C14.961 7.789 15.47 8 16 8L20 8","M10 10L5.5 14.5","M9 11L10 12","M6 16C6 17.105 5.105 18 4 18C2.895 18 2 17.105 2 16C2 14.895 2.895 14 4 14C5.105 14 6 14.895 6 16Z"]);
export default SiconFileKey2;
