// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "fish-off"
import { createSicon } from '../createSicon';

export const SiconFishOff = /*#__PURE__*/ createSicon("fish-off", [["M18 12.47L18 12.5","M18 12L18 12.47","M17.525 17.526A6.744 6.744 0 0 1 15 18C11.44 18 7.44 15.47 6.5 12C6.848 10.72 7.614 9.567 8.621 8.62","M12.065 6.532A8.802 8.802 0 0 1 15 6C18.56 6 21.06 8.54 22 12C21.691 13.14 21.214 14.177 20.587 15.058","M7 10.67C7 8 5.58 5.97 2.73 5.5C1.73 7 1.73 10.5 2.96 12C1.72 13.5 1.72 17 2.73 18.5C5.58 18.03 7 16 7 13.33","M14.48 8.958A9.77 9.77 0 0 1 16 6.07","M16 17.93A9.77 9.77 0 0 1 14.272 14.312","M16.01 17.93L15.78 19.33A2 2 0 0 1 13.8 21L9.5 21A5.96 5.96 0 0 0 10.99 17.02","M8.53 3L13.8 3A2 2 0 0 1 15.78 4.67L16.01 6.07","M2 2L22 22"],"ffefbffbff"]);
export default SiconFishOff;
