// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "flask-conical-off"
import { createSicon } from '../createSicon';

export const SiconFlaskConicalOff = /*#__PURE__*/ createSicon("flask-conical-off", ["M10 2L10 4.343","M14 2L14 8.343","M2 2L22 22","M20 20A2 2 0 0 1 18 22L6 22A2 2 0 0 1 4.245 19.04L9.472 9.477","M6.453 15L15 15","M8.5 2L15.5 2"]);
export default SiconFlaskConicalOff;
