// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "flip-vertical-2"
import { createSicon } from '../createSicon';

export const SiconFlipVertical2 = /*#__PURE__*/ createSicon("flip-vertical-2", ["M14.5 5.5L14.5 5.5A3.536 3.536 0 0 1 9.5 5.5L9.5 5.5A1.464 1.464 0 0 1 10.536 3L13.464 3A1.464 1.464 0 0 1 14.5 5.5Z","M14.5 18.5L14.5 18.5A3.536 3.536 0 0 0 9.5 18.5L9.5 18.5A1.464 1.464 0 0 0 10.536 21L13.464 21A1.464 1.464 0 0 0 14.5 18.5Z","M4 12L2 12","M10 12L8 12","M16 12L14 12","M22 12L20 12"]);
export default SiconFlipVertical2;
