// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "flower-2"
import { createSicon } from '../createSicon';

export const SiconFlower2 = /*#__PURE__*/ createSicon("flower-2", ["M12 5A3 3 0 1 1 15 8","M12 5A3 3 0 1 0 9 8","M12 5L12 6","M9 8A3 3 0 1 0 12 11","M9 8L10 8","M15 8A3 3 0 1 1 12 11","M15 8L14 8","M12 11L12 10","M10 8A2 2 0 1 0 14 8A2 2 0 1 0 10 8Z","M12 10L12 22","M12 22C16.2 22 19 20.333 19 17C14.8 17 12 18.667 12 22Z","M12 22C7.8 22 5 20.333 5 17C9.2 17 12 18.667 12 22Z"]);
export default SiconFlower2;
