// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "flower"
import { createSicon } from '../createSicon';

export const SiconFlower = /*#__PURE__*/ createSicon("flower", [["M9 12A3 3 0 1 0 15 12A3 3 0 1 0 9 12Z","M12 16.5A4.5 4.5 0 1 1 7.5 12A4.5 4.5 0 1 1 12 7.5A4.5 4.5 0 1 1 16.5 12A4.5 4.5 0 1 1 12 16.5","M12 7.5L12 9","M7.5 12L9 12","M16.5 12L15 12","M12 16.5L12 15","M8 8L9.88 9.88","M14.12 9.88L16 8","M8 16L9.88 14.12","M14.12 14.12L16 16"],"nbeeeennnn"]);
export default SiconFlower;
