// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "folder-search-2"
import { createSicon } from '../createSicon';

export const SiconFolderSearch2 = /*#__PURE__*/ createSicon("folder-search-2", ["M9 12.5A2.5 2.5 0 1 0 14 12.5A2.5 2.5 0 1 0 9 12.5Z","M20 20A2 2 0 0 0 22 18L22 8A2 2 0 0 0 20 6L12.1 6A2 2 0 0 1 10.41 5.1L9.6 3.9A2 2 0 0 0 7.93 3L4 3A2 2 0 0 0 2 5L2 18A2 2 0 0 0 4 20L20 20Z","M13.3 14.3L15 16"]);
export default SiconFolderSearch2;
