// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "fold-horizontal"
import { createSicon } from '../createSicon';

export const SiconFoldHorizontal = /*#__PURE__*/ createSicon("fold-horizontal", ["M2 12L8 12","M22 12L16 12","M12 2L12 4","M12 8L12 10","M12 14L12 16","M12 20L12 22","M19 9L16 12L19 15","M5 15L8 12L5 9"]);
export default SiconFoldHorizontal;
