// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "fuel"
import { createSicon } from '../createSicon';

export const SiconFuel = /*#__PURE__*/ createSicon("fuel", [["M14 13L16 13A2 2 0 0 1 18 15L18 17A2 2 0 0 0 22 17L22 10.002A2 2 0 0 0 21.41 8.582L18 5","M14 21L14 5A2 2 0 0 0 12 3L5 3A2 2 0 0 0 3 5L3 21","M2 21L15 21","M3 9L14 9"],"bben"]);
export default SiconFuel;
