// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "gem"
import { createSicon } from '../createSicon';

export const SiconGem = /*#__PURE__*/ createSicon("gem", ["M10.5 3L8.139 8.667A1 1 0 0 0 8.106 9.345L11.044 18.894A1 1 0 0 0 12.956 18.894L15.894 9.345A1 1 0 0 0 15.861 8.667L13.5 3","M17 3A2 2 0 0 1 18.6 3.8L21.6 7.8A2 2 0 0 1 21.613 10.182L13.623 21.168A2 2 0 0 1 10.376 21.168L2.386 10.182A2 2 0 0 1 2.4 7.8L5.398 3.803A2 2 0 0 1 7 3L17 3Z","M2 9L22 9"]);
export default SiconGem;
