// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "gift"
import { createSicon } from '../createSicon';

export const SiconGift = /*#__PURE__*/ createSicon("gift", [["M12 7L12 21","M20 11L20 19A2 2 0 0 1 18 21L6 21A2 2 0 0 1 4 19L4 11","M7.5 7A1 1 0 0 1 7.5 2A4.8 8 0 0 1 12 7A4.8 8 0 0 1 16.5 2A1 1 0 0 1 16.5 7","M4 7L20 7A1 1 0 0 1 21 8L21 10A1 1 0 0 1 20 11L4 11A1 1 0 0 1 3 10L3 8A1 1 0 0 1 4 7Z"],"nbbb"]);
export default SiconGift;
