// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "git-branch"
import { createSicon } from '../createSicon';

export const SiconGitBranch = /*#__PURE__*/ createSicon("git-branch", ["M15 6A9 9 0 0 0 6 15L6 3","M15 6A3 3 0 1 0 21 6A3 3 0 1 0 15 6Z","M3 18A3 3 0 1 0 9 18A3 3 0 1 0 3 18Z"]);
export default SiconGitBranch;
