// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "hand-metal"
import { createSicon } from '../createSicon';

export const SiconHandMetal = /*#__PURE__*/ createSicon("hand-metal", ["M18 12.5L18 10A2 2 0 0 0 16 8A2 2 0 0 0 14 10L14 11.4","M14 11L14 9A2 2 0 1 0 10 9L10 11","M10 10.5L10 5A2 2 0 1 0 6 5L6 14","M7 15L5.24 13.24A2 2 0 0 0 2.41 16.06L6.01 19.66C7.5 21.14 9.2 22 12 22L14 22A8 8 0 0 0 22 14L22 7A2 2 0 1 0 18 7L18 12"]);
export default SiconHandMetal;
