// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "hand-fist"
import { createSicon } from '../createSicon';

export const SiconHandFist = /*#__PURE__*/ createSicon("hand-fist", [["M12.035 17.012A3 3 0 0 0 9.035 14.012L8.724 14.01A0.72 0.72 0 0 1 8.219 12.781L9.414 11.586A2 2 0 0 1 10.828 11L12 11A2 2 0 0 0 12 7L9.243 7A3 3 0 0 0 7.121 7.879L4.414 10.586A4.83 4.83 0 0 0 3 14A8 8 0 0 0 11 22L13 22A8 8 0 0 0 21 14L21 7A2 2 0 1 0 17 7L17 9A2 2 0 1 0 21 9","M13.888 9.662A2 2 0 0 0 17 8L17 5A2 2 0 1 0 13 5","M9 5A2 2 0 1 0 5 5L5 10","M9 7L9 4A2 2 0 1 1 13 4L13 7.268"],"fbbb"]);
export default SiconHandFist;
