// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "images"
import { createSicon } from '../createSicon';

export const SiconImages = /*#__PURE__*/ createSicon("images", ["M22 11L20.704 9.704A2.4 2.4 0 0 0 17.296 9.704L11 16","M4 8A2 2 0 0 0 2 10L2 20A2 2 0 0 0 4 22L14 22A2 2 0 0 0 16 20","M12 7A1 1 0 1 0 14 7A1 1 0 1 0 12 7Z","M10 2L20 2A2 2 0 0 1 22 4L22 14A2 2 0 0 1 20 16L10 16A2 2 0 0 1 8 14L8 4A2 2 0 0 1 10 2Z"]);
export default SiconImages;
