// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "list-indent-increase" (alias of "indent-increase")
import { createSicon } from '../createSicon';

export const SiconIndentIncrease = /*#__PURE__*/ createSicon("indent-increase", ["M21 5L11 5","M21 12L11 12","M21 19L11 19","M3 8L6.293 11.293A1 1 0 0 1 6.293 12.707L3 16"]);
export default SiconIndentIncrease;
