// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: Sakani Figma icon set, icon "instagram"
import { createSicon } from '../createSicon';

export const SiconInstagram = /*#__PURE__*/ createSicon("instagram", [["M17.5 6.5L17.51 6.5","M7 2L17 2C19.761 2 22 4.239 22 7L22 17C22 19.761 19.761 22 17 22L7 22C4.239 22 2 19.761 2 17L2 7C2 4.239 4.239 2 7 2Z","M16 11.37C16.123 12.202 15.981 13.052 15.594 13.799C15.206 14.546 14.593 15.152 13.842 15.53C13.09 15.908 12.238 16.04 11.408 15.906C10.577 15.772 9.81 15.38 9.215 14.785C8.62 14.19 8.228 13.423 8.094 12.592C7.96 11.762 8.092 10.91 8.47 10.158C8.849 9.407 9.454 8.794 10.201 8.406C10.948 8.019 11.798 7.877 12.63 8C13.479 8.126 14.265 8.522 14.872 9.128C15.479 9.735 15.874 10.521 16 11.37Z"],"nbn"]);
export default SiconInstagram;
