// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "italic"
import { createSicon } from '../createSicon';

export const SiconItalic = /*#__PURE__*/ createSicon("italic", ["M19 4L10 4","M14 20L5 20","M15 4L9 20"]);
export default SiconItalic;
