// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "keyboard-off"
import { createSicon } from '../createSicon';

export const SiconKeyboardOff = /*#__PURE__*/ createSicon("keyboard-off", [["M20 4A2 2 0 0 1 22 6","M22 6L22 16.41","M7 16L16 16","M9.69 4L20 4","M14 8L14.01 8","M18 8L18.01 8","M2 2L22 22","M20 20L4 20A2 2 0 0 1 2 18L2 6A2 2 0 0 1 4 4","M6 8L6.01 8","M8 12L8.01 12"],"ffnfffeben"]);
export default SiconKeyboardOff;
