// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "layout-template"
import { createSicon } from '../createSicon';

export const SiconLayoutTemplate = /*#__PURE__*/ createSicon("layout-template", ["M4 3L20 3A1 1 0 0 1 21 4L21 9A1 1 0 0 1 20 10L4 10A1 1 0 0 1 3 9L3 4A1 1 0 0 1 4 3Z","M4 14L11 14A1 1 0 0 1 12 15L12 20A1 1 0 0 1 11 21L4 21A1 1 0 0 1 3 20L3 15A1 1 0 0 1 4 14Z","M17 14L20 14A1 1 0 0 1 21 15L21 20A1 1 0 0 1 20 21L17 21A1 1 0 0 1 16 20L16 15A1 1 0 0 1 17 14Z"]);
export default SiconLayoutTemplate;
