// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "layout-list"
import { createSicon } from '../createSicon';

export const SiconLayoutList = /*#__PURE__*/ createSicon("layout-list", ["M4 3L9 3A1 1 0 0 1 10 4L10 9A1 1 0 0 1 9 10L4 10A1 1 0 0 1 3 9L3 4A1 1 0 0 1 4 3Z","M4 14L9 14A1 1 0 0 1 10 15L10 20A1 1 0 0 1 9 21L4 21A1 1 0 0 1 3 20L3 15A1 1 0 0 1 4 14Z","M14 4L21 4","M14 9L21 9","M14 15L21 15","M14 20L21 20"]);
export default SiconLayoutList;
