// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "library"
import { createSicon } from '../createSicon';

export const SiconLibrary = /*#__PURE__*/ createSicon("library", ["M16 6L20 20","M12 6L12 20","M8 8L8 20","M4 4L4 20"]);
export default SiconLibrary;
