// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "list-check"
import { createSicon } from '../createSicon';

export const SiconListCheck = /*#__PURE__*/ createSicon("list-check", ["M16 5L3 5","M16 12L3 12","M11 19L3 19","M15 18L16.293 19.293A1 1 0 0 0 17.707 19.293L21 16"]);
export default SiconListCheck;
