// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "list-checks"
import { createSicon } from '../createSicon';

export const SiconListChecks = /*#__PURE__*/ createSicon("list-checks", ["M13 5L21 5","M13 12L21 12","M13 19L21 19","M3 17L4.293 18.293A1 1 0 0 0 5.707 18.293L9 15","M3 7L4.293 8.293A1 1 0 0 0 5.707 8.293L9 5"]);
export default SiconListChecks;
