// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "locate"
import { createSicon } from '../createSicon';

export const SiconLocate = /*#__PURE__*/ createSicon("locate", ["M2 12L5 12","M19 12L22 12","M12 2L12 5","M12 19L12 22","M5 12A7 7 0 1 0 19 12A7 7 0 1 0 5 12Z"]);
export default SiconLocate;
