// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "log-in"
import { createSicon } from '../createSicon';

export const SiconLogIn = /*#__PURE__*/ createSicon("log-in", ["M10 17L15 12L10 7","M15 12L3 12","M15 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L15 21"]);
export default SiconLogIn;
