// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "log-out"
import { createSicon } from '../createSicon';

export const SiconLogOut = /*#__PURE__*/ createSicon("log-out", [["M16 17L21 12L16 7","M21 12L9 12","M9 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3L9 3"],"ffb"]);
export default SiconLogOut;
