// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "logs"
import { createSicon } from '../createSicon';

export const SiconLogs = /*#__PURE__*/ createSicon("logs", ["M3 5L4 5","M3 12L4 12","M3 19L4 19","M8 5L9 5","M8 12L9 12","M8 19L9 19","M13 5L21 5","M13 12L21 12","M13 19L21 19"]);
export default SiconLogs;
