// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "luggage"
import { createSicon } from '../createSicon';

export const SiconLuggage = /*#__PURE__*/ createSicon("luggage", [["M6 20A2 2 0 0 1 4 18L4 8A2 2 0 0 1 6 6L18 6A2 2 0 0 1 20 8L20 18A2 2 0 0 1 18 20","M8 18L8 4A2 2 0 0 1 10 2L14 2A2 2 0 0 1 16 4L16 18","M10 20L14 20","M14 20A2 2 0 1 0 18 20A2 2 0 1 0 14 20Z","M6 20A2 2 0 1 0 10 20A2 2 0 1 0 6 20Z"],"bbeee"]);
export default SiconLuggage;
