// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "mail-minus"
import { createSicon } from '../createSicon';

export const SiconMailMinus = /*#__PURE__*/ createSicon("mail-minus", ["M22 15L22 6A2 2 0 0 0 20 4L4 4A2 2 0 0 0 2 6L2 18C2 19.1 2.9 20 4 20L12 20","M22 7L13.03 12.7A1.94 1.94 0 0 1 10.97 12.7L2 7","M16 19L22 19"]);
export default SiconMailMinus;
