// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "mailbox"
import { createSicon } from '../createSicon';

export const SiconMailbox = /*#__PURE__*/ createSicon("mailbox", ["M22 17A2 2 0 0 1 20 19L4 19A2 2 0 0 1 2 17L2 9.5C2 7 4 5 6.5 5L18 5C20.2 5 22 6.8 22 9L22 17Z","M15 9L17 9A1 1 0 0 1 18 10L18 11","M6.5 5C9 5 11 7 11 9.5L11 17A2 2 0 0 1 9 19","M6 10L7 10"]);
export default SiconMailbox;
