// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "mail-check"
import { createSicon } from '../createSicon';

export const SiconMailCheck = /*#__PURE__*/ createSicon("mail-check", ["M22 13L22 6A2 2 0 0 0 20 4L4 4A2 2 0 0 0 2 6L2 18C2 19.1 2.9 20 4 20L12 20","M22 7L13.03 12.7A1.94 1.94 0 0 1 10.97 12.7L2 7","M16 19L17 20A1.414 1.414 0 0 0 19 20L22 17"]);
export default SiconMailCheck;
