// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "map-pin-check-inside"
import { createSicon } from '../createSicon';

export const SiconMapPinCheckInside = /*#__PURE__*/ createSicon("map-pin-check-inside", ["M20 10C20 14.993 14.461 20.193 12.601 21.799A1 1 0 0 1 11.399 21.799C9.539 20.193 4 14.993 4 10A8 8 0 0 1 20 10","M9 10L10.293 11.293A1 1 0 0 0 11.707 11.293L15 8"]);
export default SiconMapPinCheckInside;
