// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "map-pinned"
import { createSicon } from '../createSicon';

export const SiconMapPinned = /*#__PURE__*/ createSicon("map-pinned", ["M18 8C18 11.613 14.131 15.429 12.607 16.795A1 1 0 0 1 11.393 16.795C9.87 15.429 6 11.613 6 8A6 6 0 0 1 18 8","M10 8A2 2 0 1 0 14 8A2 2 0 1 0 10 8Z","M8.714 14L5.004 14A1 1 0 0 0 4.056 14.683L2.052 20.683A1 1 0 0 0 3 22L21 22A1 1 0 0 0 21.948 20.684L19.948 14.684A1 1 0 0 0 18.999 14L15.287 14"]);
export default SiconMapPinned;
