// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "map-plus"
import { createSicon } from '../createSicon';

export const SiconMapPlus = /*#__PURE__*/ createSicon("map-plus", ["M11 19L9.894 18.448A2 2 0 0 0 8.106 18.448L4.447 20.278A1 1 0 0 1 3 19.381L3 6.618A1 1 0 0 1 3.553 5.724L8.106 3.447A2 2 0 0 1 9.894 3.447L14.106 5.553A2 2 0 0 0 15.894 5.553L19.553 3.723A1 1 0 0 1 21 4.619L21 12","M15 5.764L15 12","M18 15L18 21","M21 18L15 18","M9 3.236L9 18.236"]);
export default SiconMapPlus;
