// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "martini"
import { createSicon } from '../createSicon';

export const SiconMartini = /*#__PURE__*/ createSicon("martini", ["M12 12L4.207 4.207A0.707 0.707 0 0 1 4.707 3L19.293 3A0.707 0.707 0 0 1 19.793 4.207L12 12Z","M12 12L12 22","M7 22L17 22"]);
export default SiconMartini;
