// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "medal"
import { createSicon } from '../createSicon';

export const SiconMedal = /*#__PURE__*/ createSicon("medal", ["M7.21 15L2.66 7.14A2 2 0 0 1 2.79 4.94L4.4 2.8A2 2 0 0 1 6 2L18 2A2 2 0 0 1 19.6 2.8L21.2 4.94A2 2 0 0 1 21.34 7.14L16.79 15","M11 12L5.12 2.2","M13 12L18.88 2.2","M8 7L16 7","M7 17A5 5 0 1 0 17 17A5 5 0 1 0 7 17Z","M12 18L12 16.25A0.25 0.25 0 0 0 11.75 16L11.5 16"]);
export default SiconMedal;
