// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "message-square-dot"
import { createSicon } from '../createSicon';

export const SiconMessageSquareDot = /*#__PURE__*/ createSicon("message-square-dot", [["M12.7 3L4 3A2 2 0 0 0 2 5L2 21.286A0.71 0.71 0 0 0 3.212 21.788L5.414 19.586A2 2 0 0 1 6.828 19L20 19A2 2 0 0 0 22 17L22 12.3","M16 6A3 3 0 1 0 22 6A3 3 0 1 0 16 6Z"],"bf"]);
export default SiconMessageSquareDot;
