// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "message-square-code"
import { createSicon } from '../createSicon';

export const SiconMessageSquareCode = /*#__PURE__*/ createSicon("message-square-code", ["M22 17A2 2 0 0 1 20 19L6.828 19A2 2 0 0 0 5.414 19.586L3.212 21.788A0.71 0.71 0 0 1 2 21.286L2 5A2 2 0 0 1 4 3L20 3A2 2 0 0 1 22 5L22 17Z","M10 8L7.707 10.293A1 1 0 0 0 7.707 11.707L10 14","M14 14L16.293 11.707A1 1 0 0 0 16.293 10.293L14 8"]);
export default SiconMessageSquareCode;
