// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "message-circle-code"
import { createSicon } from '../createSicon';

export const SiconMessageCircleCode = /*#__PURE__*/ createSicon("message-circle-code", ["M10 9L7.707 11.293A1 1 0 0 0 7.707 12.707L10 15","M14 15L16.293 12.707A1 1 0 0 0 16.293 11.293L14 9","M2.992 16.342A2 2 0 0 1 3.086 17.509L2.021 20.799A1 1 0 0 0 3.257 21.967L6.67 20.969A2 2 0 0 1 7.769 21.061A10 10 0 1 0 2.992 16.342"]);
export default SiconMessageCircleCode;
