// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "microwave"
import { createSicon } from '../createSicon';

export const SiconMicrowave = /*#__PURE__*/ createSicon("microwave", [["M4 4L20 4A2 2 0 0 1 22 6L22 17A2 2 0 0 1 20 19L4 19A2 2 0 0 1 2 17L2 6A2 2 0 0 1 4 4Z","M7 8L13 8A1 1 0 0 1 14 9L14 14A1 1 0 0 1 13 15L7 15A1 1 0 0 1 6 14L6 9A1 1 0 0 1 7 8Z","M18 8L18 15","M6 19L6 21","M18 19L18 21"],"bnnnn"]);
export default SiconMicrowave;
