// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "monitor-stop"
import { createSicon } from '../createSicon';

export const SiconMonitorStop = /*#__PURE__*/ createSicon("monitor-stop", ["M12 17L12 21","M8 21L16 21","M4 3L20 3A2 2 0 0 1 22 5L22 15A2 2 0 0 1 20 17L4 17A2 2 0 0 1 2 15L2 5A2 2 0 0 1 4 3Z","M10 7L14 7A1 1 0 0 1 15 8L15 12A1 1 0 0 1 14 13L10 13A1 1 0 0 1 9 12L9 8A1 1 0 0 1 10 7Z"]);
export default SiconMonitorStop;
