// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "monitor"
import { createSicon } from '../createSicon';

export const SiconMonitor = /*#__PURE__*/ createSicon("monitor", ["M4 3L20 3A2 2 0 0 1 22 5L22 15A2 2 0 0 1 20 17L4 17A2 2 0 0 1 2 15L2 5A2 2 0 0 1 4 3Z","M8 21L16 21","M12 17L12 21"]);
export default SiconMonitor;
