// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "mountain"
import { createSicon } from '../createSicon';

export const SiconMountain = /*#__PURE__*/ createSicon("mountain", [["M10 7L10.419 7.838A2.548 2.548 0 0 0 14.5 8.5L14.5 8.5A2.185 2.185 0 0 1 18.118 9.354L20.377 16.13A3.7 3.7 0 0 1 16.867 21L7.133 21A3.7 3.7 0 0 1 3.623 16.13L6.586 7.243A1.852 1.852 0 0 1 10 7Z"],"b"]);
export default SiconMountain;
