// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "mouse"
import { createSicon } from '../createSicon';

export const SiconMouse = /*#__PURE__*/ createSicon("mouse", ["M12 2L12 2A7 7 0 0 1 19 9L19 15A7 7 0 0 1 12 22L12 22A7 7 0 0 1 5 15L5 9A7 7 0 0 1 12 2Z","M12 6L12 10"]);
export default SiconMouse;
