// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "mouse-pointer-click"
import { createSicon } from '../createSicon';

export const SiconMousePointerClick = /*#__PURE__*/ createSicon("mouse-pointer-click", [["M14 4.1L12 6","M5.1 8L2.2 7.2","M6 12L4.1 14","M7.2 2.2L8 5.1","M9.037 9.69A0.498 0.498 0 0 1 9.69 9.037L20.69 13.537A0.5 0.5 0 0 1 20.616 14.486L16.267 15.527A1 1 0 0 0 15.527 16.266L14.487 20.616A0.5 0.5 0 0 1 13.537 20.69L9.037 9.69Z"],"ffffb"]);
export default SiconMousePointerClick;
