// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "move-right"
import { createSicon } from '../createSicon';

export const SiconMoveRight = /*#__PURE__*/ createSicon("move-right", ["M18 8L22 12L18 16","M2 12L22 12"]);
export default SiconMoveRight;
