// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "move"
import { createSicon } from '../createSicon';

export const SiconMove = /*#__PURE__*/ createSicon("move", ["M12 2L12 22","M15 19L12 22L9 19","M19 9L22 12L19 15","M2 12L22 12","M5 9L2 12L5 15","M9 5L12 2L15 5"]);
export default SiconMove;
