// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "music"
import { createSicon } from '../createSicon';

export const SiconMusic = /*#__PURE__*/ createSicon("music", [["M9 18L9 8.389A4 4 0 0 1 12.342 4.443L16.342 3.776A4 4 0 0 1 21 7.722L21 16","M3 18A3 3 0 1 0 9 18A3 3 0 1 0 3 18Z","M15 16A3 3 0 1 0 21 16A3 3 0 1 0 15 16Z"],"bfn"]);
export default SiconMusic;
