// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "notebook-text"
import { createSicon } from '../createSicon';

export const SiconNotebookText = /*#__PURE__*/ createSicon("notebook-text", ["M2 6L6 6","M2 10L6 10","M2 14L6 14","M2 18L6 18","M6 2L18 2A2 2 0 0 1 20 4L20 20A2 2 0 0 1 18 22L6 22A2 2 0 0 1 4 20L4 4A2 2 0 0 1 6 2Z","M9.5 8L14.5 8","M9.5 12L16 12","M9.5 16L14 16"]);
export default SiconNotebookText;
