// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "notepad-text"
import { createSicon } from '../createSicon';

export const SiconNotepadText = /*#__PURE__*/ createSicon("notepad-text", [["M8 2L8 6","M12 2L12 6","M16 2L16 6","M6 4L18 4A2 2 0 0 1 20 6L20 20A2 2 0 0 1 18 22L6 22A2 2 0 0 1 4 20L4 6A2 2 0 0 1 6 4Z","M8 10L14 10","M8 14L16 14","M8 18L13 18"],"nnnbnnn"]);
export default SiconNotepadText;
