// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "notebook-tabs"
import { createSicon } from '../createSicon';

export const SiconNotebookTabs = /*#__PURE__*/ createSicon("notebook-tabs", [["M2 6L6 6","M2 10L6 10","M2 14L6 14","M2 18L6 18","M6 2L18 2A2 2 0 0 1 20 4L20 20A2 2 0 0 1 18 22L6 22A2 2 0 0 1 4 20L4 4A2 2 0 0 1 6 2Z","M15 2L15 22","M15 7L20 7","M15 12L20 12","M15 17L20 17"],"nnnnbnnnn"]);
export default SiconNotebookTabs;
