// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "package-plus"
import { createSicon } from '../createSicon';

export const SiconPackagePlus = /*#__PURE__*/ createSicon("package-plus", [["M12 22L12 12","M16 17L22 17","M19 14L19 20","M21 10.535L21 8A2 2 0 0 0 20 6.27L13 2.27A2 2 0 0 0 11 2.27L4 6.27A2 2 0 0 0 3 8L3 16A2 2 0 0 0 4 17.729L11 21.729A2 2 0 0 0 13 21.73L14.675 20.775","M3.29 7L12 12L20.71 7","M7.5 4.27L16.497 9.418"],"nffbnn"]);
export default SiconPackagePlus;
