// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "package-2"
import { createSicon } from '../createSicon';

export const SiconPackage2 = /*#__PURE__*/ createSicon("package-2", [["M12 3L12 9","M16.76 3A2 2 0 0 1 18.56 4.1L20.79 8.579A2 2 0 0 1 21 9.47L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 9.472A2 2 0 0 1 3.211 8.578L5.45 4.1A2 2 0 0 1 7.24 3L16.76 3Z","M3.054 9.013L20.947 9.013"],"nbn"]);
export default SiconPackage2;
