// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "panel-bottom-close"
import { createSicon } from '../createSicon';

export const SiconPanelBottomClose = /*#__PURE__*/ createSicon("panel-bottom-close", [["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z","M3 15L21 15","M15 8L13.5 9.5A2.121 2.121 0 0 1 10.5 9.5L9 8"],"bnn"]);
export default SiconPanelBottomClose;
