// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "paw-print"
import { createSicon } from '../createSicon';

export const SiconPawPrint = /*#__PURE__*/ createSicon("paw-print", ["M9 4A2 2 0 1 0 13 4A2 2 0 1 0 9 4Z","M16 8A2 2 0 1 0 20 8A2 2 0 1 0 16 8Z","M18 16A2 2 0 1 0 22 16A2 2 0 1 0 18 16Z","M9 10A5 5 0 0 1 14 15L14 18.5A3.5 3.5 0 0 1 7.16 19.545Q6.52 17.48 4.46 16.84A3.5 3.5 0 0 1 5.5 10L9 10Z"]);
export default SiconPawPrint;
