// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pc-case"
import { createSicon } from '../createSicon';

export const SiconPcCase = /*#__PURE__*/ createSicon("pc-case", ["M7 2L17 2A2 2 0 0 1 19 4L19 20A2 2 0 0 1 17 22L7 22A2 2 0 0 1 5 20L5 4A2 2 0 0 1 7 2Z","M15 14L15.01 14","M9 6L15 6","M9 10L15 10"]);
export default SiconPcCase;
