// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "percent"
import { createSicon } from '../createSicon';

export const SiconPercent = /*#__PURE__*/ createSicon("percent", ["M19 5L5 19","M4 6.5A2.5 2.5 0 1 0 9 6.5A2.5 2.5 0 1 0 4 6.5Z","M15 17.5A2.5 2.5 0 1 0 20 17.5A2.5 2.5 0 1 0 15 17.5Z"]);
export default SiconPercent;
