// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pin-off"
import { createSicon } from '../createSicon';

export const SiconPinOff = /*#__PURE__*/ createSicon("pin-off", ["M12 17L12 22","M15 9.34L15 7A1 1 0 0 1 16 6A2 2 0 0 0 16 2L7.89 2","M2 2L22 22","M9 9L9 10.76A2 2 0 0 1 7.89 12.55L6.11 13.45A2 2 0 0 0 5 15.24L5 16A1 1 0 0 0 6 17L17 17"]);
export default SiconPinOff;
