// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pin"
import { createSicon } from '../createSicon';

export const SiconPin = /*#__PURE__*/ createSicon("pin", [["M12 17L12 22","M9 10.76A2 2 0 0 1 7.89 12.55L6.11 13.45A2 2 0 0 0 5 15.24L5 16A1 1 0 0 0 6 17L18 17A1 1 0 0 0 19 16L19 15.24A2 2 0 0 0 17.89 13.45L16.11 12.55A2 2 0 0 1 15 10.76L15 7A1 1 0 0 1 16 6A2 2 0 0 0 16 2L8 2A2 2 0 0 0 8 6A1 1 0 0 1 9 7L9 10.76Z"],"fb"]);
export default SiconPin;
