// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pipette"
import { createSicon } from '../createSicon';

export const SiconPipette = /*#__PURE__*/ createSicon("pipette", ["M12 9L3.586 17.414A2 2 0 0 0 3 18.828L3 20.172A2 2 0 0 1 2.414 21.586A2 2 0 0 1 3.828 21L5.172 21A2 2 0 0 0 6.586 20.414L15 12","M18.2 9.2L18.4 9.4A1 1 0 1 1 15.4 12.4L11.6 8.6A1 1 0 1 1 14.6 5.6L14.8 5.8A0.283 0.283 0 0 0 15.2 5.8L18.4 2.6A1 1 0 1 1 21.4 5.6L18.2 8.8A0.283 0.283 0 0 0 18.2 9.2Z","M2 22L2.414 21.586"]);
export default SiconPipette;
