// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pizza"
import { createSicon } from '../createSicon';

export const SiconPizza = /*#__PURE__*/ createSicon("pizza", ["M12 14L11 15","M13.75 18.25L12.5 19.67","M17.775 5.654A15.68 15.68 0 0 0 5.654 17.774","M18.8 9.3A1 1 0 0 0 20.9 17","M21.964 20.732A1 1 0 0 1 20.732 21.964L2.732 16.964A1 1 0 0 1 2.037 15.732A19.68 19.68 0 0 1 15.732 2.037A1 1 0 0 1 16.964 2.732L21.964 20.732Z"]);
export default SiconPizza;
