// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pointer-off"
import { createSicon } from '../createSicon';

export const SiconPointerOff = /*#__PURE__*/ createSicon("pointer-off", ["M10 4.5L10 4A2 2 0 0 0 7.59 2.043","M13.9 8.4A2 2 0 0 0 12.64 7.105","M21.7 16.2A8 8 0 0 0 22 14L22 11A2 2 0 1 0 18 11L18 10A2 2 0 0 0 14.37 8.842","M7 15L5.2 13.2A2 2 0 0 0 2.41 16.06L6 19.7A7.74 7.74 0 0 0 12 22L14 22A8 8 0 0 0 19.657 19.657","M6 6L6 14","M2 2L22 22"]);
export default SiconPointerOff;
