// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "puzzle"
import { createSicon } from '../createSicon';

export const SiconPuzzle = /*#__PURE__*/ createSicon("puzzle", [["M15.39 4.39A1 1 0 0 0 17.07 3.916A2.5 2.5 0 1 1 20.084 6.931A1 1 0 0 0 19.61 8.611L21.293 10.293A2.414 2.414 0 0 1 21.293 13.707L19.61 15.39A1 1 0 0 1 17.93 14.916A2.5 2.5 0 1 0 14.916 17.931A1 1 0 0 1 15.39 19.611L13.707 21.293A2.414 2.414 0 0 1 10.293 21.293L8.61 19.61A1 1 0 0 0 6.93 20.084A2.5 2.5 0 1 1 3.916 17.069A1 1 0 0 0 4.39 15.389L2.707 13.707A2.414 2.414 0 0 1 2.707 10.293L4.39 8.61A1 1 0 0 1 6.07 9.084A2.5 2.5 0 1 0 9.084 6.069A1 1 0 0 1 8.61 4.389L10.293 2.707A2.414 2.414 0 0 1 13.707 2.707L15.39 4.39Z"],"b"]);
export default SiconPuzzle;
