// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "pyramid"
import { createSicon } from '../createSicon';

export const SiconPyramid = /*#__PURE__*/ createSicon("pyramid", ["M2.5 16.88A1 1 0 0 1 2.18 15.45L11.18 2.43A1 1 0 0 1 12.82 2.43L21.82 15.44A1 1 0 0 1 21.5 16.88L12.99 21.74A2 2 0 0 1 11.01 21.74L2.5 16.88Z","M12 2L12 22"]);
export default SiconPyramid;
