// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "radar"
import { createSicon } from '../createSicon';

export const SiconRadar = /*#__PURE__*/ createSicon("radar", [["M19.07 4.93A10 10 0 0 0 6.99 3.34","M4 6L4.01 6","M2.29 9.62A10 10 0 1 0 21.31 8.35","M16.24 7.76A6 6 0 1 0 8.23 16.67","M12 18L12.01 18","M17.99 11.66A6 6 0 0 1 15.77 16.67","M10 12A2 2 0 1 0 14 12A2 2 0 1 0 10 12Z","M13.41 10.59L19.07 4.93"],"ffbfnnnf"]);
export default SiconRadar;
