// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "radiation"
import { createSicon } from '../createSicon';

export const SiconRadiation = /*#__PURE__*/ createSicon("radiation", ["M12 12L12.01 12","M14 15.464A4 4 0 0 1 10 15.464L7.528 19.746A1 1 0 0 0 7.993 21.162A10 10 0 0 0 16.007 21.162A1 1 0 0 0 16.472 19.746L14 15.464Z","M16 12A4 4 0 0 0 14 8.536L16.472 4.254A1 1 0 0 1 17.932 3.949A10 10 0 0 1 21.938 10.889A1 1 0 0 1 21 12L16 12Z","M8 12A4 4 0 0 1 10 8.536L7.528 4.254A1 1 0 0 0 6.068 3.949A10 10 0 0 0 2.062 10.889A1 1 0 0 0 3 12L8 12Z"]);
export default SiconRadiation;
