// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: Sakani Figma icon set, icon "rail-symbol"
import { createSicon } from '../createSicon';

export const SiconRailSymbol = /*#__PURE__*/ createSicon("rail-symbol", ["M5 15L19 15","M5 9L19 9","M14 20L11.5 17.5A3.536 3.536 0 0 1 11.5 12.5L12.5 11.5A3.536 3.536 0 0 0 12.5 6.5L10 4"]);
export default SiconRailSymbol;
