// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "rat"
import { createSicon } from '../createSicon';

export const SiconRat = /*#__PURE__*/ createSicon("rat", ["M13 22L4 22A2 2 0 0 1 4 18L16 18","M13.236 18A3 3 0 0 0 11.036 13","M16 9L16.01 9","M16.82 3.94A3 3 0 1 1 20.057 8.808L21.872 11.395A1.5 1.5 0 0 1 20.372 13.495L17.5 13.042A3 3 0 0 0 14 16.042","M17 4.988A3 3 0 1 0 11.8 7.04A7 7 0 0 0 4 14.015A4 4 0 0 0 8 18"]);
export default SiconRat;
