// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "receipt-russian-ruble"
import { createSicon } from '../createSicon';

export const SiconReceiptRussianRuble = /*#__PURE__*/ createSicon("receipt-russian-ruble", ["M4 3A1 1 0 0 1 5 2A1.3 1.3 0 0 1 5.7 2.2L6.633 2.8A1.3 1.3 0 0 0 8.033 2.8L8.967 2.2A1.3 1.3 0 0 1 10.367 2.2L11.3 2.8A1.3 1.3 0 0 0 12.7 2.8L13.633 2.2A1.3 1.3 0 0 1 15.033 2.2L15.967 2.8A1.3 1.3 0 0 0 17.367 2.8L18.3 2.2A1.3 1.3 0 0 1 19 2A1 1 0 0 1 20 3L20 21A1 1 0 0 1 19 22A1.3 1.3 0 0 1 18.3 21.8L17.367 21.2A1.3 1.3 0 0 0 15.967 21.2L15.033 21.8A1.3 1.3 0 0 1 13.633 21.8L12.7 21.2A1.3 1.3 0 0 0 11.3 21.2L10.367 21.8A1.3 1.3 0 0 1 8.967 21.8L8.033 21.2A1.3 1.3 0 0 0 6.633 21.2L5.7 21.8A1.3 1.3 0 0 1 5 22A1 1 0 0 1 4 21L4 3Z","M8 11L13 11A2 2 0 0 0 13 7L11 7A1 1 0 0 0 10 8L10 17","M8 15L13 15"]);
export default SiconReceiptRussianRuble;
