// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "refresh-ccw"
import { createSicon } from '../createSicon';

export const SiconRefreshCcw = /*#__PURE__*/ createSicon("refresh-ccw", [["M21 12A9 9 0 0 0 12 3A9.75 9.75 0 0 0 5.26 5.74L3 8","M3 3L3 8L8 8","M3 12A9 9 0 0 0 12 21A9.75 9.75 0 0 0 18.74 18.26L21 16","M16 16L21 16L21 21"],"pppp"]);
export default SiconRefreshCcw;
