// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "refresh-cw-off"
import { createSicon } from '../createSicon';

export const SiconRefreshCwOff = /*#__PURE__*/ createSicon("refresh-cw-off", [["M21 8L18.74 5.74A9.75 9.75 0 0 0 12 3C11 3 10.03 3.16 9.13 3.47","M8 16L3 16L3 21","M3 12C3 9.51 4 7.26 5.64 5.64","M3 16L5.26 18.26A9.75 9.75 0 0 0 12 21C14.49 21 16.74 20 18.36 18.36","M21 12C21 13 20.84 13.97 20.53 14.87","M21 3L21 8L16 8","M22 22L2 2"],"ppppppp"]);
export default SiconRefreshCwOff;
