// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "repeat-2"
import { createSicon } from '../createSicon';

export const SiconRepeat2 = /*#__PURE__*/ createSicon("repeat-2", ["M2 9L5 6L8 9","M13 18L7 18A2 2 0 0 1 5 16L5 6","M22 15L19 18L16 15","M11 6L17 6A2 2 0 0 1 19 8L19 18"]);
export default SiconRepeat2;
