// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ribbon"
import { createSicon } from '../createSicon';

export const SiconRibbon = /*#__PURE__*/ createSicon("ribbon", ["M12 11.22C11 9.997 10 9 10 8A2 2 0 0 1 14 8C14 9 13.002 10.002 11.99 11.22","M12 18L14.57 14.5","M6.243 9.016A7 7 0 0 1 17.75 9.007","M9.35 14.53L12 11.22","M9.35 14.53C7.728 12.246 6 10.221 6 7A6 5 0 0 1 18 7C17.995 10.22 16.222 12.235 14.57 14.5L18.127 19.027A1 1 0 0 1 17.924 20.457L16.03 21.817A1 1 0 0 1 14.646 21.602L12 18L9.321 21.593A1 1 0 0 1 7.931 21.806L6.066 20.453A1 1 0 0 1 5.863 19.031L9.35 14.53Z"]);
export default SiconRibbon;
