// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ruler-dimension-line"
import { createSicon } from '../createSicon';

export const SiconRulerDimensionLine = /*#__PURE__*/ createSicon("ruler-dimension-line", ["M10 15L10 12","M14 15L14 12","M18 15L18 12","M2 8L2 4","M22 6L2 6","M22 8L22 4","M6 15L6 12","M4 12L20 12A2 2 0 0 1 22 14L22 18A2 2 0 0 1 20 20L4 20A2 2 0 0 1 2 18L2 14A2 2 0 0 1 4 12Z"]);
export default SiconRulerDimensionLine;
