// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "sailboat"
import { createSicon } from '../createSicon';

export const SiconSailboat = /*#__PURE__*/ createSicon("sailboat", ["M10 2L10 17","M7 22A4 4 0 0 1 3 18A1 1 0 0 1 4 17L20 17A1 1 0 0 1 21 18A4 4 0 0 1 17 22L7 22Z","M9.159 2.46A1 1 0 0 1 10.68 2.267L20.657 11.247A1 1 0 0 1 20 13L4 13A1 1 0 0 1 3.176 11.433L9.159 2.46Z"]);
export default SiconSailboat;
