// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "save-all"
import { createSicon } from '../createSicon';

export const SiconSaveAll = /*#__PURE__*/ createSicon("save-all", ["M10 2L10 5A1 1 0 0 0 11 6L16 6","M18 18L18 12A1 1 0 0 0 17 11L11 11A1 1 0 0 0 10 12L10 18","M18 22L4 22A2 2 0 0 1 2 20L2 6","M8 18A2 2 0 0 1 6 16L6 4A2 2 0 0 1 8 2L17.172 2A2 2 0 0 1 18.586 2.586L21.414 5.414A2 2 0 0 1 22 6.828L22 16A2 2 0 0 1 19.99 18L8 18Z"]);
export default SiconSaveAll;
