// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "scroll-text"
import { createSicon } from '../createSicon';

export const SiconScrollText = /*#__PURE__*/ createSicon("scroll-text", [["M15 12L10 12","M15 8L10 8","M19 17L19 5A2 2 0 0 0 17 3L4 3","M8 21L20 21A2 2 0 0 0 22 19L22 18A1 1 0 0 0 21 17L11 17A1 1 0 0 0 10 18L10 19A2 2 0 1 1 6 19L6 5A2 2 0 1 0 2 5L2 7A1 1 0 0 0 3 8L6 8"],"pppp"]);
export default SiconScrollText;
