// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "send-horizontal"
import { createSicon } from '../createSicon';

export const SiconSendHorizontal = /*#__PURE__*/ createSicon("send-horizontal", [["M3.714 3.048A0.498 0.498 0 0 0 3.031 3.675L5.874 11.302A2 2 0 0 1 5.874 12.698L3.032 20.325A0.498 0.498 0 0 0 3.714 20.952L21.714 12.452A0.5 0.5 0 0 0 21.714 11.548L3.714 3.048Z","M6 12L22 12"],"bn"]);
export default SiconSendHorizontal;
