// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "separator-vertical"
import { createSicon } from '../createSicon';

export const SiconSeparatorVertical = /*#__PURE__*/ createSicon("separator-vertical", ["M12 3L12 21","M16 16L19.293 12.707A1 1 0 0 0 19.293 11.293L16 8","M8 8L4.707 11.293A1 1 0 0 0 4.707 12.707L8 16"]);
export default SiconSeparatorVertical;
