// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "slice"
import { createSicon } from '../createSicon';

export const SiconSlice = /*#__PURE__*/ createSicon("slice", [["M11 16.586L11 19A1 1 0 0 1 10 20L6 20A1.657 1.657 0 0 1 4.828 17.172L18.37 3.63A1 1 0 1 1 21.37 6.63L11.707 16.293A1 1 0 0 1 10.293 16.293L8 14"],"p"]);
export default SiconSlice;
