// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "face-slightly-smiling" (alias of "smile")
import { createSicon } from '../createSicon';

export const SiconSmile = /*#__PURE__*/ createSicon("smile", [["M15 10L15 9","M16.472 15A6 6 0 0 1 7.529 15","M9 10L9 9","M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z"],"nnnb"]);
export default SiconSmile;
