// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "sofa"
import { createSicon } from '../createSicon';

export const SiconSofa = /*#__PURE__*/ createSicon("sofa", ["M20 9L20 6A2 2 0 0 0 18 4L6 4A2 2 0 0 0 4 6L4 9","M2 16A2 2 0 0 0 4 18L20 18A2 2 0 0 0 22 16L22 11A2 2 0 0 0 18 11L18 12.5A0.5 0.5 0 0 1 17.5 13L6.5 13A0.5 0.5 0 0 1 6 12.5L6 11A2 2 0 0 0 2 11L2 16Z","M4 18L4 20","M20 18L20 20","M12 4L12 13"]);
export default SiconSofa;
