// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "spell-check-2"
import { createSicon } from '../createSicon';

export const SiconSpellCheck2 = /*#__PURE__*/ createSicon("spell-check-2", ["M6 16L9 10A3.354 3.354 0 0 1 15 10L18 16","M8 12L16 12","M4 21C5.1 21 5.1 20 6.3 20C7.5 20 7.4 21 8.6 21C9.7 21 9.7 20 10.9 20C12 20 12 21 13.2 21C14.3 21 14.3 20 15.5 20C16.6 20 16.6 21 17.8 21C18.9 21 18.9 20 20.1 20"]);
export default SiconSpellCheck2;
