// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "squares-intersect"
import { createSicon } from '../createSicon';

export const SiconSquaresIntersect = /*#__PURE__*/ createSicon("squares-intersect", ["M10 22A2 2 0 0 1 8 20","M14 2A2 2 0 0 1 16 4","M16 22L14 22","M2 10L2 8","M2 4A2 2 0 0 1 4 2","M20 8A2 2 0 0 1 22 10","M22 14L22 16","M22 20A2 2 0 0 1 20 22","M4 16A2 2 0 0 1 2 14","M8 10A2 2 0 0 1 10 8L15 8A1 1 0 0 1 16 9L16 14A2 2 0 0 1 14 16L9 16A1 1 0 0 1 8 15L8 10Z","M8 2L10 2"]);
export default SiconSquaresIntersect;
