// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-dashed-bottom-code"
import { createSicon } from '../createSicon';

export const SiconSquareDashedBottomCode = /*#__PURE__*/ createSicon("square-dashed-bottom-code", ["M10 9.5L9 10.75A2.001 2.001 0 0 0 9 13.25L10 14.5","M14 21L15 21","M14 9.5L15 10.75A2.001 2.001 0 0 1 15 13.25L14 14.5","M5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21","M9 21L10 21"]);
export default SiconSquareDashedBottomCode;
