// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-chevron-down"
import { createSicon } from '../createSicon';

export const SiconSquareChevronDown = /*#__PURE__*/ createSicon("square-chevron-down", ["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z","M16 10L12.707 13.293A1 1 0 0 1 11.293 13.293L8 10"]);
export default SiconSquareChevronDown;
