// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-chevron-left"
import { createSicon } from '../createSicon';

export const SiconSquareChevronLeft = /*#__PURE__*/ createSicon("square-chevron-left", [["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z","M14 16L12 14A2.828 2.828 0 0 1 12 10L14 8"],"bn"]);
export default SiconSquareChevronLeft;
