// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-stack"
import { createSicon } from '../createSicon';

export const SiconSquareStack = /*#__PURE__*/ createSicon("square-stack", [["M4 10C2.9 10 2 9.1 2 8L2 4C2 2.9 2.9 2 4 2L8 2C9.1 2 10 2.9 10 4","M10 16C8.9 16 8 15.1 8 14L8 10C8 8.9 8.9 8 10 8L14 8C15.1 8 16 8.9 16 10","M16 14L20 14A2 2 0 0 1 22 16L22 20A2 2 0 0 1 20 22L16 22A2 2 0 0 1 14 20L14 16A2 2 0 0 1 16 14Z"],"bbb"]);
export default SiconSquareStack;
