// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-sigma"
import { createSicon } from '../createSicon';

export const SiconSquareSigma = /*#__PURE__*/ createSicon("square-sigma", ["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z","M16 8.9L16 7.95A0.95 0.95 0 0 0 15.05 7L11.202 7A1.539 1.539 0 0 0 10 9.5L10.151 9.689A3.7 3.7 0 0 1 10.151 14.311L10 14.5A1.539 1.539 0 0 0 11.202 17L15.05 17A0.95 0.95 0 0 0 16 16.05L16 15.1"]);
export default SiconSquareSigma;
