// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-chevron-right"
import { createSicon } from '../createSicon';

export const SiconSquareChevronRight = /*#__PURE__*/ createSicon("square-chevron-right", ["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z","M10 8L13.293 11.293A1 1 0 0 1 13.293 12.707L10 16"]);
export default SiconSquareChevronRight;
