// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-arrow-down"
import { createSicon } from '../createSicon';

export const SiconSquareArrowDown = /*#__PURE__*/ createSicon("square-arrow-down", [["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z","M12 8L12 16","M8 12L12 16L16 12"],"bnn"]);
export default SiconSquareArrowDown;
