// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-split-vertical"
import { createSicon } from '../createSicon';

export const SiconSquareSplitVertical = /*#__PURE__*/ createSicon("square-split-vertical", ["M2 12L22 12","M21 16L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 16","M3 8L3 5A2 2 0 0 1 5 3L19 3A2 2 0 0 1 21 5L21 8"]);
export default SiconSquareSplitVertical;
