// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-square"
import { createSicon } from '../createSicon';

export const SiconSquareSquare = /*#__PURE__*/ createSicon("square-square", [["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z","M9 8L15 8A1 1 0 0 1 16 9L16 15A1 1 0 0 1 15 16L9 16A1 1 0 0 1 8 15L8 9A1 1 0 0 1 9 8Z"],"bn"]);
export default SiconSquareSquare;
