// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "square-stop"
import { createSicon } from '../createSicon';

export const SiconSquareStop = /*#__PURE__*/ createSicon("square-stop", [["M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z","M10 9L14 9A1 1 0 0 1 15 10L15 14A1 1 0 0 1 14 15L10 15A1 1 0 0 1 9 14L9 10A1 1 0 0 1 10 9Z"],"bn"]);
export default SiconSquareStop;
