// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "star-off"
import { createSicon } from '../createSicon';

export const SiconStarOff = /*#__PURE__*/ createSicon("star-off", [["M10.344 4.688L11.525 2.295A0.53 0.53 0 0 1 12.475 2.295L14.785 6.974A2.12 2.12 0 0 0 16.38 8.134L21.546 8.89A0.53 0.53 0 0 1 21.84 9.794L18.603 12.946","M17.945 17.945L18.375 20.45A0.53 0.53 0 0 1 17.604 21.01L12.986 18.582A2.12 2.12 0 0 0 11.013 18.582L6.396 21.01A0.53 0.53 0 0 1 5.626 20.45L6.507 15.311A2.12 2.12 0 0 0 5.896 13.432L2.16 9.795A0.53 0.53 0 0 1 2.454 8.889L7.619 8.134A8 8 0 0 0 8.019 8.035","M2 2L22 22"],"bbn"]);
export default SiconStarOff;
