// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "sticky-note"
import { createSicon } from '../createSicon';

export const SiconStickyNote = /*#__PURE__*/ createSicon("sticky-note", ["M21 9A2.4 2.4 0 0 0 20.294 7.294L16.706 3.706A2.4 2.4 0 0 0 15 3L5 3A2 2 0 0 0 3 5L3 19A2 2 0 0 0 5 21L19 21A2 2 0 0 0 21 19L21 9Z","M15 3L15 8A1 1 0 0 0 16 9L21 9"]);
export default SiconStickyNote;
