// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "strikethrough"
import { createSicon } from '../createSicon';

export const SiconStrikethrough = /*#__PURE__*/ createSicon("strikethrough", ["M16 4L9 4A3 3 0 0 0 6.17 8","M14 12A4 4 0 0 1 14 20L6 20","M4 12L20 12"]);
export default SiconStrikethrough;
