// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "sun-snow"
import { createSicon } from '../createSicon';

export const SiconSunSnow = /*#__PURE__*/ createSicon("sun-snow", ["M10 21L10 20","M10 4L10 3","M10 9A3 3 0 0 0 10 15","M14 20L14.915 18.171A1 1 0 0 1 15.988 17.634L18 18","M14 4L14.915 5.829A1 1 0 0 0 15.988 6.366L18 6","M17 21L14.224 15.447A1 1 0 0 1 14.224 14.553L15.5 12L22 12","M17 3L14.224 8.553A1 1 0 0 0 14.224 9.447L15.5 12","M2 12L3 12","M20 10L18.95 11.4A1 1 0 0 0 18.95 12.6L20 14","M3.64 18.36L4.34 17.66","M4.34 6.34L3.64 5.64"]);
export default SiconSunSnow;
