// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "sun-snow"
import { createSicon } from '../createSicon';

export const SiconSunSnow = /*#__PURE__*/ createSicon("sun-snow", [["M10 21L10 20","M10 4L10 3","M10 9A3 3 0 0 0 10 15","M14 20L14.625 18.75A1.863 1.863 0 0 1 16.625 17.75L18 18","M14 4L14.625 5.25A1.863 1.863 0 0 0 16.625 6.25L18 6","M17 21L14.75 16.5A3.354 3.354 0 0 1 14.75 13.5L15.5 12L22 12","M17 3L14.75 7.5A3.354 3.354 0 0 0 14.75 10.5L15.5 12","M2 12L3 12","M20 10L19.25 11A1.667 1.667 0 0 0 19.25 13L20 14","M3.64 18.36L4.34 17.66","M4.34 6.34L3.64 5.64"],"ffbefbffeff"]);
export default SiconSunSnow;
