// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "sun-moon"
import { createSicon } from '../createSicon';

export const SiconSunMoon = /*#__PURE__*/ createSicon("sun-moon", ["M12 2L12 4","M14.837 16.385A6 6 0 1 1 7.614 9.163C8.238 9.016 8.584 9.823 8.329 10.411A4 4 0 0 0 13.589 15.67C14.178 15.415 14.985 15.76 14.837 16.385","M16 12A4 4 0 0 0 12 8","M19 5L17.744 6.256","M20 12L22 12"]);
export default SiconSunMoon;
