// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "table-cells-split"
import { createSicon } from '../createSicon';

export const SiconTableCellsSplit = /*#__PURE__*/ createSicon("table-cells-split", [["M12 15L12 9","M3 15L21 15","M3 9L21 9","M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z"],"nnnb"]);
export default SiconTableCellsSplit;
