// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tablet"
import { createSicon } from '../createSicon';

export const SiconTablet = /*#__PURE__*/ createSicon("tablet", ["M6 2L18 2A2 2 0 0 1 20 4L20 20A2 2 0 0 1 18 22L6 22A2 2 0 0 1 4 20L4 4A2 2 0 0 1 6 2Z","M12 18L12.01 18"]);
export default SiconTablet;
