// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "table-cells-merge"
import { createSicon } from '../createSicon';

export const SiconTableCellsMerge = /*#__PURE__*/ createSicon("table-cells-merge", ["M12 21L12 15","M12 9L12 3","M3 15L21 15","M3 9L21 9","M5 3L19 3A2 2 0 0 1 21 5L21 19A2 2 0 0 1 19 21L5 21A2 2 0 0 1 3 19L3 5A2 2 0 0 1 5 3Z"]);
export default SiconTableCellsMerge;
