// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tangent"
import { createSicon } from '../createSicon';

export const SiconTangent = /*#__PURE__*/ createSicon("tangent", ["M15 4A2 2 0 1 0 19 4A2 2 0 1 0 15 4Z","M15.59 5.41L5.41 15.59","M2 17A2 2 0 1 0 6 17A2 2 0 1 0 2 17Z","M12 22C12 22 8 13 10.5 10.5C13 8 22 12 22 12"]);
export default SiconTangent;
