// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "text-search"
import { createSicon } from '../createSicon';

export const SiconTextSearch = /*#__PURE__*/ createSicon("text-search", ["M21 5L3 5","M10 12L3 12","M10 19L3 19","M14 15A3 3 0 1 0 20 15A3 3 0 1 0 14 15Z","M21 19L19.1 17.1"]);
export default SiconTextSearch;
