// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "thermometer-snowflake"
import { createSicon } from '../createSicon';

export const SiconThermometerSnowflake = /*#__PURE__*/ createSicon("thermometer-snowflake", ["M10 20L9.085 18.171A1 1 0 0 0 8.012 17.634L6 18","M10 4L9.085 5.829A1 1 0 0 1 8.012 6.366L6 6","M10.585 15L10 15","M2 12L8.5 12L10 9","M20 14.54A4 4 0 1 1 16 14.54L16 4A2 2 0 0 1 20 4L20 14.54Z","M4 10L5.05 11.4A1 1 0 0 1 5.05 12.6L4 14","M7 21L10 15L8.5 12","M7 3L10 9L12 9"]);
export default SiconThermometerSnowflake;
