// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "torus"
import { createSicon } from '../createSicon';

export const SiconTorus = /*#__PURE__*/ createSicon("torus", [["M9 11A3 2 0 1 0 15 11A3 2 0 1 0 9 11Z","M2 12.5A10 8.5 0 1 0 22 12.5A10 8.5 0 1 0 2 12.5Z"],"nb"]);
export default SiconTorus;
