// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tractor"
import { createSicon } from '../createSicon';

export const SiconTractor = /*#__PURE__*/ createSicon("tractor", [["M10 11L21 11.9A1 1 0 0 1 21.8 13L21.135 17.158A1 1 0 0 1 20.147 18L20 18","M16 18L11 18","M18 5A1 1 0 0 0 17 6L17 11.573","M3 4L11.129 4A1 1 0 0 1 12.119 4.863L13 11.246","M4 11L4 4","M7 15L7.01 15","M8 10.1L8 4","M16 18A2 2 0 1 0 20 18A2 2 0 1 0 16 18Z","M2 15A5 5 0 1 0 12 15A5 5 0 1 0 2 15Z"],"bffffnffb"]);
export default SiconTractor;
