// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "tree-palm"
import { createSicon } from '../createSicon';

export const SiconTreePalm = /*#__PURE__*/ createSicon("tree-palm", ["M13 8C13 5.24 10.54 3 7.5 3C4.46 3 2 5.24 2 8L3.586 8A1 1 0 0 0 4.293 7.707L4.5 7.5A0.707 0.707 0 0 1 5.5 7.5L5.707 7.707A1 1 0 0 0 6.414 8L10 8","M13 7.14A5.82 5.82 0 0 1 16.5 6C19.54 6 22 8.24 22 11L19.414 11A1 1 0 0 1 18.707 10.707L18.5 10.5A0.707 0.707 0 0 0 17.5 10.5L17.293 10.707A1 1 0 0 1 16.586 11L14 11","M5.89 9.71C3.74 11.86 3.59 15.18 5.54 17.14L9.78 12.89L10.48 12.19L11.19 11.48L13.31 9.36C11.36 7.4 8.04 7.56 5.89 9.71","M11 15.5C11.5 18 10.83 20 10 22L14 22C16 16.5 13.5 10 13 8"]);
export default SiconTreePalm;
