// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "triangle"
import { createSicon } from '../createSicon';

export const SiconTriangle = /*#__PURE__*/ createSicon("triangle", ["M13.73 4A2 2 0 0 0 10.27 4L2.27 18A2 2 0 0 0 4 21L20 21A2 2 0 0 0 21.73 18L13.73 4Z"]);
export default SiconTriangle;
