// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "triangle-right"
import { createSicon } from '../createSicon';

export const SiconTriangleRight = /*#__PURE__*/ createSicon("triangle-right", ["M22 18A2 2 0 0 1 20 20L3 20C1.9 20 1.7 19.4 2.6 18.7L20.4 4.3C21.3 3.6 22 3.9 22 5L22 18Z"]);
export default SiconTriangleRight;
