// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "ungroup"
import { createSicon } from '../createSicon';

export const SiconUngroup = /*#__PURE__*/ createSicon("ungroup", ["M13 14L19 14A2 2 0 0 1 21 16L21 19A2 2 0 0 1 19 21L13 21A2 2 0 0 1 11 19L11 16A2 2 0 0 1 13 14Z","M5 3L11 3A2 2 0 0 1 13 5L13 8A2 2 0 0 1 11 10L5 10A2 2 0 0 1 3 8L3 5A2 2 0 0 1 5 3Z"]);
export default SiconUngroup;
