// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "unplug"
import { createSicon } from '../createSicon';

export const SiconUnplug = /*#__PURE__*/ createSicon("unplug", ["M19 5L22 2","M2 22L5 19","M6.3 20.3A2.4 2.4 0 0 0 9.7 20.3L10.85 19.15A1.626 1.626 0 0 0 10.85 16.85L7.15 13.15A1.626 1.626 0 0 0 4.85 13.15L3.7 14.3A2.4 2.4 0 0 0 3.7 17.7L6.3 20.3Z","M7.5 13.5L10 11","M10.5 16.5L13 14","M13.15 7.15L16.85 10.85A1.626 1.626 0 0 0 19.15 10.85L20.3 9.7A2.4 2.4 0 0 0 20.3 6.3L17.7 3.7A2.4 2.4 0 0 0 14.3 3.7L13.15 4.85A1.626 1.626 0 0 0 13.15 7.15Z"]);
export default SiconUnplug;
