// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "users-round"
import { createSicon } from '../createSicon';

export const SiconUsersRound = /*#__PURE__*/ createSicon("users-round", ["M18 21A8 8 0 0 0 2 21","M5 8A5 5 0 1 0 15 8A5 5 0 1 0 5 8Z","M22 20C22 16.63 20 13.5 18 12A5 5 0 0 0 17.55 3.7"]);
export default SiconUsersRound;
