// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "venus-and-mars"
import { createSicon } from '../createSicon';

export const SiconVenusAndMars = /*#__PURE__*/ createSicon("venus-and-mars", [["M10 20L14 20","M12 16L12 22","M17 2L21 2L21 6","M21 2L15.54 7.46","M7 11A5 5 0 1 0 17 11A5 5 0 1 0 7 11Z"],"ffffb"]);
export default SiconVenusAndMars;
