// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "vibrate-off"
import { createSicon } from '../createSicon';

export const SiconVibrateOff = /*#__PURE__*/ createSicon("vibrate-off", ["M2 8L3.293 9.293A1 1 0 0 1 3.293 10.707L2.707 11.293A1 1 0 0 0 2.707 12.707L3.293 13.293A1 1 0 0 1 3.293 14.707L2 16","M22 8L20.707 9.293A1 1 0 0 0 20.707 10.707L21.293 11.293A1 1 0 0 1 21.293 12.707L20.707 13.293A1 1 0 0 0 20.707 14.707L22 16","M8 8L8 18C8 18.55 8.45 19 9 19L15 19C15.55 19 16 18.55 16 18L16 16","M16 10.34L16 6C16 5.45 15.55 5 15 5L10.66 5","M2 2L22 22"]);
export default SiconVibrateOff;
