// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "wand-sparkles"
import { createSicon } from '../createSicon';

export const SiconWandSparkles = /*#__PURE__*/ createSicon("wand-sparkles", ["M21.64 3.64L20.36 2.36A1.21 1.21 0 0 0 18.64 2.36L2.36 18.64A1.21 1.21 0 0 0 2.36 20.36L3.64 21.64A1.2 1.2 0 0 0 5.36 21.64L21.64 5.36A1.2 1.2 0 0 0 21.64 3.64","M14 7L17 10","M5 6L5 10","M19 14L19 18","M10 2L10 4","M7 8L3 8","M21 16L17 16","M11 3L9 3"]);
export default SiconWandSparkles;
