// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "waves-ladder"
import { createSicon } from '../createSicon';

export const SiconWavesLadder = /*#__PURE__*/ createSicon("waves-ladder", [["M19 5A2 2 0 0 0 17 7L17 18","M2 18C2.6 18.5 3.2 19 4.5 19C7 19 7 17 9.5 17C12.1 17 11.9 19 14.5 19C17 19 17 17 19.5 17C20.8 17 21.4 17.5 22 18","M7 13L17 13","M7 9L17 9","M9 5A2 2 0 0 0 7 7L7 18"],"ppppp"]);
export default SiconWavesLadder;
