// Generated by scripts/sicons/generate.mjs -- do not edit by hand.
// Shape data: lucide-react 1.41.0 (ISC), icon "weight"
import { createSicon } from '../createSicon';

export const SiconWeight = /*#__PURE__*/ createSicon("weight", ["M9 5A3 3 0 1 0 15 5A3 3 0 1 0 9 5Z","M6.5 8A2 2 0 0 0 4.595 9.46L2.1 18.5A2 2 0 0 0 4 21L20 21A2 2 0 0 0 21.925 18.46L19.4 9.5A2 2 0 0 0 17.48 8L6.5 8Z"]);
export default SiconWeight;
